In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
yemen_cholera_data = pd.read_csv('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_data/yemen_governate_level_cholera_data_feb.csv')

In [3]:
yemen_cholera_data.Date

0       2018-02-18
1       2018-02-18
2       2018-02-18
3       2018-02-18
4       2018-02-18
5       2018-02-18
6       2018-02-18
7       2018-02-18
8       2018-02-18
9       2018-02-18
10      2018-02-18
11      2018-02-18
12      2018-02-18
13      2018-02-18
14      2018-02-18
15      2018-02-18
16      2018-02-18
17      2018-02-18
18      2018-02-18
19      2018-02-18
20      2018-02-18
21      2018-02-18
22      2018-02-11
23      2018-02-11
24      2018-02-11
25      2018-02-11
26      2018-02-11
27      2018-02-11
28      2018-02-11
29      2018-02-11
           ...
2884    2017-05-27
2885    2017-05-27
2886    2017-05-27
2887    2017-05-27
2888    2017-05-27
2889    2017-05-27
2890    2017-05-27
2891    2017-05-27
2892    2017-05-27
2893    2017-05-27
2894    2017-05-27
2895    2017-05-27
2896    2017-05-27
2897    2017-05-22
2898    2017-05-22
2899    2017-05-22
2900    2017-05-22
2901    2017-05-22
2902    2017-05-22
2903    2017-05-22
2904    2017-05-22
2905    2017-05-22
2906    2017-05-22
2907    2017-05-22
2908    2017-05-22
2909    2017-05-22
2910    2017-05-22
2911    2017-05-22
2912    2017-05-22
2913    2017-05-22
Name: Date, Length: 2914, dtype: object

In [4]:
yemen_cholera_data.Date = pd.to_datetime(yemen_cholera_data.Date, format = '%Y-%m-%d')

In [5]:
governorate_iso_replace_dict = {'Amran':'YE-AM', 'Al Mahwit':'YE-MW', "Al Dhale'e":'YE-DA', 'Hajjah':'YE-HJ', "Sana'a":'YE-SN', 'Dhamar':'YE-DH',
       'Abyan':'YE-AB', 'Al Hudaydah':'YE-HU', 'Al Bayda':'YE-BA', 'Amanat Al Asimah':'YE-SA', 'Raymah':'YE-RA',
       'Al Jawf':'YE-JA', 'Lahj':'YE-LA', 'Aden':'YE-AD', 'Ibb':'YE-IB', 'Taizz':'YE-TA', 'Marib':'YE-MA', "Sa'ada":'YE-SD',
       'Al Maharah':'YE-MR', 'Shabwah':'YE-SH', 'Moklla':'YE-HD', "Say'on":np.nan, 'Al-Hudaydah':'YE-HU',
       'Al_Jawf':'YE-JA', "Ma'areb":'YE-MA', 'AL Mahrah':'YE-MR'}

In [6]:
#yemen_cholera_data['governorate_isocode'] = yemen_cholera_data.Governorate.map(governorate_iso_replace_dict)

In [8]:
#yemen_cholera_data.to_csv('/Users/Rohil/Documents/iGEM/yemen/yemen_governate_level_cholera_data_feb.csv', index = False)

In [7]:
yemen_cholera_case_data_crosstab = pd.crosstab(index = yemen_cholera_data['Date'], columns = yemen_cholera_data['governorate_isocode'], values = yemen_cholera_data['Cases'], aggfunc = 'sum')

In [8]:
yemen_cholera_death_data_crosstab = pd.crosstab(index = yemen_cholera_data['Date'], columns = yemen_cholera_data['governorate_isocode'], values = yemen_cholera_data['Deaths'], aggfunc = 'sum')

In [14]:
yemen_cholera_case_data_crosstab.to_csv('/Users/Rohil/Documents/iGEM/yemen/yemen_cholera_total_case_crosstab.csv')
yemen_cholera_death_data_crosstab.to_csv('/Users/Rohil/Documents/iGEM/yemen/yemen_cholera_total_death_crosstab.csv')

In [31]:
plt.close('all')

In [56]:
total_case_fig, total_case_ax = plt.subplots(1,1, figsize=(7,6))
yemen_cholera_case_data_crosstab.plot(ax = total_case_ax, title = 'total cases over time')
total_case_ax.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
total_case_fig.savefig('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_plots/total_case_data_plot.png', bbox_inches = 'tight')
plt.close('all')

In [55]:
total_death_fig, total_death_ax = plt.subplots(1,1, figsize=(7,6))
yemen_cholera_death_data_crosstab.plot(ax = total_death_ax, title = 'total deaths over time')
total_death_ax.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
total_death_fig.savefig('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_plots/total_death_data_plot.png', bbox_inches = 'tight')
plt.close('all')

In [54]:
attack_rate_fig, attack_rate_ax = plt.subplots(1,1, figsize=(7,6))
yemen_cholera_attack_rate_data_crosstab.plot(ax = attack_rate_ax, title = 'attack rate per thousand over time')
attack_rate_ax.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
attack_rate_fig.savefig('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_plots/attack_rate_data_plot.png', bbox_inches = 'tight')
plt.close('all')

In [9]:
# this is exactly what we want
len(yemen_cholera_case_data_crosstab.columns)

21

In [10]:
# need to convert data into stationary (changes in cholera cases from one day to another)

# the function below creates a differenced series
def difference(dataset, interval=1):
    
    diff = pd.Series()
    
    for i in range(interval, len(dataset)):
        
        print ('new total cases: ' + str(dataset[i]) + ', old total cases: ' + str(dataset[i-1]))
        print ('new date: ' + str(dataset.index[i]) + ', old date: ' + str(dataset.index[i-1]))
        
        # get the number of new cases in the ith time step
        case_delta = dataset[i] - dataset[i - interval]
        
        # number of days between the ith time step and i-1th time step
        time_delta = (dataset.index[i] - dataset.index[i - interval]).days

        idx = pd.date_range(dataset.index[i - interval], dataset.index[i])[1:]
        
        # normalize the number of new cases against the number of days in between the two time steps
        value = case_delta / time_delta
        
        # linearly interpolating - if there are multiple days between each time cholera is reported
        # we assume that the rate of change is uniform across that time period
        # therefore we repeat the same value for each day
        repeat_value = np.repeat(value, time_delta)
        
        #print (repeat_value, idx)
        print (pd.Series(repeat_value, idx))
        
        diff = diff.append(pd.Series(repeat_value, idx))

        
    return ((diff))

In [11]:
yemen_cholera_case_data_diff = pd.DataFrame()
for column in yemen_cholera_case_data_crosstab:
    yemen_cholera_case_data_diff[column]  = (difference(yemen_cholera_case_data_crosstab[column]))

new total cases: 1365.0, old total cases: 1068.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    59.4
2017-05-24    59.4
2017-05-25    59.4
2017-05-26    59.4
2017-05-27    59.4
Freq: D, dtype: float64
new total cases: 1587.0, old total cases: 1365.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    74.0
2017-05-29    74.0
2017-05-30    74.0
Freq: D, dtype: float64
new total cases: 1920.0, old total cases: 1587.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    66.6
2017-06-01    66.6
2017-06-02    66.6
2017-06-03    66.6
2017-06-04    66.6
Freq: D, dtype: float64
new total cases: 2171.0, old total cases: 1920.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    83.666667
2017-06-06    83.666667
2017-06-07    83.666667
Freq: D, dtype: float64
new total cases: 2480.0, old total cases: 2171.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    103.0
2017-06-09    103.0
2017-06-10    103.0
Freq: D, dtype: float64
new total cases: 2611.0, old total cases: 2480.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    65.5
2017-06-12    65.5
Freq: D, dtype: float64
new total cases: 2675.0, old total cases: 2611.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    64.0
Freq: D, dtype: float64
new total cases: 2771.0, old total cases: 2675.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    96.0
Freq: D, dtype: float64
new total cases: 3094.0, old total cases: 2771.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    107.666667
2017-06-16    107.666667
2017-06-17    107.666667
Freq: D, dtype: float64
new total cases: 3194.0, old total cases: 3094.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    100.0
Freq: D, dtype: float64
new total cases: 3304.0, old total cases: 3194.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    110.0
Freq: D, dtype: float64
new total cases: 3305.0, old total cases: 3304.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    1.0
Freq: D, dtype: float64
new total cases: 3309.0, old total cases: 3305.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    4.0
Freq: D, dtype: float64
new total cases: 3635.0, old total cases: 3309.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    326.0
Freq: D, dtype: float64
new total cases: 3762.0, old total cases: 3635.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    127.0
Freq: D, dtype: float64
new total cases: 3953.0, old total cases: 3762.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    191.0
Freq: D, dtype: float64
new total cases: 3955.0, old total cases: 3953.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    2.0
Freq: D, dtype: float64
new total cases: 4086.0, old total cases: 3955.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    131.0
Freq: D, dtype: float64
new total cases: 4092.0, old total cases: 4086.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    6.0
Freq: D, dtype: float64
new total cases: 4513.0, old total cases: 4092.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    421.0
Freq: D, dtype: float64
new total cases: 4783.0, old total cases: 4513.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    270.0
Freq: D, dtype: float64
new total cases: 5016.0, old total cases: 4783.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    233.0
Freq: D, dtype: float64
new total cases: 5338.0, old total cases: 5016.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    322.0
Freq: D, dtype: float64
new total cases: 5976.0, old total cases: 5338.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    638.0
Freq: D, dtype: float64
new total cases: 6314.0, old total cases: 5976.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    338.0
Freq: D, dtype: float64
new total cases: 6682.0, old total cases: 6314.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    368.0
Freq: D, dtype: float64
new total cases: 6971.0, old total cases: 6682.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    289.0
Freq: D, dtype: float64
new total cases: 7293.0, old total cases: 6971.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    322.0
Freq: D, dtype: float64
new total cases: 7582.0, old total cases: 7293.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    289.0
Freq: D, dtype: float64
new total cases: 8270.0, old total cases: 7582.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    229.333333
2017-07-09    229.333333
2017-07-10    229.333333
Freq: D, dtype: float64
new total cases: 8602.0, old total cases: 8270.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    332.0
Freq: D, dtype: float64
new total cases: 8855.0, old total cases: 8602.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    253.0
Freq: D, dtype: float64
new total cases: 9139.0, old total cases: 8855.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    284.0
Freq: D, dtype: float64
new total cases: 9678.0, old total cases: 9139.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    539.0
Freq: D, dtype: float64
new total cases: 9994.0, old total cases: 9678.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    316.0
Freq: D, dtype: float64
new total cases: 10001.0, old total cases: 9994.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    7.0
Freq: D, dtype: float64
new total cases: 10360.0, old total cases: 10001.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    359.0
Freq: D, dtype: float64
new total cases: 10965.0, old total cases: 10360.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    605.0
Freq: D, dtype: float64
new total cases: 10965.0, old total cases: 10965.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    0.0
Freq: D, dtype: float64
new total cases: 11281.0, old total cases: 10965.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    316.0
Freq: D, dtype: float64
new total cases: 11573.0, old total cases: 11281.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    292.0
Freq: D, dtype: float64
new total cases: 11822.0, old total cases: 11573.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    249.0
Freq: D, dtype: float64
new total cases: 11823.0, old total cases: 11822.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    1.0
Freq: D, dtype: float64
new total cases: 12450.0, old total cases: 11823.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    627.0
Freq: D, dtype: float64
new total cases: 12746.0, old total cases: 12450.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    296.0
Freq: D, dtype: float64
new total cases: 13007.0, old total cases: 12746.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    261.0
Freq: D, dtype: float64
new total cases: 13652.0, old total cases: 13007.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    645.0
Freq: D, dtype: float64
new total cases: 13899.0, old total cases: 13652.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    247.0
Freq: D, dtype: float64
new total cases: 13904.0, old total cases: 13899.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    5.0
Freq: D, dtype: float64
new total cases: 14195.0, old total cases: 13904.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    291.0
Freq: D, dtype: float64
new total cases: 14474.0, old total cases: 14195.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    279.0
Freq: D, dtype: float64
new total cases: 14737.0, old total cases: 14474.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    263.0
Freq: D, dtype: float64
new total cases: 15220.0, old total cases: 14737.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    241.5
2017-08-03    241.5
Freq: D, dtype: float64
new total cases: 16195.0, old total cases: 15220.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    325.0
2017-08-05    325.0
2017-08-06    325.0
Freq: D, dtype: float64
new total cases: 17575.0, old total cases: 16195.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    197.142857
2017-08-08    197.142857
2017-08-09    197.142857
2017-08-10    197.142857
2017-08-11    197.142857
2017-08-12    197.142857
2017-08-13    197.142857
Freq: D, dtype: float64
new total cases: 18055.0, old total cases: 17575.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    240.0
2017-08-15    240.0
Freq: D, dtype: float64
new total cases: 18257.0, old total cases: 18055.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    202.0
Freq: D, dtype: float64
new total cases: 18469.0, old total cases: 18257.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    212.0
Freq: D, dtype: float64
new total cases: 18634.0, old total cases: 18469.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    165.0
Freq: D, dtype: float64
new total cases: 18865.0, old total cases: 18634.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    231.0
Freq: D, dtype: float64
new total cases: 19102.0, old total cases: 18865.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    237.0
Freq: D, dtype: float64
new total cases: 19103.0, old total cases: 19102.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    1.0
Freq: D, dtype: float64
new total cases: 19535.0, old total cases: 19103.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    432.0
Freq: D, dtype: float64
new total cases: 19733.0, old total cases: 19535.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    198.0
Freq: D, dtype: float64
new total cases: 19971.0, old total cases: 19733.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    238.0
Freq: D, dtype: float64
new total cases: 20550.0, old total cases: 19971.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    289.5
2017-08-26    289.5
Freq: D, dtype: float64
new total cases: 20771.0, old total cases: 20550.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    221.0
Freq: D, dtype: float64
new total cases: 20976.0, old total cases: 20771.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    205.0
Freq: D, dtype: float64
new total cases: 21164.0, old total cases: 20976.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    188.0
Freq: D, dtype: float64
new total cases: 21327.0, old total cases: 21164.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    163.0
Freq: D, dtype: float64
new total cases: 21328.0, old total cases: 21327.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    1.0
Freq: D, dtype: float64
new total cases: 21586.0, old total cases: 21328.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    258.0
Freq: D, dtype: float64
new total cases: 21814.0, old total cases: 21586.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    228.0
Freq: D, dtype: float64
new total cases: 22052.0, old total cases: 21814.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    238.0
Freq: D, dtype: float64
new total cases: 22277.0, old total cases: 22052.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    225.0
Freq: D, dtype: float64
new total cases: 22477.0, old total cases: 22277.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    200.0
Freq: D, dtype: float64
new total cases: 22673.0, old total cases: 22477.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    196.0
Freq: D, dtype: float64
new total cases: 22675.0, old total cases: 22673.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    2.0
Freq: D, dtype: float64
new total cases: 23030.0, old total cases: 22675.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    355.0
Freq: D, dtype: float64
new total cases: 23222.0, old total cases: 23030.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    192.0
Freq: D, dtype: float64
new total cases: 23222.0, old total cases: 23222.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    0.0
Freq: D, dtype: float64
new total cases: 23465.0, old total cases: 23222.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    243.0
Freq: D, dtype: float64
new total cases: 23681.0, old total cases: 23465.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    216.0
Freq: D, dtype: float64
new total cases: 23685.0, old total cases: 23681.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    4.0
Freq: D, dtype: float64
new total cases: 24079.0, old total cases: 23685.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    394.0
Freq: D, dtype: float64
new total cases: 24414.0, old total cases: 24079.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    335.0
Freq: D, dtype: float64
new total cases: 24619.0, old total cases: 24414.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    205.0
Freq: D, dtype: float64
new total cases: 24619.0, old total cases: 24619.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    0.0
Freq: D, dtype: float64
new total cases: 24983.0, old total cases: 24619.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    364.0
Freq: D, dtype: float64
new total cases: 25200.0, old total cases: 24983.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    217.0
Freq: D, dtype: float64
new total cases: 25431.0, old total cases: 25200.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    231.0
Freq: D, dtype: float64
new total cases: 25611.0, old total cases: 25431.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    180.0
Freq: D, dtype: float64
new total cases: 25611.0, old total cases: 25611.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    0.0
Freq: D, dtype: float64
new total cases: 25611.0, old total cases: 25611.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    0.0
Freq: D, dtype: float64
new total cases: 25888.0, old total cases: 25611.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    277.0
Freq: D, dtype: float64
new total cases: 26131.0, old total cases: 25888.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    243.0
Freq: D, dtype: float64
new total cases: 26228.0, old total cases: 26131.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    97.0
Freq: D, dtype: float64
new total cases: 26299.0, old total cases: 26228.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    71.0
Freq: D, dtype: float64
new total cases: 26385.0, old total cases: 26299.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    86.0
Freq: D, dtype: float64
new total cases: 26523.0, old total cases: 26385.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    69.0
2017-09-30    69.0
Freq: D, dtype: float64
new total cases: 26622.0, old total cases: 26523.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    99.0
Freq: D, dtype: float64
new total cases: 26622.0, old total cases: 26622.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 26822.0, old total cases: 26622.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    200.0
Freq: D, dtype: float64
new total cases: 26888.0, old total cases: 26822.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    66.0
Freq: D, dtype: float64
new total cases: 26950.0, old total cases: 26888.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    62.0
Freq: D, dtype: float64
new total cases: 27081.0, old total cases: 26950.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    43.666667
2017-10-07    43.666667
2017-10-08    43.666667
Freq: D, dtype: float64
new total cases: 27188.0, old total cases: 27081.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    107.0
Freq: D, dtype: float64
new total cases: 27193.0, old total cases: 27188.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    5.0
Freq: D, dtype: float64
new total cases: 27305.0, old total cases: 27193.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    112.0
Freq: D, dtype: float64
new total cases: 27435.0, old total cases: 27305.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    43.333333
2017-10-13    43.333333
2017-10-14    43.333333
Freq: D, dtype: float64
new total cases: 27469.0, old total cases: 27435.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    17.0
2017-10-16    17.0
Freq: D, dtype: float64
new total cases: 27525.0, old total cases: 27469.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    56.0
Freq: D, dtype: float64
new total cases: 27652.0, old total cases: 27525.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    31.75
2017-10-19    31.75
2017-10-20    31.75
2017-10-21    31.75
Freq: D, dtype: float64
new total cases: 27675.0, old total cases: 27652.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    23.0
Freq: D, dtype: float64
new total cases: 27724.0, old total cases: 27675.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    16.333333
2017-10-24    16.333333
2017-10-25    16.333333
Freq: D, dtype: float64
new total cases: 27781.0, old total cases: 27724.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    19.0
2017-10-27    19.0
2017-10-28    19.0
Freq: D, dtype: float64
new total cases: 27783.0, old total cases: 27781.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    2.0
Freq: D, dtype: float64
new total cases: 27804.0, old total cases: 27783.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    21.0
Freq: D, dtype: float64
new total cases: 27896.0, old total cases: 27804.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    23.0
2017-11-01    23.0
2017-11-02    23.0
2017-11-03    23.0
Freq: D, dtype: float64
new total cases: 27911.0, old total cases: 27896.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    15.0
Freq: D, dtype: float64
new total cases: 27911.0, old total cases: 27911.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    0.0
Freq: D, dtype: float64
new total cases: 27936.0, old total cases: 27911.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    25.0
Freq: D, dtype: float64
new total cases: 27941.0, old total cases: 27936.0

2017-06-18    215.0
Freq: D, dtype: float64
new total cases: 5053.0, old total cases: 4699.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    354.0
Freq: D, dtype: float64
new total cases: 5272.0, old total cases: 5053.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    219.0
Freq: D, dtype: float64
new total cases: 5470.0, old total cases: 5272.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    198.0
Freq: D, dtype: float64
new total cases: 5634.0, old total cases: 5470.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    164.0
Freq: D, dtype: float64
new total cases: 5799.0, old total cases: 5634.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    165.0
Freq: D, dtype: float64
new total cases: 6048.0, old total cases: 5799.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    249.0
Freq: D, dtype: float64
new total cases: 6205.0, old total cases: 6048.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    157.0
Freq: D, dtype: float64
new total cases: 6469.0, old total cases: 6205.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    264.0
Freq: D, dtype: float64
new total cases: 6757.0, old total cases: 6469.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    288.0
Freq: D, dtype: float64
new total cases: 7007.0, old total cases: 6757.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    250.0
Freq: D, dtype: float64
new total cases: 7315.0, old total cases: 7007.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    308.0
Freq: D, dtype: float64
new total cases: 7507.0, old total cases: 7315.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    192.0
Freq: D, dtype: float64
new total cases: 7775.0, old total cases: 7507.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    268.0
Freq: D, dtype: float64
new total cases: 7939.0, old total cases: 7775.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    164.0
Freq: D, dtype: float64
new total cases: 8100.0, old total cases: 7939.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    161.0
Freq: D, dtype: float64
new total cases: 8349.0, old total cases: 8100.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    249.0
Freq: D, dtype: float64
new total cases: 8519.0, old total cases: 8349.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    170.0
Freq: D, dtype: float64
new total cases: 8519.0, old total cases: 8519.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    0.0
Freq: D, dtype: float64
new total cases: 8948.0, old total cases: 8519.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    429.0
Freq: D, dtype: float64
new total cases: 9618.0, old total cases: 8948.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    223.333333
2017-07-09    223.333333
2017-07-10    223.333333
Freq: D, dtype: float64
new total cases: 9810.0, old total cases: 9618.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    192.0
Freq: D, dtype: float64
new total cases: 10009.0, old total cases: 9810.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    199.0
Freq: D, dtype: float64
new total cases: 10209.0, old total cases: 10009.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    200.0
Freq: D, dtype: float64
new total cases: 10347.0, old total cases: 10209.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    138.0
Freq: D, dtype: float64
new total cases: 10518.0, old total cases: 10347.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    171.0
Freq: D, dtype: float64
new total cases: 10665.0, old total cases: 10518.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    147.0
Freq: D, dtype: float64
new total cases: 10809.0, old total cases: 10665.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    144.0
Freq: D, dtype: float64
new total cases: 10997.0, old total cases: 10809.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    188.0
Freq: D, dtype: float64
new total cases: 10997.0, old total cases: 10997.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    0.0
Freq: D, dtype: float64
new total cases: 11431.0, old total cases: 10997.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    434.0
Freq: D, dtype: float64
new total cases: 11614.0, old total cases: 11431.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    183.0
Freq: D, dtype: float64
new total cases: 11812.0, old total cases: 11614.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    198.0
Freq: D, dtype: float64
new total cases: 11987.0, old total cases: 11812.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    175.0
Freq: D, dtype: float64
new total cases: 12154.0, old total cases: 11987.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    167.0
Freq: D, dtype: float64
new total cases: 12343.0, old total cases: 12154.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    189.0
Freq: D, dtype: float64
new total cases: 12501.0, old total cases: 12343.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    158.0
Freq: D, dtype: float64
new total cases: 12603.0, old total cases: 12501.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    102.0
Freq: D, dtype: float64
new total cases: 12603.0, old total cases: 12603.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    0.0
Freq: D, dtype: float64
new total cases: 12818.0, old total cases: 12603.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    215.0
Freq: D, dtype: float64
new total cases: 12932.0, old total cases: 12818.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    114.0
Freq: D, dtype: float64
new total cases: 13022.0, old total cases: 12932.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    90.0
Freq: D, dtype: float64
new total cases: 13115.0, old total cases: 13022.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    93.0
Freq: D, dtype: float64
new total cases: 13239.0, old total cases: 13115.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    62.0
2017-08-03    62.0
Freq: D, dtype: float64
new total cases: 13554.0, old total cases: 13239.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    105.0
2017-08-05    105.0
2017-08-06    105.0
Freq: D, dtype: float64
new total cases: 14040.0, old total cases: 13554.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    69.428571
2017-08-08    69.428571
2017-08-09    69.428571
2017-08-10    69.428571
2017-08-11    69.428571
2017-08-12    69.428571
2017-08-13    69.428571
Freq: D, dtype: float64
new total cases: 14234.0, old total cases: 14040.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    97.0
2017-08-15    97.0
Freq: D, dtype: float64
new total cases: 14330.0, old total cases: 14234.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    96.0
Freq: D, dtype: float64
new total cases: 14414.0, old total cases: 14330.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    84.0
Freq: D, dtype: float64
new total cases: 14479.0, old total cases: 14414.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    65.0
Freq: D, dtype: float64
new total cases: 14555.0, old total cases: 14479.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    76.0
Freq: D, dtype: float64
new total cases: 14666.0, old total cases: 14555.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    111.0
Freq: D, dtype: float64
new total cases: 14779.0, old total cases: 14666.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    113.0
Freq: D, dtype: float64
new total cases: 14905.0, old total cases: 14779.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    126.0
Freq: D, dtype: float64
new total cases: 15020.0, old total cases: 14905.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    115.0
Freq: D, dtype: float64
new total cases: 15130.0, old total cases: 15020.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    110.0
Freq: D, dtype: float64
new total cases: 15239.0, old total cases: 15130.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    54.5
2017-08-26    54.5
Freq: D, dtype: float64
new total cases: 15513.0, old total cases: 15239.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    274.0
Freq: D, dtype: float64
new total cases: 15608.0, old total cases: 15513.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    95.0
Freq: D, dtype: float64
new total cases: 15704.0, old total cases: 15608.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    96.0
Freq: D, dtype: float64
new total cases: 15802.0, old total cases: 15704.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    98.0
Freq: D, dtype: float64
new total cases: 15883.0, old total cases: 15802.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    81.0
Freq: D, dtype: float64
new total cases: 15955.0, old total cases: 15883.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    72.0
Freq: D, dtype: float64
new total cases: 16021.0, old total cases: 15955.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    66.0
Freq: D, dtype: float64
new total cases: 16119.0, old total cases: 16021.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    98.0
Freq: D, dtype: float64
new total cases: 16200.0, old total cases: 16119.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    81.0
Freq: D, dtype: float64
new total cases: 16282.0, old total cases: 16200.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    82.0
Freq: D, dtype: float64
new total cases: 16341.0, old total cases: 16282.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    59.0
Freq: D, dtype: float64
new total cases: 16435.0, old total cases: 16341.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    94.0
Freq: D, dtype: float64
new total cases: 16522.0, old total cases: 16435.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    87.0
Freq: D, dtype: float64
new total cases: 16522.0, old total cases: 16522.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    0.0
Freq: D, dtype: float64
new total cases: 16606.0, old total cases: 16522.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    84.0
Freq: D, dtype: float64
new total cases: 16742.0, old total cases: 16606.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    136.0
Freq: D, dtype: float64
new total cases: 16822.0, old total cases: 16742.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    80.0
Freq: D, dtype: float64
new total cases: 16917.0, old total cases: 16822.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    95.0
Freq: D, dtype: float64
new total cases: 16980.0, old total cases: 16917.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    63.0
Freq: D, dtype: float64
new total cases: 17050.0, old total cases: 16980.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    70.0
Freq: D, dtype: float64
new total cases: 17134.0, old total cases: 17050.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    84.0
Freq: D, dtype: float64
new total cases: 17242.0, old total cases: 17134.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    108.0
Freq: D, dtype: float64
new total cases: 17242.0, old total cases: 17242.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    0.0
Freq: D, dtype: float64
new total cases: 17387.0, old total cases: 17242.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    145.0
Freq: D, dtype: float64
new total cases: 17442.0, old total cases: 17387.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    55.0
Freq: D, dtype: float64
new total cases: 17516.0, old total cases: 17442.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    74.0
Freq: D, dtype: float64
new total cases: 17585.0, old total cases: 17516.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    69.0
Freq: D, dtype: float64
new total cases: 17646.0, old total cases: 17585.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    61.0
Freq: D, dtype: float64
new total cases: 17709.0, old total cases: 17646.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    63.0
Freq: D, dtype: float64
new total cases: 17760.0, old total cases: 17709.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    51.0
Freq: D, dtype: float64
new total cases: 17829.0, old total cases: 17760.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    69.0
Freq: D, dtype: float64
new total cases: 17893.0, old total cases: 17829.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    64.0
Freq: D, dtype: float64
new total cases: 17893.0, old total cases: 17893.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    0.0
Freq: D, dtype: float64
new total cases: 18026.0, old total cases: 17893.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    66.5
2017-09-30    66.5
Freq: D, dtype: float64
new total cases: 18098.0, old total cases: 18026.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    72.0
Freq: D, dtype: float64
new total cases: 18098.0, old total cases: 18098.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 18215.0, old total cases: 18098.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    117.0
Freq: D, dtype: float64
new total cases: 18265.0, old total cases: 18215.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    50.0
Freq: D, dtype: float64
new total cases: 18314.0, old total cases: 18265.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    49.0
Freq: D, dtype: float64
new total cases: 18420.0, old total cases: 18314.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    35.333333
2017-10-07    35.333333
2017-10-08    35.333333
Freq: D, dtype: float64
new total cases: 18528.0, old total cases: 18420.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    108.0
Freq: D, dtype: float64
new total cases: 18590.0, old total cases: 18528.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    62.0
Freq: D, dtype: float64
new total cases: 18634.0, old total cases: 18590.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    44.0
Freq: D, dtype: float64
new total cases: 18774.0, old total cases: 18634.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    46.666667
2017-10-13    46.666667
2017-10-14    46.666667
Freq: D, dtype: float64
new total cases: 18844.0, old total cases: 18774.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    35.0
2017-10-16    35.0
Freq: D, dtype: float64
new total cases: 18887.0, old total cases: 18844.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    43.0
Freq: D, dtype: float64
new total cases: 19102.0, old total cases: 18887.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    53.75
2017-10-19    53.75
2017-10-20    53.75
2017-10-21    53.75
Freq: D, dtype: float64
new total cases: 19132.0, old total cases: 19102.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    30.0
Freq: D, dtype: float64
new total cases: 19209.0, old total cases: 19132.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    25.666667
2017-10-24    25.666667
2017-10-25    25.666667
Freq: D, dtype: float64
new total cases: 19309.0, old total cases: 19209.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    33.333333
2017-10-27    33.333333
2017-10-28    33.333333
Freq: D, dtype: float64
new total cases: 19347.0, old total cases: 19309.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    38.0
Freq: D, dtype: float64
new total cases: 19397.0, old total cases: 19347.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    50.0
Freq: D, dtype: float64
new total cases: 19616.0, old total cases: 19397.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    54.75
2017-11-01    54.75
2017-11-02    54.75
2017-11-03    54.75
Freq: D, dtype: float64
new total cases: 19674.0, old total cases: 19616.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    58.0
Freq: D, dtype: float64
new total cases: 19711.0, old total cases: 19674.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    37.0
Freq: D, dtype: float64
new total cases: 19757.0, old total cases: 19711.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    46.0
Freq: D, dtype: float64
new total cases: 19786.0, old total cases: 19757.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    29.0
Freq: D, dtype: float64
new total cases: 19816.0, old total cases: 19786.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    30.0
Freq: D, dtype: float64
new total cases: 20171.0, old total cases: 19816.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    32.272727
2017-11-10    32.272727
2017-11-11    32.272727
2017-11-12    32.272727
2017-11-13    32.272727
2017-11-14    32.272727
2017-11-15    32.272727
2017-11-16    32.272727
2017-11-17    32.272727
2017-11-18    32.272727
2017-11-19    32.272727
Freq: D, dtype: float64
new total cases: 20286.0, old total cases: 20171.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    16.428571
2017-11-21    16.428571
2017-11-22    16.428571
2017-11-23    16.428571
2017-11-24    16.428571
2017-11-25    16.428571
2017-11-26    16.428571
Freq: D, dtype: float64
new total cases: 20566.0, old total cases: 20286.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    13.333333
2017-11-28    13.333333
2017-11-29    13.333333
2017-11-30    13.333333
2017-12-01    13.333333
2017-12-02    13.333333
2017-12-03    13.333333
2017-12-04    13.333333
2017-12-05    13.333333
2017-12-06    13.333333
2017-12-07    13.333333
2017-12-08    13.333333
2017-12-09    13.333333
2017-12-10    13.333333
2017-12-11    13.333333
2017-12-12    13.333333
2017-12-13    13.333333
2017-12-14    13.333333
2017-12-15    13.333333
2017-12-16    13.333333
2017-12-17    13.333333
Freq: D, dtype: float64
new total cases: 20819.0, old total cases: 20566.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    18.071429
2017-12-19    18.071429
2017-12-20    18.071429
2017-12-21    18.071429
2017-12-22    18.071429
2017-12-23    18.071429

2017-09-17    0.0
Freq: D, dtype: float64
new total cases: 21283.0, old total cases: 20965.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    318.0
Freq: D, dtype: float64
new total cases: 21429.0, old total cases: 21283.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    146.0
Freq: D, dtype: float64
new total cases: 21652.0, old total cases: 21429.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    223.0
Freq: D, dtype: float64
new total cases: 21797.0, old total cases: 21652.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    145.0
Freq: D, dtype: float64
new total cases: 21953.0, old total cases: 21797.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    156.0
Freq: D, dtype: float64
new total cases: 22176.0, old total cases: 21953.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    223.0
Freq: D, dtype: float64
new total cases: 22303.0, old total cases: 22176.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    127.0
Freq: D, dtype: float64
new total cases: 22449.0, old total cases: 22303.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    146.0
Freq: D, dtype: float64
new total cases: 22648.0, old total cases: 22449.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    199.0
Freq: D, dtype: float64
new total cases: 22804.0, old total cases: 22648.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    156.0
Freq: D, dtype: float64
new total cases: 22926.0, old total cases: 22804.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    122.0
Freq: D, dtype: float64
new total cases: 23183.0, old total cases: 22926.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    128.5
2017-09-30    128.5
Freq: D, dtype: float64
new total cases: 23324.0, old total cases: 23183.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    141.0
Freq: D, dtype: float64
new total cases: 23324.0, old total cases: 23324.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 23526.0, old total cases: 23324.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    202.0
Freq: D, dtype: float64
new total cases: 23624.0, old total cases: 23526.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    98.0
Freq: D, dtype: float64
new total cases: 23719.0, old total cases: 23624.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    95.0
Freq: D, dtype: float64
new total cases: 23827.0, old total cases: 23719.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    36.0
2017-10-07    36.0
2017-10-08    36.0
Freq: D, dtype: float64
new total cases: 24012.0, old total cases: 23827.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    185.0
Freq: D, dtype: float64
new total cases: 24012.0, old total cases: 24012.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    0.0
Freq: D, dtype: float64
new total cases: 24154.0, old total cases: 24012.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    142.0
Freq: D, dtype: float64
new total cases: 24323.0, old total cases: 24154.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    56.333333
2017-10-13    56.333333
2017-10-14    56.333333
Freq: D, dtype: float64
new total cases: 24434.0, old total cases: 24323.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    55.5
2017-10-16    55.5
Freq: D, dtype: float64
new total cases: 24435.0, old total cases: 24434.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    1.0
Freq: D, dtype: float64
new total cases: 24845.0, old total cases: 24435.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    102.5
2017-10-19    102.5
2017-10-20    102.5
2017-10-21    102.5
Freq: D, dtype: float64
new total cases: 24894.0, old total cases: 24845.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    49.0
Freq: D, dtype: float64
new total cases: 25110.0, old total cases: 24894.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    72.0
2017-10-24    72.0
2017-10-25    72.0
Freq: D, dtype: float64
new total cases: 25270.0, old total cases: 25110.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    53.333333
2017-10-27    53.333333
2017-10-28    53.333333
Freq: D, dtype: float64
new total cases: 25351.0, old total cases: 25270.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    81.0
Freq: D, dtype: float64
new total cases: 25369.0, old total cases: 25351.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    18.0
Freq: D, dtype: float64
new total cases: 25651.0, old total cases: 25369.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    70.5
2017-11-01    70.5
2017-11-02    70.5
2017-11-03    70.5
Freq: D, dtype: float64
new total cases: 25711.0, old total cases: 25651.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    60.0
Freq: D, dtype: float64
new total cases: 25771.0, old total cases: 25711.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    60.0
Freq: D, dtype: float64
new total cases: 25814.0, old total cases: 25771.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    43.0
Freq: D, dtype: float64
new total cases: 25856.0, old total cases: 25814.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    42.0
Freq: D, dtype: float64
new total cases: 25905.0, old total cases: 25856.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    49.0
Freq: D, dtype: float64
new total cases: 26532.0, old total cases: 25905.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    57.0
2017-11-10    57.0
2017-11-11    57.0
2017-11-12    57.0
2017-11-13    57.0
2017-11-14    57.0
2017-11-15    57.0
2017-11-16    57.0
2017-11-17    57.0
2017-11-18    57.0
2017-11-19    57.0
Freq: D, dtype: float64
new total cases: 26793.0, old total cases: 26532.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    37.285714
2017-11-21    37.285714
2017-11-22    37.285714
2017-11-23    37.285714
2017-11-24    37.285714
2017-11-25    37.285714
2017-11-26    37.285714
Freq: D, dtype: float64
new total cases: 27550.0, old total cases: 26793.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    36.047619
2017-11-28    36.047619
2017-11-29    36.047619
2017-11-30    36.047619
2017-12-01    36.047619
2017-12-02    36.047619
2017-12-03    36.047619
2017-12-04    36.047619
2017-12-05    36.047619
2017-12-06    36.047619
2017-12-07    36.047619
2017-12-08    36.047619
2017-12-09    36.047619
2017-12-10    36.047619
2017-12-11    36.047619
2017-12-12    36.047619
2017-12-13    36.047619
2017-12-14    36.047619
2017-12-15    36.047619
2017-12-16    36.047619
2017-12-17    36.047619
Freq: D, dtype: float64
new total cases: 27990.0, old total cases: 27550.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    31.428571
2017-12-19    31.428571
2017-12-20    31.428571
2017-12-21    31.428571
2017-12-22    31.428571
2017-12-23    31.428571
2017-12-24    31.428571
2017-12-25    31.428571
2017-12-26    31.428571
2017-12-27    31.428571
2017-12-28    31.428571
2017-12-29    31.428571
2017-12-30    31.428571
2017-12-31    31.428571
Freq: D, dtype: float64
new total cases: 28452.0, old total cases: 27990.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    66.0
2018-01-02    66.0
2018-01-03    66.0
2018-01-04    66.0
2018-01-05    66.0
2018-01-06    66.0
2018-01-07    66.0
Freq: D, dtype: float64
new total cases: 28730.0, old total cases: 28452.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    39.714286
2018-01-09    39.714286
2018-01-10    39.714286
2018-01-11    39.714286
2018-01-12    39.714286
2018-01-13    39.714286
2018-01-14    39.714286
Freq: D, dtype: float64
new total cases: 29269.0, old total cases: 28730.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    77.0
2018-01-16    77.0
2018-01-17    77.0
2018-01-18    77.0
2018-01-19    77.0
2018-01-20    77.0
2018-01-21    77.0
Freq: D, dtype: float64
new total cases: 29718.0, old total cases: 29269.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    64.142857
2018-01-23    64.142857
2018-01-24    64.142857
2018-01-25    64.142857
2018-01-26    64.142857
2018-01-27    64.142857
2018-01-28    64.142857
Freq: D, dtype: float64
new total cases: 29980.0, old total cases: 29718.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    37.428571
2018-01-30    37.428571
2018-01-31    37.428571
2018-02-01    37.428571
2018-02-02    37.428571
2018-02-03    37.428571
2018-02-04    37.428571
Freq: D, dtype: float64
new total cases: 30265.0, old total cases: 29980.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    40.714286
2018-02-06    40.714286
2018-02-07    40.714286
2018-02-08    40.714286
2018-02-09    40.714286
2018-02-10    40.714286
2018-02-11    40.714286
Freq: D, dtype: float64
new total cases: 30568.0, old total cases: 30265.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    43.285714
2018-02-13    43.285714
2018-02-14    43.285714
2018-02-15    43.285714
2018-02-16    43.285714
2018-02-17    43.285714
2018-02-18    43.285714
Freq: D, dtype: float64
new total cases: 1919.0, old total cases: 1401.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    103.6
2017-05-24    103.6
2017-05-25    103.6
2017-05-26    103.6
2017-05-27    103.6
Freq: D, dtype: float64
new total cases: 2371.0, old total cases: 1919.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    150.666667
2017-05-29    150.666667
2017-05-30    150.666667
Freq: D, dtype: float64
new total cases: 2802.0, old total cases: 2371.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    86.2
2017-06-01    86.2
2017-06-02    86.2
2017-06-03    86.2
2017-06-04    86.2
Freq: D, dtype: float64
new total cases: 3428.0, old total cases: 2802.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    208.666667
2017-06-06    208.666667
2017-06-07    208.666667
Freq: D, dtype: float64
new total cases: 4700.0, old total cases: 3428.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    424.0
2017-06-09    424.0
2017-06-10    424.0
Freq: D, dtype: float64
new total cases: 4857.0, old total cases: 4700.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    78.5
2017-06-12    78.5
Freq: D, dtype: float64
new total cases: 5030.0, old total cases: 4857.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    173.0
Freq: D, dtype: float64
new total cases: 5107.0, old total cases: 5030.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    77.0
Freq: D, dtype: float64
new total cases: 5999.0, old total cases: 5107.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    297.333333
2017-06-16    297.333333
2017-06-17    297.333333
Freq: D, dtype: float64
new total cases: 6802.0, old total cases: 5999.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    803.0
Freq: D, dtype: float64
new total cases: 7041.0, old total cases: 6802.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    239.0
Freq: D, dtype: float64
new total cases: 7201.0, old total cases: 7041.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    160.0
Freq: D, dtype: float64
new total cases: 7582.0, old total cases: 7201.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    381.0
Freq: D, dtype: float64
new total cases: 7593.0, old total cases: 7582.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    11.0
Freq: D, dtype: float64
new total cases: 8445.0, old total cases: 7593.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    852.0
Freq: D, dtype: float64
new total cases: 8896.0, old total cases: 8445.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    451.0
Freq: D, dtype: float64
new total cases: 9171.0, old total cases: 8896.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    275.0
Freq: D, dtype: float64
new total cases: 9746.0, old total cases: 9171.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    575.0
Freq: D, dtype: float64
new total cases: 10183.0, old total cases: 9746.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    437.0
Freq: D, dtype: float64
new total cases: 10610.0, old total cases: 10183.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    427.0
Freq: D, dtype: float64
new total cases: 11192.0, old total cases: 10610.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    582.0
Freq: D, dtype: float64
new total cases: 11195.0, old total cases: 11192.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    3.0
Freq: D, dtype: float64
new total cases: 11196.0, old total cases: 11195.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    1.0
Freq: D, dtype: float64
new total cases: 12360.0, old total cases: 11196.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    1164.0
Freq: D, dtype: float64
new total cases: 12371.0, old total cases: 12360.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    11.0
Freq: D, dtype: float64
new total cases: 12375.0, old total cases: 12371.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    4.0
Freq: D, dtype: float64
new total cases: 13573.0, old total cases: 12375.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    1198.0
Freq: D, dtype: float64
new total cases: 14628.0, old total cases: 13573.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    1055.0
Freq: D, dtype: float64
new total cases: 15166.0, old total cases: 14628.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    538.0
Freq: D, dtype: float64
new total cases: 16624.0, old total cases: 15166.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    486.0
2017-07-09    486.0
2017-07-10    486.0
Freq: D, dtype: float64
new total cases: 17622.0, old total cases: 16624.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    998.0
Freq: D, dtype: float64
new total cases: 18047.0, old total cases: 17622.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    425.0
Freq: D, dtype: float64
new total cases: 18050.0, old total cases: 18047.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    3.0
Freq: D, dtype: float64
new total cases: 18419.0, old total cases: 18050.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    369.0
Freq: D, dtype: float64
new total cases: 18902.0, old total cases: 18419.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    483.0
Freq: D, dtype: float64
new total cases: 19659.0, old total cases: 18902.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    757.0
Freq: D, dtype: float64
new total cases: 19659.0, old total cases: 19659.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    0.0
Freq: D, dtype: float64
new total cases: 20054.0, old total cases: 19659.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    395.0
Freq: D, dtype: float64
new total cases: 20504.0, old total cases: 20054.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    450.0
Freq: D, dtype: float64
new total cases: 20941.0, old total cases: 20504.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    437.0
Freq: D, dtype: float64
new total cases: 21342.0, old total cases: 20941.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    401.0
Freq: D, dtype: float64
new total cases: 21628.0, old total cases: 21342.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    286.0
Freq: D, dtype: float64
new total cases: 21935.0, old total cases: 21628.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    307.0
Freq: D, dtype: float64
new total cases: 22240.0, old total cases: 21935.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    305.0
Freq: D, dtype: float64
new total cases: 22539.0, old total cases: 22240.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    299.0
Freq: D, dtype: float64
new total cases: 22867.0, old total cases: 22539.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    328.0
Freq: D, dtype: float64
new total cases: 23347.0, old total cases: 22867.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    480.0
Freq: D, dtype: float64
new total cases: 23746.0, old total cases: 23347.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    399.0
Freq: D, dtype: float64
new total cases: 23746.0, old total cases: 23746.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    0.0
Freq: D, dtype: float64
new total cases: 24485.0, old total cases: 23746.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    739.0
Freq: D, dtype: float64
new total cases: 24849.0, old total cases: 24485.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    364.0
Freq: D, dtype: float64
new total cases: 25220.0, old total cases: 24849.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    371.0
Freq: D, dtype: float64
new total cases: 25581.0, old total cases: 25220.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    180.5
2017-08-03    180.5
Freq: D, dtype: float64
new total cases: 27294.0, old total cases: 25581.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    571.0
2017-08-05    571.0
2017-08-06    571.0
Freq: D, dtype: float64
new total cases: 29063.0, old total cases: 27294.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    252.714286
2017-08-08    252.714286
2017-08-09    252.714286
2017-08-10    252.714286
2017-08-11    252.714286
2017-08-12    252.714286
2017-08-13    252.714286
Freq: D, dtype: float64
new total cases: 29755.0, old total cases: 29063.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    346.0
2017-08-15    346.0
Freq: D, dtype: float64
new total cases: 29755.0, old total cases: 29755.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    0.0
Freq: D, dtype: float64
new total cases: 29755.0, old total cases: 29755.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    0.0
Freq: D, dtype: float64
new total cases: 30783.0, old total cases: 29755.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    1028.0
Freq: D, dtype: float64
new total cases: 31038.0, old total cases: 30783.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    255.0
Freq: D, dtype: float64
new total cases: 31368.0, old total cases: 31038.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    330.0
Freq: D, dtype: float64
new total cases: 31725.0, old total cases: 31368.0

Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15   NaN
2017-06-16   NaN
2017-06-17   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29   NaN
Freq: D, dtype: float64
new total cases: 2.0, old total cases: nan
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30   NaN
Freq: D, dtype: float64
new total cases: 2.0, old total cases: 2.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    0.0
Freq: D, dtype: float64
new total cases: 2.0, old total cases: 2.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    0.0
Freq: D, dtype: float64
new total cases: 2.0, old total cases: 2.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    0.0
Freq: D, dtype: float64
new total cases: 2.0, old total cases: 2.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    0.0
Freq: D, dtype: float64
new total cases: 2.0, old total cases: 2.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    0.0
Freq: D, dtype: float64
new total cases: 2.0, old total cases: 2.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    0.0
Freq: D, dtype: float64
new total cases: 2.0, old total cases: 2.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    0.0
Freq: D, dtype: float64
new total cases: nan, old total cases: 2.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08   NaN
2017-07-09   NaN
2017-07-10   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30   NaN
Freq: D, dtype: float64
new total cases: 21.0, old total cases: nan
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31   NaN
Freq: D, dtype: float64
new total cases: 42.0, old total cases: 21.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    21.0
Freq: D, dtype: float64
new total cases: 58.0, old total cases: 42.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    8.0
2017-08-03    8.0
Freq: D, dtype: float64
new total cases: 83.0, old total cases: 58.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    8.333333
2017-08-05    8.333333
2017-08-06    8.333333
Freq: D, dtype: float64
new total cases: 115.0, old total cases: 83.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    4.571429
2017-08-08    4.571429
2017-08-09    4.571429
2017-08-10    4.571429
2017-08-11    4.571429
2017-08-12    4.571429
2017-08-13    4.571429
Freq: D, dtype: float64
new total cases: 127.0, old total cases: 115.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    6.0
2017-08-15    6.0
Freq: D, dtype: float64
new total cases: 133.0, old total cases: 127.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    6.0
Freq: D, dtype: float64
new total cases: 133.0, old total cases: 133.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    0.0
Freq: D, dtype: float64
new total cases: 133.0, old total cases: 133.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 133.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    12.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    0.0
Freq: D, dtype: float64
new total cases: 157.0, old total cases: 145.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    12.0
Freq: D, dtype: float64
new total cases: 157.0, old total cases: 157.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    0.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 157.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    13.0
Freq: D, dtype: float64
new total cases: 172.0, old total cases: 170.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    1.0
2017-08-26    1.0
Freq: D, dtype: float64
new total cases: 180.0, old total cases: 172.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    8.0
Freq: D, dtype: float64
new total cases: 190.0, old total cases: 180.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    10.0
Freq: D, dtype: float64
new total cases: 196.0, old total cases: 190.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    6.0
Freq: D, dtype: float64
new total cases: 199.0, old total cases: 196.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    3.0
Freq: D, dtype: float64
new total cases: 211.0, old total cases: 199.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    12.0
Freq: D, dtype: float64
new total cases: 217.0, old total cases: 211.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    6.0
Freq: D, dtype: float64
new total cases: 221.0, old total cases: 217.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    4.0
Freq: D, dtype: float64
new total cases: 228.0, old total cases: 221.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    7.0
Freq: D, dtype: float64
new total cases: 245.0, old total cases: 228.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    17.0
Freq: D, dtype: float64
new total cases: 268.0, old total cases: 245.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    23.0
Freq: D, dtype: float64
new total cases: 272.0, old total cases: 268.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    4.0
Freq: D, dtype: float64
new total cases: 276.0, old total cases: 272.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    4.0
Freq: D, dtype: float64
new total cases: 304.0, old total cases: 276.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    28.0
Freq: D, dtype: float64
new total cases: 304.0, old total cases: 304.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    0.0
Freq: D, dtype: float64
new total cases: 311.0, old total cases: 304.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    7.0
Freq: D, dtype: float64
new total cases: 313.0, old total cases: 311.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    2.0
Freq: D, dtype: float64
new total cases: 313.0, old total cases: 313.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    0.0
Freq: D, dtype: float64
new total cases: 338.0, old total cases: 313.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    25.0
Freq: D, dtype: float64
new total cases: 355.0, old total cases: 338.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    17.0
Freq: D, dtype: float64
new total cases: 364.0, old total cases: 355.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    9.0
Freq: D, dtype: float64
new total cases: 382.0, old total cases: 364.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    18.0
Freq: D, dtype: float64
new total cases: 403.0, old total cases: 382.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    21.0
Freq: D, dtype: float64
new total cases: 413.0, old total cases: 403.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    10.0
Freq: D, dtype: float64
new total cases: 424.0, old total cases: 413.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    11.0
Freq: D, dtype: float64
new total cases: 444.0, old total cases: 424.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    20.0
Freq: D, dtype: float64
new total cases: 454.0, old total cases: 444.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    10.0
Freq: D, dtype: float64
new total cases: 456.0, old total cases: 454.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    2.0
Freq: D, dtype: float64
new total cases: 465.0, old total cases: 456.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    9.0
Freq: D, dtype: float64
new total cases: 469.0, old total cases: 465.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    4.0
Freq: D, dtype: float64
new total cases: 469.0, old total cases: 469.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    0.0
Freq: D, dtype: float64
new total cases: 481.0, old total cases: 469.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    12.0
Freq: D, dtype: float64
new total cases: 495.0, old total cases: 481.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    14.0
Freq: D, dtype: float64
new total cases: 495.0, old total cases: 495.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    0.0
Freq: D, dtype: float64
new total cases: 514.0, old total cases: 495.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    9.5
2017-09-30    9.5
Freq: D, dtype: float64
new total cases: 519.0, old total cases: 514.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    5.0
Freq: D, dtype: float64
new total cases: 519.0, old total cases: 519.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 527.0, old total cases: 519.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    8.0
Freq: D, dtype: float64
new total cases: 527.0, old total cases: 527.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    0.0
Freq: D, dtype: float64
new total cases: 532.0, old total cases: 527.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    5.0
Freq: D, dtype: float64
new total cases: 537.0, old total cases: 532.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    1.666667
2017-10-07    1.666667
2017-10-08    1.666667
Freq: D, dtype: float64
new total cases: 547.0, old total cases: 537.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    10.0
Freq: D, dtype: float64
new total cases: 545.0, old total cases: 547.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10   -2.0
Freq: D, dtype: float64
new total cases: 549.0, old total cases: 545.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    4.0
Freq: D, dtype: float64
new total cases: 559.0, old total cases: 549.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    3.333333
2017-10-13    3.333333
2017-10-14    3.333333
Freq: D, dtype: float64
new total cases: 561.0, old total cases: 559.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    1.0
2017-10-16    1.0
Freq: D, dtype: float64
new total cases: 563.0, old total cases: 561.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    2.0
Freq: D, dtype: float64
new total cases: 565.0, old total cases: 563.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    0.5
2017-10-19    0.5
2017-10-20    0.5
2017-10-21    0.5
Freq: D, dtype: float64
new total cases: 565.0, old total cases: 565.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 565.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    1.0
2017-10-24    1.0
2017-10-25    1.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    0.0
2017-10-27    0.0
2017-10-28    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    0.0
2017-11-01    0.0
2017-11-02    0.0
2017-11-03    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    0.0
2017-11-10    0.0
2017-11-11    0.0
2017-11-12    0.0
2017-11-13    0.0
2017-11-14    0.0
2017-11-15    0.0
2017-11-16    0.0
2017-11-17    0.0
2017-11-18    0.0
2017-11-19    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    0.0
2017-11-21    0.0
2017-11-22    0.0
2017-11-23    0.0
2017-11-24    0.0
2017-11-25    0.0
2017-11-26    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    0.0
2017-11-28    0.0
2017-11-29    0.0
2017-11-30    0.0
2017-12-01    0.0
2017-12-02    0.0
2017-12-03    0.0
2017-12-04    0.0
2017-12-05    0.0
2017-12-06    0.0
2017-12-07    0.0
2017-12-08    0.0
2017-12-09    0.0
2017-12-10    0.0
2017-12-11    0.0
2017-12-12    0.0
2017-12-13    0.0
2017-12-14    0.0
2017-12-15    0.0
2017-12-16    0.0
2017-12-17    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    0.0
2017-12-19    0.0
2017-12-20    0.0
2017-12-21    0.0
2017-12-22    0.0
2017-12-23    0.0
2017-12-24    0.0
2017-12-25    0.0
2017-12-26    0.0
2017-12-27    0.0
2017-12-28    0.0
2017-12-29    0.0
2017-12-30    0.0
2017-12-31    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    0.0
2018-01-02    0.0
2018-01-03    0.0
2018-01-04    0.0
2018-01-05    0.0
2018-01-06    0.0
2018-01-07    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    0.0
2018-01-09    0.0
2018-01-10    0.0
2018-01-11    0.0
2018-01-12    0.0
2018-01-13    0.0
2018-01-14    0.0
Freq: D, dtype: float64
new total cases: 568.0, old total cases: 568.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    0.0

new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    678.0
Freq: D, dtype: float64
new total cases: 77286.0, old total cases: 76528.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    758.0
Freq: D, dtype: float64
new total cases: 78091.0, old total cases: 77286.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    805.0
Freq: D, dtype: float64
new total cases: 78706.0, old total cases: 78091.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    615.0
Freq: D, dtype: float64
new total cases: 79360.0, old total cases: 78706.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    654.0
Freq: D, dtype: float64
new total cases: 80232.0, old total cases: 79360.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    872.0
Freq: D, dtype: float64
new total cases: 81187.0, old total cases: 80232.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    955.0
Freq: D, dtype: float64
new total cases: 82301.0, old total cases: 81187.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    1114.0
Freq: D, dtype: float64
new total cases: 83472.0, old total cases: 82301.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    1171.0
Freq: D, dtype: float64
new total cases: 84545.0, old total cases: 83472.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    1073.0
Freq: D, dtype: float64
new total cases: 85697.0, old total cases: 84545.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    1152.0
Freq: D, dtype: float64
new total cases: 86571.0, old total cases: 85697.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    874.0
Freq: D, dtype: float64
new total cases: 87624.0, old total cases: 86571.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    1053.0
Freq: D, dtype: float64
new total cases: 88741.0, old total cases: 87624.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    1117.0
Freq: D, dtype: float64
new total cases: 89763.0, old total cases: 88741.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    1022.0
Freq: D, dtype: float64
new total cases: 90757.0, old total cases: 89763.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    994.0
Freq: D, dtype: float64
new total cases: 91783.0, old total cases: 90757.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    1026.0
Freq: D, dtype: float64
new total cases: 92797.0, old total cases: 91783.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    1014.0
Freq: D, dtype: float64
new total cases: 93681.0, old total cases: 92797.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    884.0
Freq: D, dtype: float64
new total cases: 94864.0, old total cases: 93681.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    1183.0
Freq: D, dtype: float64
new total cases: 96123.0, old total cases: 94864.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    1259.0
Freq: D, dtype: float64
new total cases: 97193.0, old total cases: 96123.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    1070.0
Freq: D, dtype: float64
new total cases: 98381.0, old total cases: 97193.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    1188.0
Freq: D, dtype: float64
new total cases: 99747.0, old total cases: 98381.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    1366.0
Freq: D, dtype: float64
new total cases: 100717.0, old total cases: 99747.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    970.0
Freq: D, dtype: float64
new total cases: 102294.0, old total cases: 100717.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    788.5
2017-09-30    788.5
Freq: D, dtype: float64
new total cases: 103280.0, old total cases: 102294.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    986.0
Freq: D, dtype: float64
new total cases: 103280.0, old total cases: 103280.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 105092.0, old total cases: 103280.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    1812.0
Freq: D, dtype: float64
new total cases: 106169.0, old total cases: 105092.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    1077.0
Freq: D, dtype: float64
new total cases: 107019.0, old total cases: 106169.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    850.0
Freq: D, dtype: float64
new total cases: 108917.0, old total cases: 107019.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    632.666667
2017-10-07    632.666667
2017-10-08    632.666667
Freq: D, dtype: float64
new total cases: 111219.0, old total cases: 108917.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    2302.0
Freq: D, dtype: float64
new total cases: 112638.0, old total cases: 111219.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    1419.0
Freq: D, dtype: float64
new total cases: 113632.0, old total cases: 112638.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    994.0
Freq: D, dtype: float64
new total cases: 116772.0, old total cases: 113632.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    1046.666667
2017-10-13    1046.666667
2017-10-14    1046.666667
Freq: D, dtype: float64
new total cases: 118798.0, old total cases: 116772.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    1013.0
2017-10-16    1013.0
Freq: D, dtype: float64
new total cases: 119684.0, old total cases: 118798.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    886.0
Freq: D, dtype: float64
new total cases: 122167.0, old total cases: 119684.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    620.75
2017-10-19    620.75
2017-10-20    620.75
2017-10-21    620.75
Freq: D, dtype: float64
new total cases: 122869.0, old total cases: 122167.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    702.0
Freq: D, dtype: float64
new total cases: 124636.0, old total cases: 122869.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    589.0
2017-10-24    589.0
2017-10-25    589.0
Freq: D, dtype: float64
new total cases: 126318.0, old total cases: 124636.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    560.666667
2017-10-27    560.666667
2017-10-28    560.666667
Freq: D, dtype: float64
new total cases: 126830.0, old total cases: 126318.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    512.0
Freq: D, dtype: float64
new total cases: 127366.0, old total cases: 126830.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    536.0
Freq: D, dtype: float64
new total cases: 129538.0, old total cases: 127366.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    543.0
2017-11-01    543.0
2017-11-02    543.0
2017-11-03    543.0
Freq: D, dtype: float64
new total cases: 129896.0, old total cases: 129538.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    358.0
Freq: D, dtype: float64
new total cases: 130390.0, old total cases: 129896.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    494.0
Freq: D, dtype: float64
new total cases: 130943.0, old total cases: 130390.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    553.0
Freq: D, dtype: float64
new total cases: 131342.0, old total cases: 130943.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    399.0
Freq: D, dtype: float64
new total cases: 131827.0, old total cases: 131342.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    485.0
Freq: D, dtype: float64
new total cases: 136937.0, old total cases: 131827.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    464.545455
2017-11-10    464.545455
2017-11-11    464.545455
2017-11-12    464.545455
2017-11-13    464.545455
2017-11-14    464.545455
2017-11-15    464.545455
2017-11-16    464.545455
2017-11-17    464.545455
2017-11-18    464.545455
2017-11-19    464.545455
Freq: D, dtype: float64
new total cases: 139145.0, old total cases: 136937.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    315.428571
2017-11-21    315.428571
2017-11-22    315.428571
2017-11-23    315.428571
2017-11-24    315.428571
2017-11-25    315.428571
2017-11-26    315.428571
Freq: D, dtype: float64
new total cases: 145559.0, old total cases: 139145.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    305.428571
2017-11-28    305.428571
2017-11-29    305.428571
2017-11-30    305.428571
2017-12-01    305.428571
2017-12-02    305.428571
2017-12-03    305.428571
2017-12-04    305.428571
2017-12-05    305.428571
2017-12-06    305.428571
2017-12-07    305.428571
2017-12-08    305.428571
2017-12-09    305.428571
2017-12-10    305.428571
2017-12-11    305.428571
2017-12-12    305.428571
2017-12-13    305.428571
2017-12-14    305.428571
2017-12-15    305.428571
2017-12-16    305.428571
2017-12-17    305.428571
Freq: D, dtype: float64
new total cases: 149041.0, old total cases: 145559.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    248.714286
2017-12-19    248.714286
2017-12-20    248.714286
2017-12-21    248.714286
2017-12-22    248.714286
2017-12-23    248.714286
2017-12-24    248.714286
2017-12-25    248.714286
2017-12-26    248.714286
2017-12-27    248.714286
2017-12-28    248.714286
2017-12-29    248.714286
2017-12-30    248.714286
2017-12-31    248.714286
Freq: D, dtype: float64
new total cases: 150319.0, old total cases: 149041.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    182.571429
2018-01-02    182.571429
2018-01-03    182.571429
2018-01-04    182.571429
2018-01-05    182.571429
2018-01-06    182.571429
2018-01-07    182.571429
Freq: D, dtype: float64
new total cases: 150965.0, old total cases: 150319.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    92.285714
2018-01-09    92.285714
2018-01-10    92.285714
2018-01-11    92.285714
2018-01-12    92.285714
2018-01-13    92.285714
2018-01-14    92.285714
Freq: D, dtype: float64
new total cases: 152592.0, old total cases: 150965.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    232.428571
2018-01-16    232.428571
2018-01-17    232.428571
2018-01-18    232.428571
2018-01-19    232.428571
2018-01-20    232.428571
2018-01-21    232.428571
Freq: D, dtype: float64
new total cases: 153446.0, old total cases: 152592.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    122.0
2018-01-23    122.0
2018-01-24    122.0
2018-01-25    122.0
2018-01-26    122.0
2018-01-27    122.0
2018-01-28    122.0
Freq: D, dtype: float64
new total cases: 154262.0, old total cases: 153446.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    116.571429
2018-01-30    116.571429
2018-01-31    116.571429
2018-02-01    116.571429
2018-02-02    116.571429
2018-02-03    116.571429
2018-02-04    116.571429
Freq: D, dtype: float64
new total cases: 155245.0, old total cases: 154262.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    140.428571
2018-02-06    140.428571
2018-02-07    140.428571
2018-02-08    140.428571
2018-02-09    140.428571
2018-02-10    140.428571
2018-02-11    140.428571
Freq: D, dtype: float64
new total cases: 155908.0, old total cases: 155245.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    94.714286
2018-02-13    94.714286
2018-02-14    94.714286
2018-02-15    94.714286
2018-02-16    94.714286
2018-02-17    94.714286
2018-02-18    94.714286
Freq: D, dtype: float64
new total cases: 2177.0, old total cases: 1378.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    159.8
2017-05-24    159.8
2017-05-25    159.8
2017-05-26    159.8
2017-05-27    159.8
Freq: D, dtype: float64
new total cases: 2567.0, old total cases: 2177.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    130.0
2017-05-29    130.0
2017-05-30    130.0
Freq: D, dtype: float64
new total cases: 4274.0, old total cases: 2567.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    341.4
2017-06-01    341.4
2017-06-02    341.4
2017-06-03    341.4
2017-06-04    341.4
Freq: D, dtype: float64
new total cases: 6041.0, old total cases: 4274.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    589.0
2017-06-06    589.0
2017-06-07    589.0
Freq: D, dtype: float64
new total cases: 8623.0, old total cases: 6041.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    860.666667
2017-06-09    860.666667
2017-06-10    860.666667
Freq: D, dtype: float64
new total cases: 9490.0, old total cases: 8623.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    433.5
2017-06-12    433.5
Freq: D, dtype: float64
new total cases: 9996.0, old total cases: 9490.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    506.0
Freq: D, dtype: float64
new total cases: 10323.0, old total cases: 9996.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    327.0
Freq: D, dtype: float64
new total cases: 11911.0, old total cases: 10323.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    529.333333
2017-06-16    529.333333
2017-06-17    529.333333
Freq: D, dtype: float64
new total cases: 12832.0, old total cases: 11911.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    921.0
Freq: D, dtype: float64
new total cases: 13383.0, old total cases: 12832.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    551.0
Freq: D, dtype: float64
new total cases: 13865.0, old total cases: 13383.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    482.0
Freq: D, dtype: float64
new total cases: 14088.0, old total cases: 13865.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    223.0
Freq: D, dtype: float64
new total cases: 14778.0, old total cases: 14088.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    690.0
Freq: D, dtype: float64
new total cases: 15093.0, old total cases: 14778.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    315.0
Freq: D, dtype: float64
new total cases: 15785.0, old total cases: 15093.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    692.0
Freq: D, dtype: float64
new total cases: 16236.0, old total cases: 15785.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    451.0
Freq: D, dtype: float64
new total cases: 16489.0, old total cases: 16236.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    253.0
Freq: D, dtype: float64
new total cases: 16662.0, old total cases: 16489.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    173.0
Freq: D, dtype: float64
new total cases: 17135.0, old total cases: 16662.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    473.0
Freq: D, dtype: float64
new total cases: 17889.0, old total cases: 17135.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    754.0
Freq: D, dtype: float64
new total cases: 18663.0, old total cases: 17889.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    774.0
Freq: D, dtype: float64
new total cases: 19194.0, old total cases: 18663.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    531.0
Freq: D, dtype: float64
new total cases: 19993.0, old total cases: 19194.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    799.0
Freq: D, dtype: float64
new total cases: 20671.0, old total cases: 19993.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    678.0
Freq: D, dtype: float64
new total cases: 21306.0, old total cases: 20671.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    635.0
Freq: D, dtype: float64
new total cases: 22124.0, old total cases: 21306.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    818.0
Freq: D, dtype: float64
new total cases: 22737.0, old total cases: 22124.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    613.0
Freq: D, dtype: float64
new total cases: 23129.0, old total cases: 22737.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    392.0
Freq: D, dtype: float64
new total cases: 24834.0, old total cases: 23129.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    568.333333
2017-07-09    568.333333
2017-07-10    568.333333
Freq: D, dtype: float64
new total cases: 25433.0, old total cases: 24834.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    599.0
Freq: D, dtype: float64
new total cases: 25723.0, old total cases: 25433.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    290.0
Freq: D, dtype: float64
new total cases: 26137.0, old total cases: 25723.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    414.0
Freq: D, dtype: float64
new total cases: 26583.0, old total cases: 26137.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    446.0
Freq: D, dtype: float64
new total cases: 26676.0, old total cases: 26583.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    93.0
Freq: D, dtype: float64
new total cases: 27098.0, old total cases: 26676.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    422.0
Freq: D, dtype: float64
new total cases: 27454.0, old total cases: 27098.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    356.0
Freq: D, dtype: float64
new total cases: 27882.0, old total cases: 27454.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    428.0
Freq: D, dtype: float64
new total cases: 28250.0, old total cases: 27882.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    368.0
Freq: D, dtype: float64
new total cases: 28470.0, old total cases: 28250.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    220.0
Freq: D, dtype: float64
new total cases: 28473.0, old total cases: 28470.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    3.0
Freq: D, dtype: float64
new total cases: 29260.0, old total cases: 28473.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    787.0
Freq: D, dtype: float64
new total cases: 29529.0, old total cases: 29260.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    269.0
Freq: D, dtype: float64
new total cases: 29723.0, old total cases: 29529.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    194.0
Freq: D, dtype: float64
new total cases: 30389.0, old total cases: 29723.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    666.0
Freq: D, dtype: float64
new total cases: 30394.0, old total cases: 30389.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    5.0
Freq: D, dtype: float64
new total cases: 30967.0, old total cases: 30394.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    573.0
Freq: D, dtype: float64
new total cases: 31252.0, old total cases: 30967.0

new total cases: 328.0, old total cases: 168.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    32.0
2017-05-24    32.0
2017-05-25    32.0
2017-05-26    32.0
2017-05-27    32.0
Freq: D, dtype: float64
new total cases: 471.0, old total cases: 328.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    47.666667
2017-05-29    47.666667
2017-05-30    47.666667
Freq: D, dtype: float64
new total cases: 520.0, old total cases: 471.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    9.8
2017-06-01    9.8
2017-06-02    9.8
2017-06-03    9.8
2017-06-04    9.8
Freq: D, dtype: float64
new total cases: 724.0, old total cases: 520.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    68.0
2017-06-06    68.0
2017-06-07    68.0
Freq: D, dtype: float64
new total cases: 1042.0, old total cases: 724.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    106.0
2017-06-09    106.0
2017-06-10    106.0
Freq: D, dtype: float64
new total cases: 1239.0, old total cases: 1042.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    98.5
2017-06-12    98.5
Freq: D, dtype: float64
new total cases: 1241.0, old total cases: 1239.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    2.0
Freq: D, dtype: float64
new total cases: 1476.0, old total cases: 1241.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    235.0
Freq: D, dtype: float64
new total cases: 1586.0, old total cases: 1476.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    36.666667
2017-06-16    36.666667
2017-06-17    36.666667
Freq: D, dtype: float64
new total cases: 1900.0, old total cases: 1586.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    314.0
Freq: D, dtype: float64
new total cases: 1925.0, old total cases: 1900.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    25.0
Freq: D, dtype: float64
new total cases: 2138.0, old total cases: 1925.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    213.0
Freq: D, dtype: float64
new total cases: 2147.0, old total cases: 2138.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    9.0
Freq: D, dtype: float64
new total cases: 2163.0, old total cases: 2147.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    16.0
Freq: D, dtype: float64
new total cases: 2170.0, old total cases: 2163.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    7.0
Freq: D, dtype: float64
new total cases: 2496.0, old total cases: 2170.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    326.0
Freq: D, dtype: float64
new total cases: 2503.0, old total cases: 2496.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    7.0
Freq: D, dtype: float64
new total cases: 2779.0, old total cases: 2503.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    276.0
Freq: D, dtype: float64
new total cases: 2794.0, old total cases: 2779.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    15.0
Freq: D, dtype: float64
new total cases: 3014.0, old total cases: 2794.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    220.0
Freq: D, dtype: float64
new total cases: 3026.0, old total cases: 3014.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    12.0
Freq: D, dtype: float64
new total cases: 3320.0, old total cases: 3026.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    294.0
Freq: D, dtype: float64
new total cases: 3339.0, old total cases: 3320.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    19.0
Freq: D, dtype: float64
new total cases: 3597.0, old total cases: 3339.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    258.0
Freq: D, dtype: float64
new total cases: 3608.0, old total cases: 3597.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    11.0
Freq: D, dtype: float64
new total cases: 3754.0, old total cases: 3608.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    146.0
Freq: D, dtype: float64
new total cases: 4063.0, old total cases: 3754.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    309.0
Freq: D, dtype: float64
new total cases: 4063.0, old total cases: 4063.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    0.0
Freq: D, dtype: float64
new total cases: 4072.0, old total cases: 4063.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    9.0
Freq: D, dtype: float64
new total cases: 4090.0, old total cases: 4072.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    6.0
2017-07-09    6.0
2017-07-10    6.0
Freq: D, dtype: float64
new total cases: 4097.0, old total cases: 4090.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    7.0
Freq: D, dtype: float64
new total cases: 4103.0, old total cases: 4097.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    6.0
Freq: D, dtype: float64
new total cases: 4108.0, old total cases: 4103.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    5.0
Freq: D, dtype: float64
new total cases: 4536.0, old total cases: 4108.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    428.0
Freq: D, dtype: float64
new total cases: 4540.0, old total cases: 4536.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    4.0
Freq: D, dtype: float64
new total cases: 4540.0, old total cases: 4540.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    0.0
Freq: D, dtype: float64
new total cases: 4545.0, old total cases: 4540.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    5.0
Freq: D, dtype: float64
new total cases: 4553.0, old total cases: 4545.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    8.0
Freq: D, dtype: float64
new total cases: 4553.0, old total cases: 4553.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    0.0
Freq: D, dtype: float64
new total cases: 4570.0, old total cases: 4553.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    17.0
Freq: D, dtype: float64
new total cases: 4575.0, old total cases: 4570.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    5.0
Freq: D, dtype: float64
new total cases: 4579.0, old total cases: 4575.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    4.0
Freq: D, dtype: float64
new total cases: 4583.0, old total cases: 4579.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    4.0
Freq: D, dtype: float64
new total cases: 4591.0, old total cases: 4583.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    8.0
Freq: D, dtype: float64
new total cases: 4591.0, old total cases: 4591.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    0.0
Freq: D, dtype: float64
new total cases: 5911.0, old total cases: 4591.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    1320.0
Freq: D, dtype: float64
new total cases: 5914.0, old total cases: 5911.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    3.0
Freq: D, dtype: float64
new total cases: 5914.0, old total cases: 5914.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    0.0
Freq: D, dtype: float64
new total cases: 6905.0, old total cases: 5914.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    991.0
Freq: D, dtype: float64
new total cases: 6913.0, old total cases: 6905.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    8.0
Freq: D, dtype: float64
new total cases: 7124.0, old total cases: 6913.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    211.0
Freq: D, dtype: float64
new total cases: 7605.0, old total cases: 7124.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    481.0
Freq: D, dtype: float64
new total cases: 8090.0, old total cases: 7605.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    242.5
2017-08-03    242.5
Freq: D, dtype: float64
new total cases: 9009.0, old total cases: 8090.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    306.333333
2017-08-05    306.333333
2017-08-06    306.333333
Freq: D, dtype: float64
new total cases: 10475.0, old total cases: 9009.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    209.428571
2017-08-08    209.428571
2017-08-09    209.428571
2017-08-10    209.428571
2017-08-11    209.428571
2017-08-12    209.428571
2017-08-13    209.428571
Freq: D, dtype: float64
new total cases: 10982.0, old total cases: 10475.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    253.5
2017-08-15    253.5
Freq: D, dtype: float64
new total cases: 11230.0, old total cases: 10982.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    248.0
Freq: D, dtype: float64
new total cases: 11457.0, old total cases: 11230.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    227.0
Freq: D, dtype: float64
new total cases: 11686.0, old total cases: 11457.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    229.0
Freq: D, dtype: float64
new total cases: 11688.0, old total cases: 11686.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    2.0
Freq: D, dtype: float64
new total cases: 11689.0, old total cases: 11688.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    1.0
Freq: D, dtype: float64
new total cases: 12150.0, old total cases: 11689.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    461.0
Freq: D, dtype: float64
new total cases: 12640.0, old total cases: 12150.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    490.0
Freq: D, dtype: float64
new total cases: 12897.0, old total cases: 12640.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    257.0
Freq: D, dtype: float64
new total cases: 13148.0, old total cases: 12897.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    251.0
Freq: D, dtype: float64
new total cases: 13416.0, old total cases: 13148.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    134.0
2017-08-26    134.0
Freq: D, dtype: float64
new total cases: 13851.0, old total cases: 13416.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    435.0
Freq: D, dtype: float64
new total cases: 14150.0, old total cases: 13851.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    299.0
Freq: D, dtype: float64
new total cases: 14366.0, old total cases: 14150.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    216.0
Freq: D, dtype: float64
new total cases: 14569.0, old total cases: 14366.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    203.0
Freq: D, dtype: float64
new total cases: 14731.0, old total cases: 14569.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    162.0
Freq: D, dtype: float64
new total cases: 14911.0, old total cases: 14731.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    180.0
Freq: D, dtype: float64
new total cases: 15022.0, old total cases: 14911.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    111.0
Freq: D, dtype: float64
new total cases: 15238.0, old total cases: 15022.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    216.0
Freq: D, dtype: float64
new total cases: 15446.0, old total cases: 15238.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    208.0
Freq: D, dtype: float64
new total cases: 15653.0, old total cases: 15446.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    207.0
Freq: D, dtype: float64
new total cases: 15867.0, old total cases: 15653.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    214.0
Freq: D, dtype: float64
new total cases: 15870.0, old total cases: 15867.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    3.0
Freq: D, dtype: float64
new total cases: 16090.0, old total cases: 15870.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    220.0
Freq: D, dtype: float64
new total cases: 16261.0, old total cases: 16090.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    171.0
Freq: D, dtype: float64
new total cases: 16424.0, old total cases: 16261.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    163.0
Freq: D, dtype: float64
new total cases: 16637.0, old total cases: 16424.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    213.0
Freq: D, dtype: float64
new total cases: 16877.0, old total cases: 16637.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    240.0
Freq: D, dtype: float64
new total cases: 17116.0, old total cases: 16877.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    239.0
Freq: D, dtype: float64
new total cases: 17527.0, old total cases: 17116.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    411.0
Freq: D, dtype: float64
new total cases: 17529.0, old total cases: 17527.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    2.0
Freq: D, dtype: float64
new total cases: 17771.0, old total cases: 17529.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    242.0
Freq: D, dtype: float64
new total cases: 17945.0, old total cases: 17771.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    174.0
Freq: D, dtype: float64
new total cases: 18146.0, old total cases: 17945.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    201.0
Freq: D, dtype: float64
new total cases: 18386.0, old total cases: 18146.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    240.0
Freq: D, dtype: float64
new total cases: 18587.0, old total cases: 18386.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    201.0
Freq: D, dtype: float64
new total cases: 18779.0, old total cases: 18587.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    192.0
Freq: D, dtype: float64
new total cases: 18988.0, old total cases: 18779.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    209.0
Freq: D, dtype: float64
new total cases: 19153.0, old total cases: 18988.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    165.0
Freq: D, dtype: float64
new total cases: 19315.0, old total cases: 19153.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    162.0
Freq: D, dtype: float64
new total cases: 19512.0, old total cases: 19315.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    197.0
Freq: D, dtype: float64
new total cases: 19813.0, old total cases: 19512.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    301.0
Freq: D, dtype: float64
new total cases: 20019.0, old total cases: 19813.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    206.0
Freq: D, dtype: float64
new total cases: 20220.0, old total cases: 20019.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    201.0
Freq: D, dtype: float64
new total cases: 20535.0, old total cases: 20220.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    157.5
2017-09-30    157.5
Freq: D, dtype: float64
new total cases: 20678.0, old total cases: 20535.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    143.0
Freq: D, dtype: float64
new total cases: 20678.0, old total cases: 20678.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 20999.0, old total cases: 20678.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    321.0
Freq: D, dtype: float64
new total cases: 21149.0, old total cases: 20999.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    150.0
Freq: D, dtype: float64
new total cases: 21149.0, old total cases: 21149.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    0.0
Freq: D, dtype: float64
new total cases: 21508.0, old total cases: 21149.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    119.666667
2017-10-07    119.666667
2017-10-08    119.666667
Freq: D, dtype: float64
new total cases: 21763.0, old total cases: 21508.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    255.0
Freq: D, dtype: float64
new total cases: 21763.0, old total cases: 21763.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    0.0
Freq: D, dtype: float64
new total cases: 21977.0, old total cases: 21763.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    214.0
Freq: D, dtype: float64
new total cases: 22168.0, old total cases: 21977.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    63.666667
2017-10-13    63.666667
2017-10-14    63.666667
Freq: D, dtype: float64
new total cases: 22308.0, old total cases: 22168.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    70.0
2017-10-16    70.0
Freq: D, dtype: float64
new total cases: 22358.0, old total cases: 22308.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    50.0
Freq: D, dtype: float64
new total cases: 22454.0, old total cases: 22358.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    24.0
2017-10-19    24.0
2017-10-20    24.0
2017-10-21    24.0
Freq: D, dtype: float64
new total cases: 22458.0, old total cases: 22454.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    4.0
Freq: D, dtype: float64
new total cases: 22469.0, old total cases: 22458.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    3.666667
2017-10-24    3.666667
2017-10-25    3.666667
Freq: D, dtype: float64
new total cases: 22474.0, old total cases: 22469.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    1.666667
2017-10-27    1.666667
2017-10-28    1.666667
Freq: D, dtype: float64
new total cases: 22480.0, old total cases: 22474.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    6.0
Freq: D, dtype: float64
new total cases: 22481.0, old total cases: 22480.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    1.0
Freq: D, dtype: float64
new total cases: 22503.0, old total cases: 22481.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    5.5
2017-11-01    5.5
2017-11-02    5.5
2017-11-03    5.5
Freq: D, dtype: float64
new total cases: 22505.0, old total cases: 22503.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    2.0
Freq: D, dtype: float64
new total cases: 22508.0, old total cases: 22505.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    3.0
Freq: D, dtype: float64
new total cases: 22514.0, old total cases: 22508.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    6.0
Freq: D, dtype: float64
new total cases: 22520.0, old total cases: 22514.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    6.0
Freq: D, dtype: float64

new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    7.5
2017-08-26    7.5
Freq: D, dtype: float64
new total cases: 1091.0, old total cases: 1081.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    10.0
Freq: D, dtype: float64
new total cases: 1104.0, old total cases: 1091.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    13.0
Freq: D, dtype: float64
new total cases: 1109.0, old total cases: 1104.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    5.0
Freq: D, dtype: float64
new total cases: 1109.0, old total cases: 1109.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    0.0
Freq: D, dtype: float64
new total cases: 1119.0, old total cases: 1109.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    10.0
Freq: D, dtype: float64
new total cases: 1121.0, old total cases: 1119.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    2.0
Freq: D, dtype: float64
new total cases: 1126.0, old total cases: 1121.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    5.0
Freq: D, dtype: float64
new total cases: 1130.0, old total cases: 1126.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    4.0
Freq: D, dtype: float64
new total cases: 1137.0, old total cases: 1130.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    7.0
Freq: D, dtype: float64
new total cases: 1140.0, old total cases: 1137.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    3.0
Freq: D, dtype: float64
new total cases: 1143.0, old total cases: 1140.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    3.0
Freq: D, dtype: float64
new total cases: 1147.0, old total cases: 1143.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    4.0
Freq: D, dtype: float64
new total cases: 1147.0, old total cases: 1147.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    0.0
Freq: D, dtype: float64
new total cases: 1148.0, old total cases: 1147.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    1.0
Freq: D, dtype: float64
new total cases: 1151.0, old total cases: 1148.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    3.0
Freq: D, dtype: float64
new total cases: 1153.0, old total cases: 1151.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    2.0
Freq: D, dtype: float64
new total cases: 1154.0, old total cases: 1153.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    1.0
Freq: D, dtype: float64
new total cases: 1156.0, old total cases: 1154.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    2.0
Freq: D, dtype: float64
new total cases: 1159.0, old total cases: 1156.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    3.0
Freq: D, dtype: float64
new total cases: 1159.0, old total cases: 1159.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    0.0
Freq: D, dtype: float64
new total cases: 1159.0, old total cases: 1159.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    0.0
Freq: D, dtype: float64
new total cases: 1159.0, old total cases: 1159.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    0.0
Freq: D, dtype: float64
new total cases: 1161.0, old total cases: 1159.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    2.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1161.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    1.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    0.0
2017-09-30    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    0.0
Freq: D, dtype: float64
new total cases: 1162.0, old total cases: 1162.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    0.0
2017-10-07    0.0
2017-10-08    0.0
Freq: D, dtype: float64
new total cases: 1163.0, old total cases: 1162.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    1.0
Freq: D, dtype: float64
new total cases: 1163.0, old total cases: 1163.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    0.0
Freq: D, dtype: float64
new total cases: 1163.0, old total cases: 1163.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    0.0
Freq: D, dtype: float64
new total cases: 1163.0, old total cases: 1163.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    0.0
2017-10-13    0.0
2017-10-14    0.0
Freq: D, dtype: float64
new total cases: 1163.0, old total cases: 1163.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    0.0
2017-10-16    0.0
Freq: D, dtype: float64
new total cases: 1163.0, old total cases: 1163.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    0.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1163.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    0.25
2017-10-19    0.25
2017-10-20    0.25
2017-10-21    0.25
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    0.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    0.0
2017-10-24    0.0
2017-10-25    0.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    0.0
2017-10-27    0.0
2017-10-28    0.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    0.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    0.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    0.0
2017-11-01    0.0
2017-11-02    0.0
2017-11-03    0.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    0.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    0.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    0.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    0.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    0.0
Freq: D, dtype: float64
new total cases: 1166.0, old total cases: 1164.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    0.181818
2017-11-10    0.181818
2017-11-11    0.181818
2017-11-12    0.181818
2017-11-13    0.181818
2017-11-14    0.181818
2017-11-15    0.181818
2017-11-16    0.181818
2017-11-17    0.181818
2017-11-18    0.181818
2017-11-19    0.181818
Freq: D, dtype: float64
new total cases: 1167.0, old total cases: 1166.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    0.142857
2017-11-21    0.142857
2017-11-22    0.142857
2017-11-23    0.142857
2017-11-24    0.142857
2017-11-25    0.142857
2017-11-26    0.142857
Freq: D, dtype: float64
new total cases: 1168.0, old total cases: 1167.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    0.047619
2017-11-28    0.047619
2017-11-29    0.047619
2017-11-30    0.047619
2017-12-01    0.047619
2017-12-02    0.047619
2017-12-03    0.047619
2017-12-04    0.047619
2017-12-05    0.047619
2017-12-06    0.047619
2017-12-07    0.047619
2017-12-08    0.047619
2017-12-09    0.047619
2017-12-10    0.047619
2017-12-11    0.047619
2017-12-12    0.047619
2017-12-13    0.047619
2017-12-14    0.047619
2017-12-15    0.047619
2017-12-16    0.047619
2017-12-17    0.047619
Freq: D, dtype: float64
new total cases: 1168.0, old total cases: 1168.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    0.0
2017-12-19    0.0
2017-12-20    0.0
2017-12-21    0.0
2017-12-22    0.0
2017-12-23    0.0
2017-12-24    0.0
2017-12-25    0.0
2017-12-26    0.0
2017-12-27    0.0
2017-12-28    0.0
2017-12-29    0.0
2017-12-30    0.0
2017-12-31    0.0
Freq: D, dtype: float64
new total cases: 1168.0, old total cases: 1168.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    0.0
2018-01-02    0.0
2018-01-03    0.0
2018-01-04    0.0
2018-01-05    0.0
2018-01-06    0.0
2018-01-07    0.0
Freq: D, dtype: float64
new total cases: 1168.0, old total cases: 1168.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    0.0
2018-01-09    0.0
2018-01-10    0.0
2018-01-11    0.0
2018-01-12    0.0
2018-01-13    0.0
2018-01-14    0.0
Freq: D, dtype: float64
new total cases: 1168.0, old total cases: 1168.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    0.0
2018-01-16    0.0
2018-01-17    0.0
2018-01-18    0.0
2018-01-19    0.0
2018-01-20    0.0
2018-01-21    0.0
Freq: D, dtype: float64
new total cases: 1168.0, old total cases: 1168.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    0.0
2018-01-23    0.0
2018-01-24    0.0
2018-01-25    0.0
2018-01-26    0.0
2018-01-27    0.0
2018-01-28    0.0
Freq: D, dtype: float64
new total cases: 1168.0, old total cases: 1168.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    0.0
2018-01-30    0.0
2018-01-31    0.0
2018-02-01    0.0
2018-02-02    0.0
2018-02-03    0.0
2018-02-04    0.0
Freq: D, dtype: float64
new total cases: 1168.0, old total cases: 1168.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    0.0
2018-02-06    0.0
2018-02-07    0.0
2018-02-08    0.0
2018-02-09    0.0
2018-02-10    0.0
2018-02-11    0.0
Freq: D, dtype: float64
new total cases: 1168.0, old total cases: 1168.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    0.0
2018-02-13    0.0
2018-02-14    0.0
2018-02-15    0.0
2018-02-16    0.0
2018-02-17    0.0
2018-02-18    0.0
Freq: D, dtype: float64
new total cases: 3594.0, old total cases: 2486.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    221.6
2017-05-24    221.6
2017-05-25    221.6
2017-05-26    221.6
2017-05-27    221.6
Freq: D, dtype: float64
new total cases: 4246.0, old total cases: 3594.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    217.333333
2017-05-29    217.333333
2017-05-30    217.333333
Freq: D, dtype: float64
new total cases: 5514.0, old total cases: 4246.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    253.6
2017-06-01    253.6
2017-06-02    253.6
2017-06-03    253.6
2017-06-04    253.6
Freq: D, dtype: float64
new total cases: 6196.0, old total cases: 5514.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    227.333333
2017-06-06    227.333333
2017-06-07    227.333333
Freq: D, dtype: float64
new total cases: 7126.0, old total cases: 6196.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    310.0
2017-06-09    310.0
2017-06-10    310.0
Freq: D, dtype: float64
new total cases: 7405.0, old total cases: 7126.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    139.5
2017-06-12    139.5
Freq: D, dtype: float64
new total cases: 7634.0, old total cases: 7405.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    229.0
Freq: D, dtype: float64
new total cases: 7815.0, old total cases: 7634.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    181.0
Freq: D, dtype: float64
new total cases: 8535.0, old total cases: 7815.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    240.0
2017-06-16    240.0
2017-06-17    240.0
Freq: D, dtype: float64
new total cases: 8822.0, old total cases: 8535.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    287.0
Freq: D, dtype: float64
new total cases: 9116.0, old total cases: 8822.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    294.0
Freq: D, dtype: float64
new total cases: 9214.0, old total cases: 9116.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    98.0
Freq: D, dtype: float64
new total cases: 9466.0, old total cases: 9214.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    252.0
Freq: D, dtype: float64
new total cases: 9744.0, old total cases: 9466.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    278.0
Freq: D, dtype: float64
new total cases: 10035.0, old total cases: 9744.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    291.0
Freq: D, dtype: float64
new total cases: 10305.0, old total cases: 10035.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    270.0
Freq: D, dtype: float64
new total cases: 10500.0, old total cases: 10305.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    195.0
Freq: D, dtype: float64
new total cases: 10892.0, old total cases: 10500.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    392.0
Freq: D, dtype: float64
new total cases: 11320.0, old total cases: 10892.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    428.0
Freq: D, dtype: float64
new total cases: 11763.0, old total cases: 11320.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    443.0
Freq: D, dtype: float64
new total cases: 12128.0, old total cases: 11763.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    365.0
Freq: D, dtype: float64
new total cases: 12648.0, old total cases: 12128.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    520.0
Freq: D, dtype: float64
new total cases: 12936.0, old total cases: 12648.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    288.0
Freq: D, dtype: float64
new total cases: 13228.0, old total cases: 12936.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    292.0
Freq: D, dtype: float64
new total cases: 13465.0, old total cases: 13228.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    237.0
Freq: D, dtype: float64
new total cases: 13811.0, old total cases: 13465.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    346.0
Freq: D, dtype: float64
new total cases: 14193.0, old total cases: 13811.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    382.0
Freq: D, dtype: float64
new total cases: 14572.0, old total cases: 14193.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    379.0
Freq: D, dtype: float64
new total cases: 14921.0, old total cases: 14572.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    349.0
Freq: D, dtype: float64
new total cases: 15819.0, old total cases: 14921.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    299.333333
2017-07-09    299.333333
2017-07-10    299.333333
Freq: D, dtype: float64
new total cases: 16444.0, old total cases: 15819.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    625.0
Freq: D, dtype: float64
new total cases: 16922.0, old total cases: 16444.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    478.0
Freq: D, dtype: float64
new total cases: 17877.0, old total cases: 16922.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    955.0
Freq: D, dtype: float64
new total cases: 18243.0, old total cases: 17877.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    366.0
Freq: D, dtype: float64
new total cases: 18963.0, old total cases: 18243.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    720.0
Freq: D, dtype: float64
new total cases: 19278.0, old total cases: 18963.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    315.0
Freq: D, dtype: float64
new total cases: 19650.0, old total cases: 19278.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    372.0
Freq: D, dtype: float64
new total cases: 19997.0, old total cases: 19650.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    347.0
Freq: D, dtype: float64
new total cases: 20320.0, old total cases: 19997.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    323.0
Freq: D, dtype: float64
new total cases: 20320.0, old total cases: 20320.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    0.0
Freq: D, dtype: float64
new total cases: 20697.0, old total cases: 20320.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    377.0
Freq: D, dtype: float64
new total cases: 21537.0, old total cases: 20697.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    840.0
Freq: D, dtype: float64
new total cases: 22621.0, old total cases: 21537.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    1084.0
Freq: D, dtype: float64
new total cases: 22922.0, old total cases: 22621.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    301.0
Freq: D, dtype: float64

new total cases: 15456.0, old total cases: 15071.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    27.5
2017-12-19    27.5
2017-12-20    27.5
2017-12-21    27.5
2017-12-22    27.5
2017-12-23    27.5
2017-12-24    27.5
2017-12-25    27.5
2017-12-26    27.5
2017-12-27    27.5
2017-12-28    27.5
2017-12-29    27.5
2017-12-30    27.5
2017-12-31    27.5
Freq: D, dtype: float64
new total cases: 15924.0, old total cases: 15456.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    66.857143
2018-01-02    66.857143
2018-01-03    66.857143
2018-01-04    66.857143
2018-01-05    66.857143
2018-01-06    66.857143
2018-01-07    66.857143
Freq: D, dtype: float64
new total cases: 16403.0, old total cases: 15924.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    68.428571
2018-01-09    68.428571
2018-01-10    68.428571
2018-01-11    68.428571
2018-01-12    68.428571
2018-01-13    68.428571
2018-01-14    68.428571
Freq: D, dtype: float64
new total cases: 16853.0, old total cases: 16403.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    64.285714
2018-01-16    64.285714
2018-01-17    64.285714
2018-01-18    64.285714
2018-01-19    64.285714
2018-01-20    64.285714
2018-01-21    64.285714
Freq: D, dtype: float64
new total cases: 17217.0, old total cases: 16853.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    52.0
2018-01-23    52.0
2018-01-24    52.0
2018-01-25    52.0
2018-01-26    52.0
2018-01-27    52.0
2018-01-28    52.0
Freq: D, dtype: float64
new total cases: 17445.0, old total cases: 17217.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    32.571429
2018-01-30    32.571429
2018-01-31    32.571429
2018-02-01    32.571429
2018-02-02    32.571429
2018-02-03    32.571429
2018-02-04    32.571429
Freq: D, dtype: float64
new total cases: 17641.0, old total cases: 17445.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    28.0
2018-02-06    28.0
2018-02-07    28.0
2018-02-08    28.0
2018-02-09    28.0
2018-02-10    28.0
2018-02-11    28.0
Freq: D, dtype: float64
new total cases: 17841.0, old total cases: 17641.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    28.571429
2018-02-13    28.571429
2018-02-14    28.571429
2018-02-15    28.571429
2018-02-16    28.571429
2018-02-17    28.571429
2018-02-18    28.571429
Freq: D, dtype: float64
new total cases: 12544.0, old total cases: 9216.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    665.6
2017-05-24    665.6
2017-05-25    665.6
2017-05-26    665.6
2017-05-27    665.6
Freq: D, dtype: float64
new total cases: 13700.0, old total cases: 12544.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    385.333333
2017-05-29    385.333333
2017-05-30    385.333333
Freq: D, dtype: float64
new total cases: 16386.0, old total cases: 13700.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    537.2
2017-06-01    537.2
2017-06-02    537.2
2017-06-03    537.2
2017-06-04    537.2
Freq: D, dtype: float64
new total cases: 18887.0, old total cases: 16386.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    833.666667
2017-06-06    833.666667
2017-06-07    833.666667
Freq: D, dtype: float64
new total cases: 21538.0, old total cases: 18887.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    883.666667
2017-06-09    883.666667
2017-06-10    883.666667
Freq: D, dtype: float64
new total cases: 22113.0, old total cases: 21538.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    287.5
2017-06-12    287.5
Freq: D, dtype: float64
new total cases: 22661.0, old total cases: 22113.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    548.0
Freq: D, dtype: float64
new total cases: 23436.0, old total cases: 22661.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    775.0
Freq: D, dtype: float64
new total cases: 26126.0, old total cases: 23436.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    896.666667
2017-06-16    896.666667
2017-06-17    896.666667
Freq: D, dtype: float64
new total cases: 27134.0, old total cases: 26126.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    1008.0
Freq: D, dtype: float64
new total cases: 27825.0, old total cases: 27134.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    691.0
Freq: D, dtype: float64
new total cases: 29229.0, old total cases: 27825.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    1404.0
Freq: D, dtype: float64
new total cases: 30178.0, old total cases: 29229.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    949.0
Freq: D, dtype: float64
new total cases: 30882.0, old total cases: 30178.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    704.0
Freq: D, dtype: float64
new total cases: 31660.0, old total cases: 30882.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    778.0
Freq: D, dtype: float64
new total cases: 32455.0, old total cases: 31660.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    795.0
Freq: D, dtype: float64
new total cases: 32812.0, old total cases: 32455.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    357.0
Freq: D, dtype: float64
new total cases: 33349.0, old total cases: 32812.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    537.0
Freq: D, dtype: float64
new total cases: 34312.0, old total cases: 33349.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    963.0
Freq: D, dtype: float64
new total cases: 35060.0, old total cases: 34312.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    748.0
Freq: D, dtype: float64
new total cases: 35693.0, old total cases: 35060.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    633.0
Freq: D, dtype: float64
new total cases: 36240.0, old total cases: 35693.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    547.0
Freq: D, dtype: float64
new total cases: 36915.0, old total cases: 36240.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    675.0
Freq: D, dtype: float64
new total cases: 37981.0, old total cases: 36915.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    1066.0
Freq: D, dtype: float64
new total cases: 38638.0, old total cases: 37981.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    657.0
Freq: D, dtype: float64
new total cases: 39316.0, old total cases: 38638.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    678.0
Freq: D, dtype: float64
new total cases: 39972.0, old total cases: 39316.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    656.0
Freq: D, dtype: float64
new total cases: 40477.0, old total cases: 39972.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    505.0
Freq: D, dtype: float64
new total cases: 40840.0, old total cases: 40477.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    363.0
Freq: D, dtype: float64
new total cases: 42142.0, old total cases: 40840.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    434.0
2017-07-09    434.0
2017-07-10    434.0
Freq: D, dtype: float64
new total cases: 42765.0, old total cases: 42142.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    623.0
Freq: D, dtype: float64
new total cases: 43578.0, old total cases: 42765.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    813.0
Freq: D, dtype: float64
new total cases: 44187.0, old total cases: 43578.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    609.0
Freq: D, dtype: float64
new total cases: 44755.0, old total cases: 44187.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    568.0
Freq: D, dtype: float64
new total cases: 45227.0, old total cases: 44755.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    472.0
Freq: D, dtype: float64
new total cases: 45701.0, old total cases: 45227.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    474.0
Freq: D, dtype: float64
new total cases: 46477.0, old total cases: 45701.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    776.0
Freq: D, dtype: float64
new total cases: 46985.0, old total cases: 46477.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    508.0
Freq: D, dtype: float64
new total cases: 47647.0, old total cases: 46985.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    662.0
Freq: D, dtype: float64
new total cases: 48100.0, old total cases: 47647.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    453.0
Freq: D, dtype: float64
new total cases: 48430.0, old total cases: 48100.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    330.0
Freq: D, dtype: float64
new total cases: 48916.0, old total cases: 48430.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    486.0
Freq: D, dtype: float64
new total cases: 49311.0, old total cases: 48916.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    395.0
Freq: D, dtype: float64
new total cases: 49850.0, old total cases: 49311.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    539.0
Freq: D, dtype: float64
new total cases: 50331.0, old total cases: 49850.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    481.0
Freq: D, dtype: float64
new total cases: 50835.0, old total cases: 50331.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    504.0
Freq: D, dtype: float64
new total cases: 51083.0, old total cases: 50835.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    248.0
Freq: D, dtype: float64
new total cases: 51571.0, old total cases: 51083.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    488.0
Freq: D, dtype: float64
new total cases: 51900.0, old total cases: 51571.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    329.0
Freq: D, dtype: float64
new total cases: 52415.0, old total cases: 51900.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    515.0
Freq: D, dtype: float64
new total cases: 53975.0, old total cases: 52415.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    1560.0
Freq: D, dtype: float64
new total cases: 54651.0, old total cases: 53975.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    676.0
Freq: D, dtype: float64
new total cases: 55563.0, old total cases: 54651.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    456.0
2017-08-03    456.0
Freq: D, dtype: float64
new total cases: 57751.0, old total cases: 55563.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    729.333333
2017-08-05    729.333333
2017-08-06    729.333333
Freq: D, dtype: float64
new total cases: 60100.0, old total cases: 57751.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    335.571429
2017-08-08    335.571429
2017-08-09    335.571429
2017-08-10    335.571429
2017-08-11    335.571429
2017-08-12    335.571429
2017-08-13    335.571429
Freq: D, dtype: float64
new total cases: 61384.0, old total cases: 60100.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    642.0
2017-08-15    642.0
Freq: D, dtype: float64
new total cases: 61771.0, old total cases: 61384.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    387.0
Freq: D, dtype: float64
new total cases: 62193.0, old total cases: 61771.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    422.0
Freq: D, dtype: float64
new total cases: 62367.0, old total cases: 62193.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    174.0
Freq: D, dtype: float64
new total cases: 62557.0, old total cases: 62367.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    190.0
Freq: D, dtype: float64
new total cases: 62977.0, old total cases: 62557.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    420.0
Freq: D, dtype: float64
new total cases: 63480.0, old total cases: 62977.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    503.0
Freq: D, dtype: float64
new total cases: 63840.0, old total cases: 63480.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    360.0
Freq: D, dtype: float64
new total cases: 64174.0, old total cases: 63840.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    334.0
Freq: D, dtype: float64
new total cases: 64786.0, old total cases: 64174.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    612.0
Freq: D, dtype: float64
new total cases: 65111.0, old total cases: 64786.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    162.5
2017-08-26    162.5
Freq: D, dtype: float64
new total cases: 65399.0, old total cases: 65111.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    288.0
Freq: D, dtype: float64
new total cases: 65609.0, old total cases: 65399.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    210.0
Freq: D, dtype: float64
new total cases: 65878.0, old total cases: 65609.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    269.0
Freq: D, dtype: float64
new total cases: 66070.0, old total cases: 65878.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    192.0
Freq: D, dtype: float64
new total cases: 66523.0, old total cases: 66070.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    453.0
Freq: D, dtype: float64
new total cases: 66675.0, old total cases: 66523.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    152.0
Freq: D, dtype: float64
new total cases: 66928.0, old total cases: 66675.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    253.0
Freq: D, dtype: float64
new total cases: 67222.0, old total cases: 66928.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    294.0
Freq: D, dtype: float64
new total cases: 67734.0, old total cases: 67222.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    512.0
Freq: D, dtype: float64
new total cases: 68040.0, old total cases: 67734.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    306.0
Freq: D, dtype: float64
new total cases: 68349.0, old total cases: 68040.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    309.0
Freq: D, dtype: float64
new total cases: 68872.0, old total cases: 68349.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    523.0
Freq: D, dtype: float64
new total cases: 69162.0, old total cases: 68872.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    290.0
Freq: D, dtype: float64
new total cases: 69601.0, old total cases: 69162.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    439.0
Freq: D, dtype: float64
new total cases: 70012.0, old total cases: 69601.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    411.0
Freq: D, dtype: float64
new total cases: 70350.0, old total cases: 70012.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    338.0
Freq: D, dtype: float64
new total cases: 70669.0, old total cases: 70350.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    319.0
Freq: D, dtype: float64
new total cases: 71081.0, old total cases: 70669.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    412.0
Freq: D, dtype: float64
new total cases: 71346.0, old total cases: 71081.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    265.0
Freq: D, dtype: float64
new total cases: 71740.0, old total cases: 71346.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    394.0
Freq: D, dtype: float64
new total cases: 72020.0, old total cases: 71740.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    280.0
Freq: D, dtype: float64
new total cases: 72500.0, old total cases: 72020.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    480.0
Freq: D, dtype: float64
new total cases: 72913.0, old total cases: 72500.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    413.0
Freq: D, dtype: float64
new total cases: 73164.0, old total cases: 72913.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    251.0
Freq: D, dtype: float64
new total cases: 73384.0, old total cases: 73164.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    220.0
Freq: D, dtype: float64
new total cases: 73823.0, old total cases: 73384.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    439.0
Freq: D, dtype: float64
new total cases: 74182.0, old total cases: 73823.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    359.0
Freq: D, dtype: float64
new total cases: 74327.0, old total cases: 74182.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    145.0
Freq: D, dtype: float64
new total cases: 74778.0, old total cases: 74327.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    451.0
Freq: D, dtype: float64
new total cases: 75088.0, old total cases: 74778.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    310.0
Freq: D, dtype: float64
new total cases: 75547.0, old total cases: 75088.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    459.0
Freq: D, dtype: float64
new total cases: 75864.0, old total cases: 75547.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    317.0
Freq: D, dtype: float64
new total cases: 76203.0, old total cases: 75864.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    339.0
Freq: D, dtype: float64
new total cases: 76925.0, old total cases: 76203.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    361.0
2017-09-30    361.0
Freq: D, dtype: float64
new total cases: 77215.0, old total cases: 76925.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    290.0
Freq: D, dtype: float64
new total cases: 77215.0, old total cases: 77215.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 77835.0, old total cases: 77215.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    620.0
Freq: D, dtype: float64
new total cases: 78238.0, old total cases: 77835.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    403.0
Freq: D, dtype: float64
new total cases: 78522.0, old total cases: 78238.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    284.0
Freq: D, dtype: float64
new total cases: 78898.0, old total cases: 78522.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    125.333333
2017-10-07    125.333333
2017-10-08    125.333333
Freq: D, dtype: float64
new total cases: 79550.0, old total cases: 78898.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    652.0
Freq: D, dtype: float64
new total cases: 79551.0, old total cases: 79550.0

new total cases: 584.0, old total cases: 583.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    1.0
Freq: D, dtype: float64
new total cases: 584.0, old total cases: 584.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    0.0
Freq: D, dtype: float64
new total cases: 614.0, old total cases: 584.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    30.0
Freq: D, dtype: float64
new total cases: 616.0, old total cases: 614.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    2.0
Freq: D, dtype: float64
new total cases: 617.0, old total cases: 616.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    1.0
Freq: D, dtype: float64
new total cases: 646.0, old total cases: 617.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    29.0
Freq: D, dtype: float64
new total cases: 647.0, old total cases: 646.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    1.0
Freq: D, dtype: float64
new total cases: 647.0, old total cases: 647.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    0.0
Freq: D, dtype: float64
new total cases: 647.0, old total cases: 647.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    0.0
Freq: D, dtype: float64
new total cases: 655.0, old total cases: 647.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    4.0
2017-08-26    4.0
Freq: D, dtype: float64
new total cases: 678.0, old total cases: 655.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    23.0
Freq: D, dtype: float64
new total cases: 705.0, old total cases: 678.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    27.0
Freq: D, dtype: float64
new total cases: 707.0, old total cases: 705.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    2.0
Freq: D, dtype: float64
new total cases: 707.0, old total cases: 707.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    0.0
Freq: D, dtype: float64
new total cases: 727.0, old total cases: 707.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    20.0
Freq: D, dtype: float64
new total cases: 727.0, old total cases: 727.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    0.0
Freq: D, dtype: float64
new total cases: 743.0, old total cases: 727.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    16.0
Freq: D, dtype: float64
new total cases: 743.0, old total cases: 743.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    0.0
Freq: D, dtype: float64
new total cases: 743.0, old total cases: 743.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    0.0
Freq: D, dtype: float64
new total cases: 818.0, old total cases: 743.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    75.0
Freq: D, dtype: float64
new total cases: 962.0, old total cases: 818.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    144.0
Freq: D, dtype: float64
new total cases: 1025.0, old total cases: 962.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    63.0
Freq: D, dtype: float64
new total cases: 1025.0, old total cases: 1025.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    0.0
Freq: D, dtype: float64
new total cases: 1025.0, old total cases: 1025.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    0.0
Freq: D, dtype: float64
new total cases: 1084.0, old total cases: 1025.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    59.0
Freq: D, dtype: float64
new total cases: 1111.0, old total cases: 1084.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    27.0
Freq: D, dtype: float64
new total cases: 1150.0, old total cases: 1111.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    39.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1150.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    14.0
Freq: D, dtype: float64
new total cases: 1164.0, old total cases: 1164.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    0.0
Freq: D, dtype: float64
new total cases: 1185.0, old total cases: 1164.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    21.0
Freq: D, dtype: float64
new total cases: 1198.0, old total cases: 1185.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    13.0
Freq: D, dtype: float64
new total cases: 1198.0, old total cases: 1198.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    0.0
Freq: D, dtype: float64
new total cases: 1208.0, old total cases: 1198.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    10.0
Freq: D, dtype: float64
new total cases: 1210.0, old total cases: 1208.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    2.0
Freq: D, dtype: float64
new total cases: 1210.0, old total cases: 1210.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    0.0
Freq: D, dtype: float64
new total cases: 1211.0, old total cases: 1210.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    1.0
Freq: D, dtype: float64
new total cases: 1240.0, old total cases: 1211.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    29.0
Freq: D, dtype: float64
new total cases: 1242.0, old total cases: 1240.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    2.0
Freq: D, dtype: float64
new total cases: 1242.0, old total cases: 1242.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    0.0
Freq: D, dtype: float64
new total cases: 1243.0, old total cases: 1242.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    1.0
Freq: D, dtype: float64
new total cases: 1245.0, old total cases: 1243.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    2.0
Freq: D, dtype: float64
new total cases: 1245.0, old total cases: 1245.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    0.0
Freq: D, dtype: float64
new total cases: 1246.0, old total cases: 1245.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    1.0
Freq: D, dtype: float64
new total cases: 1293.0, old total cases: 1246.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    23.5
2017-09-30    23.5
Freq: D, dtype: float64
new total cases: 1298.0, old total cases: 1293.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    5.0
Freq: D, dtype: float64
new total cases: 1298.0, old total cases: 1298.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 1324.0, old total cases: 1298.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    26.0
Freq: D, dtype: float64
new total cases: 1324.0, old total cases: 1324.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    0.0
Freq: D, dtype: float64
new total cases: 1326.0, old total cases: 1324.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    2.0
Freq: D, dtype: float64
new total cases: 1328.0, old total cases: 1326.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    0.666667
2017-10-07    0.666667
2017-10-08    0.666667
Freq: D, dtype: float64
new total cases: 1333.0, old total cases: 1328.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    5.0
Freq: D, dtype: float64
new total cases: 1341.0, old total cases: 1333.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    8.0
Freq: D, dtype: float64
new total cases: 1344.0, old total cases: 1341.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    3.0
Freq: D, dtype: float64
new total cases: 1370.0, old total cases: 1344.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    8.666667
2017-10-13    8.666667
2017-10-14    8.666667
Freq: D, dtype: float64
new total cases: 1370.0, old total cases: 1370.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    0.0
2017-10-16    0.0
Freq: D, dtype: float64
new total cases: 1372.0, old total cases: 1370.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    2.0
Freq: D, dtype: float64
new total cases: 1381.0, old total cases: 1372.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    2.25
2017-10-19    2.25
2017-10-20    2.25
2017-10-21    2.25
Freq: D, dtype: float64
new total cases: 1381.0, old total cases: 1381.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    0.0
Freq: D, dtype: float64
new total cases: 1384.0, old total cases: 1381.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    1.0
2017-10-24    1.0
2017-10-25    1.0
Freq: D, dtype: float64
new total cases: 1384.0, old total cases: 1384.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    0.0
2017-10-27    0.0
2017-10-28    0.0
Freq: D, dtype: float64
new total cases: 1384.0, old total cases: 1384.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    0.0
Freq: D, dtype: float64
new total cases: 1384.0, old total cases: 1384.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    0.0
Freq: D, dtype: float64
new total cases: 1389.0, old total cases: 1384.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    1.25
2017-11-01    1.25
2017-11-02    1.25
2017-11-03    1.25
Freq: D, dtype: float64
new total cases: 1389.0, old total cases: 1389.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    0.0
Freq: D, dtype: float64
new total cases: 1389.0, old total cases: 1389.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    0.0
Freq: D, dtype: float64
new total cases: 1390.0, old total cases: 1389.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    1.0
Freq: D, dtype: float64
new total cases: 1390.0, old total cases: 1390.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    0.0
Freq: D, dtype: float64
new total cases: 1390.0, old total cases: 1390.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    0.0
Freq: D, dtype: float64
new total cases: 1392.0, old total cases: 1390.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    0.181818
2017-11-10    0.181818
2017-11-11    0.181818
2017-11-12    0.181818
2017-11-13    0.181818
2017-11-14    0.181818
2017-11-15    0.181818
2017-11-16    0.181818
2017-11-17    0.181818
2017-11-18    0.181818
2017-11-19    0.181818
Freq: D, dtype: float64
new total cases: 1396.0, old total cases: 1392.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    0.571429
2017-11-21    0.571429
2017-11-22    0.571429
2017-11-23    0.571429
2017-11-24    0.571429
2017-11-25    0.571429
2017-11-26    0.571429
Freq: D, dtype: float64
new total cases: 1397.0, old total cases: 1396.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    0.047619
2017-11-28    0.047619
2017-11-29    0.047619
2017-11-30    0.047619
2017-12-01    0.047619
2017-12-02    0.047619
2017-12-03    0.047619
2017-12-04    0.047619
2017-12-05    0.047619
2017-12-06    0.047619
2017-12-07    0.047619
2017-12-08    0.047619
2017-12-09    0.047619
2017-12-10    0.047619
2017-12-11    0.047619
2017-12-12    0.047619
2017-12-13    0.047619
2017-12-14    0.047619
2017-12-15    0.047619
2017-12-16    0.047619
2017-12-17    0.047619
Freq: D, dtype: float64
new total cases: 1399.0, old total cases: 1397.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    0.142857
2017-12-19    0.142857
2017-12-20    0.142857
2017-12-21    0.142857
2017-12-22    0.142857
2017-12-23    0.142857
2017-12-24    0.142857
2017-12-25    0.142857
2017-12-26    0.142857
2017-12-27    0.142857
2017-12-28    0.142857
2017-12-29    0.142857
2017-12-30    0.142857
2017-12-31    0.142857
Freq: D, dtype: float64
new total cases: 1399.0, old total cases: 1399.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    0.0
2018-01-02    0.0
2018-01-03    0.0
2018-01-04    0.0
2018-01-05    0.0
2018-01-06    0.0
2018-01-07    0.0
Freq: D, dtype: float64
new total cases: 1399.0, old total cases: 1399.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    0.0
2018-01-09    0.0
2018-01-10    0.0
2018-01-11    0.0
2018-01-12    0.0
2018-01-13    0.0
2018-01-14    0.0
Freq: D, dtype: float64
new total cases: 1399.0, old total cases: 1399.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    0.0
2018-01-16    0.0
2018-01-17    0.0
2018-01-18    0.0
2018-01-19    0.0
2018-01-20    0.0
2018-01-21    0.0
Freq: D, dtype: float64
new total cases: 1399.0, old total cases: 1399.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    0.0
2018-01-23    0.0
2018-01-24    0.0
2018-01-25    0.0
2018-01-26    0.0
2018-01-27    0.0
2018-01-28    0.0
Freq: D, dtype: float64
new total cases: 1399.0, old total cases: 1399.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    0.0
2018-01-30    0.0
2018-01-31    0.0
2018-02-01    0.0
2018-02-02    0.0
2018-02-03    0.0
2018-02-04    0.0
Freq: D, dtype: float64
new total cases: 1399.0, old total cases: 1399.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    0.0
2018-02-06    0.0
2018-02-07    0.0
2018-02-08    0.0
2018-02-09    0.0
2018-02-10    0.0
2018-02-11    0.0
Freq: D, dtype: float64
new total cases: 1399.0, old total cases: 1399.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    0.0
2018-02-13    0.0
2018-02-14    0.0
2018-02-15    0.0
2018-02-16    0.0
2018-02-17    0.0
2018-02-18    0.0
Freq: D, dtype: float64
new total cases: 5383.0, old total cases: 3815.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    313.6
2017-05-24    313.6
2017-05-25    313.6
2017-05-26    313.6
2017-05-27    313.6
Freq: D, dtype: float64
new total cases: 6224.0, old total cases: 5383.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    280.333333
2017-05-29    280.333333
2017-05-30    280.333333
Freq: D, dtype: float64
new total cases: 7992.0, old total cases: 6224.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    353.6
2017-06-01    353.6
2017-06-02    353.6
2017-06-03    353.6
2017-06-04    353.6
Freq: D, dtype: float64
new total cases: 9194.0, old total cases: 7992.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    400.666667
2017-06-06    400.666667
2017-06-07    400.666667
Freq: D, dtype: float64
new total cases: 10963.0, old total cases: 9194.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    589.666667
2017-06-09    589.666667
2017-06-10    589.666667
Freq: D, dtype: float64
new total cases: 11142.0, old total cases: 10963.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    89.5
2017-06-12    89.5
Freq: D, dtype: float64
new total cases: 11836.0, old total cases: 11142.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    694.0
Freq: D, dtype: float64
new total cases: 12225.0, old total cases: 11836.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    389.0
Freq: D, dtype: float64
new total cases: 13690.0, old total cases: 12225.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    488.333333
2017-06-16    488.333333
2017-06-17    488.333333
Freq: D, dtype: float64
new total cases: 14149.0, old total cases: 13690.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    459.0
Freq: D, dtype: float64
new total cases: 14646.0, old total cases: 14149.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    497.0
Freq: D, dtype: float64
new total cases: 15040.0, old total cases: 14646.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    394.0
Freq: D, dtype: float64
new total cases: 15251.0, old total cases: 15040.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    211.0
Freq: D, dtype: float64
new total cases: 16155.0, old total cases: 15251.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    904.0
Freq: D, dtype: float64
new total cases: 16641.0, old total cases: 16155.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    486.0
Freq: D, dtype: float64
new total cases: 17134.0, old total cases: 16641.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    493.0
Freq: D, dtype: float64
new total cases: 17418.0, old total cases: 17134.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    284.0
Freq: D, dtype: float64
new total cases: 18145.0, old total cases: 17418.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    727.0
Freq: D, dtype: float64
new total cases: 18672.0, old total cases: 18145.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    527.0
Freq: D, dtype: float64
new total cases: 19130.0, old total cases: 18672.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    458.0
Freq: D, dtype: float64
new total cases: 19898.0, old total cases: 19130.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    768.0
Freq: D, dtype: float64
new total cases: 20361.0, old total cases: 19898.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    463.0
Freq: D, dtype: float64
new total cases: 20546.0, old total cases: 20361.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    185.0
Freq: D, dtype: float64
new total cases: 21157.0, old total cases: 20546.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    611.0
Freq: D, dtype: float64
new total cases: 21831.0, old total cases: 21157.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    674.0
Freq: D, dtype: float64
new total cases: 22242.0, old total cases: 21831.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    411.0
Freq: D, dtype: float64
new total cases: 22651.0, old total cases: 22242.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    409.0
Freq: D, dtype: float64
new total cases: 23017.0, old total cases: 22651.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    366.0
Freq: D, dtype: float64
new total cases: 23261.0, old total cases: 23017.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    244.0
Freq: D, dtype: float64
new total cases: 23971.0, old total cases: 23261.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    236.666667
2017-07-09    236.666667
2017-07-10    236.666667
Freq: D, dtype: float64
new total cases: 24360.0, old total cases: 23971.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    389.0
Freq: D, dtype: float64
new total cases: 24665.0, old total cases: 24360.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    305.0
Freq: D, dtype: float64
new total cases: 24846.0, old total cases: 24665.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    181.0
Freq: D, dtype: float64
new total cases: 24957.0, old total cases: 24846.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    111.0
Freq: D, dtype: float64

In [12]:
yemen_cholera_case_data_diff

,YE-AB,YE-AD,YE-AM,YE-BA,YE-DA,YE-DH,YE-HD,YE-HJ,YE-HU,YE-IB,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
2017-05-23,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,NaN,263.200000,213.200000,159.800000,...,32.000000,11.400000,NaN,221.600000,42.400000,665.600000,NaN,NaN,313.600000,320.600000
2017-05-24,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,NaN,263.200000,213.200000,159.800000,...,32.000000,11.400000,NaN,221.600000,42.400000,665.600000,NaN,NaN,313.600000,320.600000
2017-05-25,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,NaN,263.200000,213.200000,159.800000,...,32.000000,11.400000,NaN,221.600000,42.400000,665.600000,NaN,NaN,313.600000,320.600000
2017-05-26,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,NaN,263.200000,213.200000,159.800000,...,32.000000,11.400000,NaN,221.600000,42.400000,665.600000,NaN,NaN,313.600000,320.600000
2017-05-27,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,NaN,263.200000,213.200000,159.800000,...,32.000000,11.400000,NaN,221.600000,42.400000,665.600000,NaN,NaN,313.600000,320.600000
2017-05-28,74.000000,126.000000,335.000000,200.000000,150.666667,175.333333,NaN,387.666667,1467.333333,130.000000,...,47.666667,18.333333,NaN,217.333333,47.000000,385.333333,6.666667,1.0,280.333333,335.000000
2017-05-29,74.000000,126.000000,335.000000,200.000000,150.666667,175.333333,NaN,387.666667,1467.333333,130.000000,...,47.666667,18.333333,NaN,217.333333,47.000000,385.333333,6.666667,1.0,280.333333,335.000000
2017-05-30,74.000000,126.000000,335.000000,200.000000,150.666667,175.333333,NaN,387.666667,1467.333333,130.000000,...,47.666667,18.333333,NaN,217.333333,47.000000,385.333333,6.666667,1.0,280.333333,335.000000
2017-05-31,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,NaN,544.200000,493.000000,341.400000,...,9.800000,7.400000,NaN,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
2017-06-01,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,NaN,544.200000,493.000000,341.400000,...,9.800000,7.400000,NaN,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
2017-06-02,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,NaN,544.200000,493.000000,341.400000,...,9.800000,7.400000,NaN,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
2017-06-03,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,NaN,544.200000,493.000000,341.400000,...,9.800000,7.400000,NaN,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
2017-06-04,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,NaN,544.200000,493.000000,341.400000,...,9.800000,7.400000,NaN,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
2017-06-05,83.666667,0.333333,541.333333,137.666667,208.666667,261.666667,NaN,453.333333,599.333333,589.000000,...,68.000000,31.333333,NaN,227.333333,128.000000,833.666667,2.333333,0.0,400.666667,539.666667
2017-06-06,83.666667,0.333333,541.333333,137.666667,208.666667,261.666667,NaN,453.333333,599.333333,589.000000,...,68.000000,31.333333,NaN,227.333333,128.000000,833.666667,2.333333,0.0,400.666667,539.666667
2017-06-07,83.666667,0.333333,541.333333,137.666667,208.666667,261.666667,NaN,453.333333,599.333333,589.000000,...,68.000000,31.333333,NaN,227.333333,128.000000,833.666667,2.333333,0.0,400.666667,539.666667
2017-06-08,103.000000,229.000000,674.666667,227.666667,424.000000,395.333333,NaN,685.000000,993.000000,860.666667,...,106.000000,16.666667,NaN,310.000000,191.333333,883.666667,3.666667,2.0,589.666667,648.333333
2017-06-09,103.000000,229.000000,674.666667,227.666667,424.000000,395.333333,NaN,685.000000,993.000000,860.666667,...,106.000000,16.666667,NaN,310.000000,191.333333,883.666667,3.666667,2.0,589.666667,648.333333
2017-06-10,103.000000,229.000000,674.666667,227.666667,424.000000,395.333333,NaN,685.000000,993.000000,860.666667,...,106.000000,16.666667,NaN,310.000000,191.333333,883.666667,3.666667,2.0,589.666667,648.333333
2017-06-11,65.500000,0.000000,340.000000,57.500000,78.500000,141.500000,NaN,173.500000,311.000000,433.500000,...,98.500000,12.000000,0.000000,139.500000,79.000000,287.500000,1.000000,0.0,89.500000,269.500000
2017-06-12,65.500000,0.000000,340.000000,57.500000,78.500000,141.500000,NaN,173.500000,311.000000,433.500000,...,98.500000,12.000000,0.000000,139.500000,79.000000,287.500000,1.000000,0.0,89.500000,269.500000
2017-06-13,64.000000,0.000000,522.000000,199.000000,173.000000,241.000000,NaN,827.000000,913.000000,506.000000,...,2.000000,16.000000,24.000000,229.000000,24.000000,548.000000,0.000000,0.0,694.000000,999.000000
2017-06-14,96.000000,1.000000,587.000000,230.000000,77.000000,292.000000,NaN,13.000000,825.000000,327.000000,...,235.000000,22.000000,8.000000,181.000000,265.000000,775.000000,1.000000,0.0,389.000000,554.000000
2017-06-15,107.666667,278.333333,631.666667,162.000000,297.333333,411.666667,NaN,729.666667,904.666667,529.333333,...,36.666667,16.666667,7.333333,240.000000,47.333333,896.666667,6.333333,0.0,488.333333,463.666667
2017-06-16,107.666667,278.333333,631.666667,162.000000,297.333333,411.666667,NaN,729.666667,904.666667,529.333333,...,36.666667,16.666667,7.333333,240.000000,47.333333,896.666667,6.333333,0.0,488.333333,463.666667
2017-06-17,107.666667,278.333333,631.666667,162.000000,297.333333,411.666667,NaN,729.666667,904.666667,529.333333,...,36.666667,16.666667,7.333333,240.000000,47.333333,896.666667,6.333333,0.0,488.333333,463.666667
2017-06-18,100.000000,215.000000,729.000000,0.000000,803.000000,407.000000,NaN,776.000000,1001.000000,921.000000,...,314.000000,49.000000,10.000000,287.000000,331.000000,1008.000000,5.000000,17.0,459.000000,539.000000
2017-06-19,110.000000,354.000000,750.000000,122.000000,239.000000,413.000000,NaN,8.000000,843.000000,551.000000,...,25.000000,29.000000,13.000000,294.000000,5.000000,691.000000,1.000000,12.0,497.000000,338.000000
2017-06-20,1.000000,219.000000,836.000000,2.000000,160.000000,438.000000,NaN,1276.000000,913.000000,482.000000,...,213.000000,0.000000,16.000000,98.000000,175.000000,1404.000000,1.000000,4.0,394.000000,581.000000
2017-06-21,4.000000,198.000000,818.000000,416.000000,381.000000,475.000000,NaN,236.000000,956.000000,223.000000,...,9.000000,32.000000,12.000000,252.000000,107.000000,949.000000,45.000000,0.0,211.000000,400.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-01-20,0.000000,2.714286,98.000000,77.000000,0.000000,153.714286,0.000000,398.000000,232.428571,114.714286,...,0.000000,0.000000,0.000000,66.714286,64.285714,163.428571,0.285714,0.0,96.857143,97.000000
2018-01-21,0.000000,2.714286,98.000000,77.000000,0.000000,153.714286,0.000000,398.000000,232.428571,114.714286,...,0.000000,0.000000,0.000000,66.714286,64.285714,163.428571,0.285714,0.0,96.857143,97.000000
2018-01-22,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-23,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-24,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-25,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-26,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-27,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-28,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-29,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-01-30,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-01-31,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-02-01,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-02-02,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-02-03,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-02-04,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-02-05,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-06,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-07,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-08,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-09,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-10,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-11,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-12,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-13,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-14,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-15,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-16,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-17,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-18,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143

In [13]:
yemen_cholera_death_data_diff = pd.DataFrame()
for column in yemen_cholera_death_data_crosstab:
    yemen_cholera_death_data_diff[column]  = (difference(yemen_cholera_death_data_crosstab[column]))

new total cases: 15.0, old total cases: 10.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    1.0
2017-05-24    1.0
2017-05-25    1.0
2017-05-26    1.0
2017-05-27    1.0
Freq: D, dtype: float64
new total cases: 16.0, old total cases: 15.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    0.333333
2017-05-29    0.333333
2017-05-30    0.333333
Freq: D, dtype: float64
new total cases: 16.0, old total cases: 16.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    0.0
2017-06-01    0.0
2017-06-02    0.0
2017-06-03    0.0
2017-06-04    0.0
Freq: D, dtype: float64
new total cases: 17.0, old total cases: 16.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    0.333333
2017-06-06    0.333333
2017-06-07    0.333333
Freq: D, dtype: float64
new total cases: 21.0, old total cases: 17.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    1.333333
2017-06-09    1.333333
2017-06-10    1.333333
Freq: D, dtype: float64
new total cases: 21.0, old total cases: 21.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    0.0
2017-06-12    0.0
Freq: D, dtype: float64
new total cases: 21.0, old total cases: 21.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    0.0
Freq: D, dtype: float64
new total cases: 21.0, old total cases: 21.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    0.0
Freq: D, dtype: float64
new total cases: 21.0, old total cases: 21.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    0.0
2017-06-16    0.0
2017-06-17    0.0
Freq: D, dtype: float64
new total cases: 21.0, old total cases: 21.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    0.0
Freq: D, dtype: float64
new total cases: 21.0, old total cases: 21.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    0.0
Freq: D, dtype: float64
new total cases: 21.0, old total cases: 21.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    0.0
Freq: D, dtype: float64
new total cases: 21.0, old total cases: 21.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    0.0
Freq: D, dtype: float64
new total cases: 21.0, old total cases: 21.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    0.0
Freq: D, dtype: float64
new total cases: 21.0, old total cases: 21.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    0.0
Freq: D, dtype: float64
new total cases: 22.0, old total cases: 21.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    1.0
Freq: D, dtype: float64
new total cases: 22.0, old total cases: 22.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    0.0
Freq: D, dtype: float64
new total cases: 22.0, old total cases: 22.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    0.0
Freq: D, dtype: float64
new total cases: 22.0, old total cases: 22.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    0.0
Freq: D, dtype: float64
new total cases: 22.0, old total cases: 22.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    0.0
Freq: D, dtype: float64
new total cases: 22.0, old total cases: 22.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    0.0
Freq: D, dtype: float64
new total cases: 23.0, old total cases: 22.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    1.0
Freq: D, dtype: float64
new total cases: 24.0, old total cases: 23.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    1.0
Freq: D, dtype: float64
new total cases: 25.0, old total cases: 24.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    1.0
Freq: D, dtype: float64
new total cases: 27.0, old total cases: 25.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    2.0
Freq: D, dtype: float64
new total cases: 27.0, old total cases: 27.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    0.0
Freq: D, dtype: float64
new total cases: 27.0, old total cases: 27.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    0.0
Freq: D, dtype: float64
new total cases: 27.0, old total cases: 27.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    0.0
Freq: D, dtype: float64
new total cases: 27.0, old total cases: 27.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    0.0
Freq: D, dtype: float64
new total cases: 27.0, old total cases: 27.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    0.0
2017-07-09    0.0
2017-07-10    0.0
Freq: D, dtype: float64
new total cases: 28.0, old total cases: 27.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    1.0
Freq: D, dtype: float64
new total cases: 29.0, old total cases: 28.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    1.0
Freq: D, dtype: float64
new total cases: 30.0, old total cases: 29.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    1.0
Freq: D, dtype: float64
new total cases: 31.0, old total cases: 30.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    1.0
Freq: D, dtype: float64
new total cases: 31.0, old total cases: 31.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    0.0
Freq: D, dtype: float64
new total cases: 31.0, old total cases: 31.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    0.0
Freq: D, dtype: float64
new total cases: 31.0, old total cases: 31.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    0.0
Freq: D, dtype: float64
new total cases: 31.0, old total cases: 31.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    0.0
Freq: D, dtype: float64
new total cases: 31.0, old total cases: 31.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    0.0
Freq: D, dtype: float64
new total cases: 31.0, old total cases: 31.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    0.0
Freq: D, dtype: float64
new total cases: 31.0, old total cases: 31.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    0.0
Freq: D, dtype: float64
new total cases: 32.0, old total cases: 31.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    1.0
Freq: D, dtype: float64
new total cases: 32.0, old total cases: 32.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    0.0
Freq: D, dtype: float64
new total cases: 32.0, old total cases: 32.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    0.0
Freq: D, dtype: float64
new total cases: 32.0, old total cases: 32.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    0.0
Freq: D, dtype: float64
new total cases: 32.0, old total cases: 32.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    0.0
Freq: D, dtype: float64
new total cases: 32.0, old total cases: 32.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    0.0
Freq: D, dtype: float64
new total cases: 32.0, old total cases: 32.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    0.0
Freq: D, dtype: float64
new total cases: 32.0, old total cases: 32.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    0.0
Freq: D, dtype: float64
new total cases: 32.0, old total cases: 32.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    0.0
Freq: D, dtype: float64
new total cases: 33.0, old total cases: 32.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    1.0
Freq: D, dtype: float64
new total cases: 33.0, old total cases: 33.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    0.0
Freq: D, dtype: float64
new total cases: 33.0, old total cases: 33.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    0.0
2017-08-03    0.0
Freq: D, dtype: float64
new total cases: 33.0, old total cases: 33.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    0.0
2017-08-05    0.0
2017-08-06    0.0
Freq: D, dtype: float64
new total cases: 33.0, old total cases: 33.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    0.0
2017-08-08    0.0
2017-08-09    0.0
2017-08-10    0.0
2017-08-11    0.0
2017-08-12    0.0
2017-08-13    0.0
Freq: D, dtype: float64
new total cases: 33.0, old total cases: 33.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    0.0
2017-08-15    0.0
Freq: D, dtype: float64
new total cases: 34.0, old total cases: 33.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    1.0
Freq: D, dtype: float64
new total cases: 34.0, old total cases: 34.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    0.0
Freq: D, dtype: float64
new total cases: 34.0, old total cases: 34.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    0.0
Freq: D, dtype: float64
new total cases: 34.0, old total cases: 34.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    0.0
Freq: D, dtype: float64
new total cases: 34.0, old total cases: 34.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    0.0
Freq: D, dtype: float64
new total cases: 34.0, old total cases: 34.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 34.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    1.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    0.0
2017-08-26    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    0.0
2017-09-30    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    0.0
2017-10-07    0.0
2017-10-08    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    0.0
2017-10-13    0.0
2017-10-14    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    0.0
2017-10-16    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    0.0
2017-10-19    0.0
2017-10-20    0.0
2017-10-21    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    0.0
2017-10-24    0.0
2017-10-25    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    0.0
2017-10-27    0.0
2017-10-28    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    0.0
2017-11-01    0.0
2017-11-02    0.0
2017-11-03    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    0.0
2017-11-10    0.0
2017-11-11    0.0
2017-11-12    0.0
2017-11-13    0.0
2017-11-14    0.0
2017-11-15    0.0
2017-11-16    0.0
2017-11-17    0.0
2017-11-18    0.0
2017-11-19    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    0.0
2017-11-21    0.0
2017-11-22    0.0
2017-11-23    0.0
2017-11-24    0.0
2017-11-25    0.0
2017-11-26    0.0
Freq: D, dtype: float64
new total cases: 35.0, old total cases: 35.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    0.0
2017-11-28    0.0
2017-11-29    0.0
2017-11-30    0.0

new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    0.666667
2017-07-09    0.666667
2017-07-10    0.666667
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 149.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    0.0
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 149.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    0.0
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 149.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    0.0
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 149.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    0.0
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 149.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    0.0
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 149.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    0.0
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 149.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 149.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    1.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    0.0
Freq: D, dtype: float64
new total cases: 150.0, old total cases: 150.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    0.0
Freq: D, dtype: float64
new total cases: 151.0, old total cases: 150.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    1.0
Freq: D, dtype: float64
new total cases: 151.0, old total cases: 151.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    0.0
2017-08-03    0.0
Freq: D, dtype: float64
new total cases: 151.0, old total cases: 151.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    0.0
2017-08-05    0.0
2017-08-06    0.0
Freq: D, dtype: float64
new total cases: 153.0, old total cases: 151.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    0.285714
2017-08-08    0.285714
2017-08-09    0.285714
2017-08-10    0.285714
2017-08-11    0.285714
2017-08-12    0.285714
2017-08-13    0.285714
Freq: D, dtype: float64
new total cases: 153.0, old total cases: 153.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    0.0
2017-08-15    0.0
Freq: D, dtype: float64
new total cases: 153.0, old total cases: 153.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    0.0
Freq: D, dtype: float64
new total cases: 154.0, old total cases: 153.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    1.0
Freq: D, dtype: float64
new total cases: 154.0, old total cases: 154.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    0.0
Freq: D, dtype: float64
new total cases: 154.0, old total cases: 154.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    0.0
Freq: D, dtype: float64
new total cases: 154.0, old total cases: 154.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    0.0
Freq: D, dtype: float64
new total cases: 154.0, old total cases: 154.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    0.0
Freq: D, dtype: float64
new total cases: 155.0, old total cases: 154.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    1.0
Freq: D, dtype: float64
new total cases: 155.0, old total cases: 155.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    0.0
Freq: D, dtype: float64
new total cases: 156.0, old total cases: 155.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    1.0
Freq: D, dtype: float64
new total cases: 156.0, old total cases: 156.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    0.0
2017-08-26    0.0
Freq: D, dtype: float64
new total cases: 157.0, old total cases: 156.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    1.0
Freq: D, dtype: float64
new total cases: 157.0, old total cases: 157.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    0.0
Freq: D, dtype: float64
new total cases: 158.0, old total cases: 157.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    1.0
Freq: D, dtype: float64
new total cases: 159.0, old total cases: 158.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    1.0
Freq: D, dtype: float64
new total cases: 159.0, old total cases: 159.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    0.0
Freq: D, dtype: float64
new total cases: 159.0, old total cases: 159.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    0.0
Freq: D, dtype: float64
new total cases: 159.0, old total cases: 159.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    0.0
Freq: D, dtype: float64
new total cases: 159.0, old total cases: 159.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    0.0
Freq: D, dtype: float64
new total cases: 159.0, old total cases: 159.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    0.0
Freq: D, dtype: float64
new total cases: 160.0, old total cases: 159.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    1.0
Freq: D, dtype: float64
new total cases: 160.0, old total cases: 160.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    0.0
Freq: D, dtype: float64
new total cases: 161.0, old total cases: 160.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    1.0
Freq: D, dtype: float64
new total cases: 161.0, old total cases: 161.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    0.0
Freq: D, dtype: float64
new total cases: 161.0, old total cases: 161.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    0.0
Freq: D, dtype: float64
new total cases: 161.0, old total cases: 161.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    0.0
Freq: D, dtype: float64
new total cases: 161.0, old total cases: 161.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    0.0
Freq: D, dtype: float64
new total cases: 161.0, old total cases: 161.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    0.0
Freq: D, dtype: float64
new total cases: 161.0, old total cases: 161.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    0.0
Freq: D, dtype: float64
new total cases: 161.0, old total cases: 161.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    0.0
Freq: D, dtype: float64
new total cases: 161.0, old total cases: 161.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    0.0
Freq: D, dtype: float64
new total cases: 162.0, old total cases: 161.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    1.0
Freq: D, dtype: float64
new total cases: 162.0, old total cases: 162.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    0.0
Freq: D, dtype: float64
new total cases: 163.0, old total cases: 162.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    1.0
Freq: D, dtype: float64
new total cases: 165.0, old total cases: 163.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    2.0
Freq: D, dtype: float64
new total cases: 166.0, old total cases: 165.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    1.0
Freq: D, dtype: float64
new total cases: 167.0, old total cases: 166.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    1.0
Freq: D, dtype: float64
new total cases: 167.0, old total cases: 167.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    0.0
Freq: D, dtype: float64
new total cases: 167.0, old total cases: 167.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    0.0
Freq: D, dtype: float64
new total cases: 167.0, old total cases: 167.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    0.0
Freq: D, dtype: float64
new total cases: 167.0, old total cases: 167.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    0.0
Freq: D, dtype: float64
new total cases: 167.0, old total cases: 167.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    0.0
Freq: D, dtype: float64
new total cases: 167.0, old total cases: 167.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    0.0
Freq: D, dtype: float64
new total cases: 167.0, old total cases: 167.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    0.0
Freq: D, dtype: float64
new total cases: 167.0, old total cases: 167.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    0.0
2017-09-30    0.0
Freq: D, dtype: float64
new total cases: 167.0, old total cases: 167.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    0.0
Freq: D, dtype: float64
new total cases: 167.0, old total cases: 167.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 168.0, old total cases: 167.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    1.0
Freq: D, dtype: float64
new total cases: 169.0, old total cases: 168.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    1.0
Freq: D, dtype: float64
new total cases: 169.0, old total cases: 169.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    0.0
Freq: D, dtype: float64
new total cases: 169.0, old total cases: 169.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    0.0
2017-10-07    0.0
2017-10-08    0.0
Freq: D, dtype: float64
new total cases: 169.0, old total cases: 169.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    0.0
Freq: D, dtype: float64
new total cases: 169.0, old total cases: 169.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    0.0
Freq: D, dtype: float64
new total cases: 169.0, old total cases: 169.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    0.0
Freq: D, dtype: float64
new total cases: 169.0, old total cases: 169.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    0.0
2017-10-13    0.0
2017-10-14    0.0
Freq: D, dtype: float64
new total cases: 169.0, old total cases: 169.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    0.0
2017-10-16    0.0
Freq: D, dtype: float64
new total cases: 169.0, old total cases: 169.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    0.0
Freq: D, dtype: float64
new total cases: 169.0, old total cases: 169.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    0.0
2017-10-19    0.0
2017-10-20    0.0
2017-10-21    0.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 169.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    1.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 170.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    0.0
2017-10-24    0.0
2017-10-25    0.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 170.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    0.0
2017-10-27    0.0
2017-10-28    0.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 170.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    0.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 170.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    0.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 170.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    0.0
2017-11-01    0.0
2017-11-02    0.0
2017-11-03    0.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 170.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    0.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 170.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    0.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 170.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    0.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 170.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    0.0
Freq: D, dtype: float64
new total cases: 170.0, old total cases: 170.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    0.0
Freq: D, dtype: float64
new total cases: 174.0, old total cases: 170.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    0.363636
2017-11-10    0.363636
2017-11-11    0.363636
2017-11-12    0.363636
2017-11-13    0.363636
2017-11-14    0.363636
2017-11-15    0.363636
2017-11-16    0.363636
2017-11-17    0.363636
2017-11-18    0.363636
2017-11-19    0.363636
Freq: D, dtype: float64
new total cases: 174.0, old total cases: 174.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    0.0
2017-11-21    0.0
2017-11-22    0.0
2017-11-23    0.0
2017-11-24    0.0
2017-11-25    0.0
2017-11-26    0.0
Freq: D, dtype: float64
new total cases: 174.0, old total cases: 174.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    0.0
2017-11-28    0.0
2017-11-29    0.0
2017-11-30    0.0
2017-12-01    0.0
2017-12-02    0.0
2017-12-03    0.0
2017-12-04    0.0
2017-12-05    0.0
2017-12-06    0.0
2017-12-07    0.0
2017-12-08    0.0
2017-12-09    0.0
2017-12-10    0.0
2017-12-11    0.0
2017-12-12    0.0
2017-12-13    0.0
2017-12-14    0.0
2017-12-15    0.0
2017-12-16    0.0
2017-12-17    0.0
Freq: D, dtype: float64
new total cases: 174.0, old total cases: 174.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    0.0
2017-12-19    0.0
2017-12-20    0.0
2017-12-21    0.0
2017-12-22    0.0
2017-12-23    0.0
2017-12-24    0.0
2017-12-25    0.0
2017-12-26    0.0
2017-12-27    0.0
2017-12-28    0.0
2017-12-29    0.0
2017-12-30    0.0
2017-12-31    0.0
Freq: D, dtype: float64
new total cases: 174.0, old total cases: 174.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    0.0
2018-01-02    0.0
2018-01-03    0.0
2018-01-04    0.0
2018-01-05    0.0
2018-01-06    0.0
2018-01-07    0.0
Freq: D, dtype: float64
new total cases: 175.0, old total cases: 174.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    0.142857
2018-01-09    0.142857
2018-01-10    0.142857
2018-01-11    0.142857
2018-01-12    0.142857
2018-01-13    0.142857
2018-01-14    0.142857
Freq: D, dtype: float64
new total cases: 175.0, old total cases: 175.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    0.0
2018-01-16    0.0
2018-01-17    0.0
2018-01-18    0.0
2018-01-19    0.0
2018-01-20    0.0
2018-01-21    0.0
Freq: D, dtype: float64
new total cases: 176.0, old total cases: 175.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    0.142857
2018-01-23    0.142857
2018-01-24    0.142857
2018-01-25    0.142857
2018-01-26    0.142857
2018-01-27    0.142857
2018-01-28    0.142857
Freq: D, dtype: float64
new total cases: 176.0, old total cases: 176.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    0.0
2018-01-30    0.0
2018-01-31    0.0
2018-02-01    0.0
2018-02-02    0.0
2018-02-03    0.0
2018-02-04    0.0
Freq: D, dtype: float64
new total cases: 176.0, old total cases: 176.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    0.0
2018-02-06    0.0
2018-02-07    0.0
2018-02-08    0.0
2018-02-09    0.0
2018-02-10    0.0
2018-02-11    0.0
Freq: D, dtype: float64
new total cases: 176.0, old total cases: 176.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    0.0
2018-02-13    0.0
2018-02-14    0.0
2018-02-15    0.0
2018-02-16    0.0
2018-02-17    0.0
2018-02-18    0.0
Freq: D, dtype: float64
new total cases: 8.0, old total cases: 6.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    0.4
2017-05-24    0.4
2017-05-25    0.4
2017-05-26    0.4
2017-05-27    0.4
Freq: D, dtype: float64
new total cases: 11.0, old total cases: 8.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    1.0
2017-05-29    1.0
2017-05-30    1.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 11.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    0.4
2017-06-01    0.4
2017-06-02    0.4
2017-06-03    0.4
2017-06-04    0.4
Freq: D, dtype: float64
new total cases: 14.0, old total cases: 13.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    0.333333
2017-06-06    0.333333
2017-06-07    0.333333
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 14.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    1.333333
2017-06-09    1.333333
2017-06-10    1.333333
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    0.0
2017-06-12    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    0.0
2017-06-16    0.0
2017-06-17    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    0.0

new total cases: 79.0, old total cases: 79.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    0.0
Freq: D, dtype: float64
new total cases: 79.0, old total cases: 79.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    0.0
Freq: D, dtype: float64
new total cases: 79.0, old total cases: 79.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    0.0
Freq: D, dtype: float64
new total cases: 79.0, old total cases: 79.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    0.0
2017-10-07    0.0
2017-10-08    0.0
Freq: D, dtype: float64
new total cases: 79.0, old total cases: 79.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    0.0
Freq: D, dtype: float64
new total cases: 79.0, old total cases: 79.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    0.0
Freq: D, dtype: float64
new total cases: 79.0, old total cases: 79.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    0.0
Freq: D, dtype: float64
new total cases: 79.0, old total cases: 79.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    0.0
2017-10-13    0.0
2017-10-14    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 79.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    0.5
2017-10-16    0.5
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    0.0
2017-10-19    0.0
2017-10-20    0.0
2017-10-21    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    0.0
2017-10-24    0.0
2017-10-25    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    0.0
2017-10-27    0.0
2017-10-28    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    0.0
2017-11-01    0.0
2017-11-02    0.0
2017-11-03    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 80.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    1.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    0.0
2017-11-10    0.0
2017-11-11    0.0
2017-11-12    0.0
2017-11-13    0.0
2017-11-14    0.0
2017-11-15    0.0
2017-11-16    0.0
2017-11-17    0.0
2017-11-18    0.0
2017-11-19    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    0.0
2017-11-21    0.0
2017-11-22    0.0
2017-11-23    0.0
2017-11-24    0.0
2017-11-25    0.0
2017-11-26    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    0.0
2017-11-28    0.0
2017-11-29    0.0
2017-11-30    0.0
2017-12-01    0.0
2017-12-02    0.0
2017-12-03    0.0
2017-12-04    0.0
2017-12-05    0.0
2017-12-06    0.0
2017-12-07    0.0
2017-12-08    0.0
2017-12-09    0.0
2017-12-10    0.0
2017-12-11    0.0
2017-12-12    0.0
2017-12-13    0.0
2017-12-14    0.0
2017-12-15    0.0
2017-12-16    0.0
2017-12-17    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    0.0
2017-12-19    0.0
2017-12-20    0.0
2017-12-21    0.0
2017-12-22    0.0
2017-12-23    0.0
2017-12-24    0.0
2017-12-25    0.0
2017-12-26    0.0
2017-12-27    0.0
2017-12-28    0.0
2017-12-29    0.0
2017-12-30    0.0
2017-12-31    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    0.0
2018-01-02    0.0
2018-01-03    0.0
2018-01-04    0.0
2018-01-05    0.0
2018-01-06    0.0
2018-01-07    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    0.0
2018-01-09    0.0
2018-01-10    0.0
2018-01-11    0.0
2018-01-12    0.0
2018-01-13    0.0
2018-01-14    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    0.0
2018-01-16    0.0
2018-01-17    0.0
2018-01-18    0.0
2018-01-19    0.0
2018-01-20    0.0
2018-01-21    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    0.0
2018-01-23    0.0
2018-01-24    0.0
2018-01-25    0.0
2018-01-26    0.0
2018-01-27    0.0
2018-01-28    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    0.0
2018-01-30    0.0
2018-01-31    0.0
2018-02-01    0.0
2018-02-02    0.0
2018-02-03    0.0
2018-02-04    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    0.0
2018-02-06    0.0
2018-02-07    0.0
2018-02-08    0.0
2018-02-09    0.0
2018-02-10    0.0
2018-02-11    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 81.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    0.0
2018-02-13    0.0
2018-02-14    0.0
2018-02-15    0.0
2018-02-16    0.0
2018-02-17    0.0
2018-02-18    0.0
Freq: D, dtype: float64
new total cases: 41.0, old total cases: 33.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    1.6
2017-05-24    1.6
2017-05-25    1.6
2017-05-26    1.6
2017-05-27    1.6
Freq: D, dtype: float64
new total cases: 44.0, old total cases: 41.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    1.0
2017-05-29    1.0
2017-05-30    1.0
Freq: D, dtype: float64
new total cases: 52.0, old total cases: 44.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    1.6
2017-06-01    1.6
2017-06-02    1.6
2017-06-03    1.6
2017-06-04    1.6
Freq: D, dtype: float64
new total cases: 55.0, old total cases: 52.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    1.0
2017-06-06    1.0
2017-06-07    1.0
Freq: D, dtype: float64
new total cases: 60.0, old total cases: 55.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    1.666667
2017-06-09    1.666667
2017-06-10    1.666667
Freq: D, dtype: float64
new total cases: 61.0, old total cases: 60.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    0.5
2017-06-12    0.5
Freq: D, dtype: float64
new total cases: 67.0, old total cases: 61.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    6.0
Freq: D, dtype: float64
new total cases: 69.0, old total cases: 67.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    2.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 69.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    3.666667
2017-06-16    3.666667
2017-06-17    3.666667
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 80.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    1.0
Freq: D, dtype: float64
new total cases: 84.0, old total cases: 81.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    3.0
Freq: D, dtype: float64
new total cases: 85.0, old total cases: 84.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    1.0
Freq: D, dtype: float64
new total cases: 86.0, old total cases: 85.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    1.0
Freq: D, dtype: float64
new total cases: 87.0, old total cases: 86.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    1.0
Freq: D, dtype: float64
new total cases: 90.0, old total cases: 87.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    3.0
Freq: D, dtype: float64
new total cases: 92.0, old total cases: 90.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    2.0
Freq: D, dtype: float64
new total cases: 92.0, old total cases: 92.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    0.0
Freq: D, dtype: float64
new total cases: 94.0, old total cases: 92.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    2.0
Freq: D, dtype: float64
new total cases: 96.0, old total cases: 94.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    2.0
Freq: D, dtype: float64
new total cases: 100.0, old total cases: 96.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    4.0
Freq: D, dtype: float64
new total cases: 100.0, old total cases: 100.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    0.0
Freq: D, dtype: float64
new total cases: 102.0, old total cases: 100.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    2.0
Freq: D, dtype: float64
new total cases: 106.0, old total cases: 102.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    4.0
Freq: D, dtype: float64
new total cases: 109.0, old total cases: 106.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    3.0
Freq: D, dtype: float64
new total cases: 109.0, old total cases: 109.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    0.0
Freq: D, dtype: float64
new total cases: 111.0, old total cases: 109.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    2.0
Freq: D, dtype: float64
new total cases: 112.0, old total cases: 111.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    1.0
Freq: D, dtype: float64
new total cases: 112.0, old total cases: 112.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    0.0
Freq: D, dtype: float64
new total cases: 113.0, old total cases: 112.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    1.0
Freq: D, dtype: float64
new total cases: 114.0, old total cases: 113.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    0.333333
2017-07-09    0.333333
2017-07-10    0.333333
Freq: D, dtype: float64
new total cases: 114.0, old total cases: 114.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    0.0
Freq: D, dtype: float64
new total cases: 114.0, old total cases: 114.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    0.0
Freq: D, dtype: float64
new total cases: 116.0, old total cases: 114.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    2.0
Freq: D, dtype: float64
new total cases: 117.0, old total cases: 116.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    1.0
Freq: D, dtype: float64
new total cases: 118.0, old total cases: 117.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    1.0
Freq: D, dtype: float64
new total cases: 119.0, old total cases: 118.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    1.0
Freq: D, dtype: float64
new total cases: 119.0, old total cases: 119.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    0.0
Freq: D, dtype: float64
new total cases: 124.0, old total cases: 119.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    5.0
Freq: D, dtype: float64
new total cases: 124.0, old total cases: 124.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    0.0
Freq: D, dtype: float64
new total cases: 126.0, old total cases: 124.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    2.0
Freq: D, dtype: float64
new total cases: 126.0, old total cases: 126.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    0.0
Freq: D, dtype: float64
new total cases: 126.0, old total cases: 126.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    0.0
Freq: D, dtype: float64
new total cases: 126.0, old total cases: 126.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    0.0
Freq: D, dtype: float64
new total cases: 126.0, old total cases: 126.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    0.0
Freq: D, dtype: float64
new total cases: 128.0, old total cases: 126.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    2.0
Freq: D, dtype: float64
new total cases: 129.0, old total cases: 128.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    1.0
Freq: D, dtype: float64
new total cases: 129.0, old total cases: 129.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    0.0
Freq: D, dtype: float64
new total cases: 130.0, old total cases: 129.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    1.0
Freq: D, dtype: float64
new total cases: 130.0, old total cases: 130.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    0.0
Freq: D, dtype: float64
new total cases: 131.0, old total cases: 130.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    1.0
Freq: D, dtype: float64
new total cases: 132.0, old total cases: 131.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    1.0
Freq: D, dtype: float64
new total cases: 132.0, old total cases: 132.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    0.0
Freq: D, dtype: float64
new total cases: 133.0, old total cases: 132.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    0.5
2017-08-03    0.5
Freq: D, dtype: float64
new total cases: 134.0, old total cases: 133.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    0.333333
2017-08-05    0.333333
2017-08-06    0.333333
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 134.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    0.857143
2017-08-08    0.857143
2017-08-09    0.857143
2017-08-10    0.857143
2017-08-11    0.857143
2017-08-12    0.857143
2017-08-13    0.857143
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    0.0
2017-08-15    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    0.0
Freq: D, dtype: float64
new total cases: 141.0, old total cases: 140.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    1.0
Freq: D, dtype: float64
new total cases: 141.0, old total cases: 141.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    0.0
Freq: D, dtype: float64
new total cases: 142.0, old total cases: 141.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    1.0
Freq: D, dtype: float64
new total cases: 142.0, old total cases: 142.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    0.0
Freq: D, dtype: float64
new total cases: 142.0, old total cases: 142.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    0.0
Freq: D, dtype: float64
new total cases: 142.0, old total cases: 142.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    0.0
Freq: D, dtype: float64
new total cases: 142.0, old total cases: 142.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    0.0
Freq: D, dtype: float64
new total cases: 143.0, old total cases: 142.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    0.5
2017-08-26    0.5
Freq: D, dtype: float64
new total cases: 144.0, old total cases: 143.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    1.0
Freq: D, dtype: float64
new total cases: 144.0, old total cases: 144.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    0.0
Freq: D, dtype: float64
new total cases: 144.0, old total cases: 144.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    0.0
Freq: D, dtype: float64
new total cases: 144.0, old total cases: 144.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 144.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    1.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    0.0
Freq: D, dtype: float64
new total cases: 146.0, old total cases: 145.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    1.0
Freq: D, dtype: float64
new total cases: 146.0, old total cases: 146.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    0.0
Freq: D, dtype: float64
new total cases: 146.0, old total cases: 146.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    0.0
Freq: D, dtype: float64
new total cases: 146.0, old total cases: 146.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    0.0
Freq: D, dtype: float64
new total cases: 146.0, old total cases: 146.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    0.0
Freq: D, dtype: float64
new total cases: 146.0, old total cases: 146.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    0.0
Freq: D, dtype: float64
new total cases: 146.0, old total cases: 146.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    0.0
Freq: D, dtype: float64

new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    6.0
Freq: D, dtype: float64
new total cases: 345.0, old total cases: 344.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    1.0
Freq: D, dtype: float64
new total cases: 345.0, old total cases: 345.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    0.0
Freq: D, dtype: float64
new total cases: 345.0, old total cases: 345.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    0.0
Freq: D, dtype: float64
new total cases: 346.0, old total cases: 345.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    1.0
Freq: D, dtype: float64
new total cases: 346.0, old total cases: 346.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    0.0
Freq: D, dtype: float64
new total cases: 353.0, old total cases: 346.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    7.0
Freq: D, dtype: float64
new total cases: 353.0, old total cases: 353.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    0.0
Freq: D, dtype: float64
new total cases: 355.0, old total cases: 353.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    2.0
Freq: D, dtype: float64
new total cases: 356.0, old total cases: 355.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    1.0
Freq: D, dtype: float64
new total cases: 357.0, old total cases: 356.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    1.0
Freq: D, dtype: float64
new total cases: 357.0, old total cases: 357.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    0.0
Freq: D, dtype: float64
new total cases: 358.0, old total cases: 357.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    1.0
Freq: D, dtype: float64
new total cases: 358.0, old total cases: 358.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    0.0
Freq: D, dtype: float64
new total cases: 358.0, old total cases: 358.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    0.0
Freq: D, dtype: float64
new total cases: 358.0, old total cases: 358.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    0.0
Freq: D, dtype: float64
new total cases: 359.0, old total cases: 358.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    1.0
Freq: D, dtype: float64
new total cases: 359.0, old total cases: 359.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    0.0
Freq: D, dtype: float64
new total cases: 359.0, old total cases: 359.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    0.0
Freq: D, dtype: float64
new total cases: 362.0, old total cases: 359.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    3.0
Freq: D, dtype: float64
new total cases: 366.0, old total cases: 362.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    2.0
2017-08-03    2.0
Freq: D, dtype: float64
new total cases: 374.0, old total cases: 366.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    2.666667
2017-08-05    2.666667
2017-08-06    2.666667
Freq: D, dtype: float64
new total cases: 378.0, old total cases: 374.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    0.571429
2017-08-08    0.571429
2017-08-09    0.571429
2017-08-10    0.571429
2017-08-11    0.571429
2017-08-12    0.571429
2017-08-13    0.571429
Freq: D, dtype: float64
new total cases: 378.0, old total cases: 378.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    0.0
2017-08-15    0.0
Freq: D, dtype: float64
new total cases: 378.0, old total cases: 378.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    0.0
Freq: D, dtype: float64
new total cases: 380.0, old total cases: 378.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    2.0
Freq: D, dtype: float64
new total cases: 381.0, old total cases: 380.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    1.0
Freq: D, dtype: float64
new total cases: 381.0, old total cases: 381.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    0.0
Freq: D, dtype: float64
new total cases: 381.0, old total cases: 381.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    0.0
Freq: D, dtype: float64
new total cases: 381.0, old total cases: 381.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    0.0
Freq: D, dtype: float64
new total cases: 381.0, old total cases: 381.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    0.0
Freq: D, dtype: float64
new total cases: 382.0, old total cases: 381.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    1.0
Freq: D, dtype: float64
new total cases: 382.0, old total cases: 382.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    0.0
Freq: D, dtype: float64
new total cases: 382.0, old total cases: 382.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    0.0
2017-08-26    0.0
Freq: D, dtype: float64
new total cases: 382.0, old total cases: 382.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    0.0
Freq: D, dtype: float64
new total cases: 382.0, old total cases: 382.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    0.0
Freq: D, dtype: float64
new total cases: 382.0, old total cases: 382.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    0.0
Freq: D, dtype: float64
new total cases: 383.0, old total cases: 382.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    1.0
Freq: D, dtype: float64
new total cases: 383.0, old total cases: 383.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    0.0
Freq: D, dtype: float64
new total cases: 383.0, old total cases: 383.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    0.0
Freq: D, dtype: float64
new total cases: 384.0, old total cases: 383.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    1.0
Freq: D, dtype: float64
new total cases: 384.0, old total cases: 384.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    0.0
Freq: D, dtype: float64
new total cases: 384.0, old total cases: 384.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    0.0
Freq: D, dtype: float64
new total cases: 386.0, old total cases: 384.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    2.0
Freq: D, dtype: float64
new total cases: 387.0, old total cases: 386.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    1.0
Freq: D, dtype: float64
new total cases: 389.0, old total cases: 387.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    2.0
Freq: D, dtype: float64
new total cases: 389.0, old total cases: 389.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    0.0
Freq: D, dtype: float64
new total cases: 389.0, old total cases: 389.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    0.0
Freq: D, dtype: float64
new total cases: 390.0, old total cases: 389.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    1.0
Freq: D, dtype: float64
new total cases: 391.0, old total cases: 390.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    1.0
Freq: D, dtype: float64
new total cases: 392.0, old total cases: 391.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    1.0
Freq: D, dtype: float64
new total cases: 393.0, old total cases: 392.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    1.0
Freq: D, dtype: float64
new total cases: 393.0, old total cases: 393.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    0.0
Freq: D, dtype: float64
new total cases: 393.0, old total cases: 393.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    0.0
Freq: D, dtype: float64
new total cases: 393.0, old total cases: 393.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    0.0
Freq: D, dtype: float64
new total cases: 393.0, old total cases: 393.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    0.0
Freq: D, dtype: float64
new total cases: 393.0, old total cases: 393.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    0.0
Freq: D, dtype: float64
new total cases: 396.0, old total cases: 393.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    3.0
Freq: D, dtype: float64
new total cases: 396.0, old total cases: 396.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    0.0
Freq: D, dtype: float64
new total cases: 396.0, old total cases: 396.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    0.0
Freq: D, dtype: float64
new total cases: 396.0, old total cases: 396.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    0.0
Freq: D, dtype: float64
new total cases: 398.0, old total cases: 396.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    2.0
Freq: D, dtype: float64
new total cases: 398.0, old total cases: 398.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    0.0
Freq: D, dtype: float64
new total cases: 398.0, old total cases: 398.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    0.0
Freq: D, dtype: float64
new total cases: 398.0, old total cases: 398.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    0.0
Freq: D, dtype: float64
new total cases: 398.0, old total cases: 398.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    0.0
Freq: D, dtype: float64
new total cases: 398.0, old total cases: 398.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    0.0
Freq: D, dtype: float64
new total cases: 399.0, old total cases: 398.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    0.5
2017-09-30    0.5
Freq: D, dtype: float64
new total cases: 400.0, old total cases: 399.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    1.0
Freq: D, dtype: float64
new total cases: 400.0, old total cases: 400.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 401.0, old total cases: 400.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    1.0
Freq: D, dtype: float64
new total cases: 401.0, old total cases: 401.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    0.0
Freq: D, dtype: float64
new total cases: 401.0, old total cases: 401.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    0.0
Freq: D, dtype: float64
new total cases: 403.0, old total cases: 401.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    0.666667
2017-10-07    0.666667
2017-10-08    0.666667
Freq: D, dtype: float64
new total cases: 403.0, old total cases: 403.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    0.0
Freq: D, dtype: float64
new total cases: 403.0, old total cases: 403.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    0.0
Freq: D, dtype: float64
new total cases: 403.0, old total cases: 403.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    0.0
Freq: D, dtype: float64
new total cases: 408.0, old total cases: 403.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    1.666667
2017-10-13    1.666667
2017-10-14    1.666667
Freq: D, dtype: float64
new total cases: 408.0, old total cases: 408.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    0.0
2017-10-16    0.0
Freq: D, dtype: float64
new total cases: 408.0, old total cases: 408.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    0.0
Freq: D, dtype: float64
new total cases: 409.0, old total cases: 408.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    0.25
2017-10-19    0.25
2017-10-20    0.25
2017-10-21    0.25
Freq: D, dtype: float64
new total cases: 409.0, old total cases: 409.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    0.0
Freq: D, dtype: float64
new total cases: 409.0, old total cases: 409.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    0.0
2017-10-24    0.0
2017-10-25    0.0
Freq: D, dtype: float64
new total cases: 409.0, old total cases: 409.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    0.0
2017-10-27    0.0
2017-10-28    0.0
Freq: D, dtype: float64
new total cases: 410.0, old total cases: 409.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    1.0
Freq: D, dtype: float64
new total cases: 410.0, old total cases: 410.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    0.0
Freq: D, dtype: float64
new total cases: 411.0, old total cases: 410.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    0.25
2017-11-01    0.25
2017-11-02    0.25
2017-11-03    0.25
Freq: D, dtype: float64
new total cases: 413.0, old total cases: 411.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    2.0
Freq: D, dtype: float64
new total cases: 414.0, old total cases: 413.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    1.0
Freq: D, dtype: float64
new total cases: 414.0, old total cases: 414.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    0.0
Freq: D, dtype: float64
new total cases: 414.0, old total cases: 414.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    0.0
Freq: D, dtype: float64
new total cases: 414.0, old total cases: 414.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    0.0
Freq: D, dtype: float64
new total cases: 416.0, old total cases: 414.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    0.181818
2017-11-10    0.181818
2017-11-11    0.181818
2017-11-12    0.181818
2017-11-13    0.181818
2017-11-14    0.181818
2017-11-15    0.181818
2017-11-16    0.181818
2017-11-17    0.181818
2017-11-18    0.181818
2017-11-19    0.181818
Freq: D, dtype: float64
new total cases: 417.0, old total cases: 416.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    0.142857
2017-11-21    0.142857
2017-11-22    0.142857
2017-11-23    0.142857
2017-11-24    0.142857
2017-11-25    0.142857
2017-11-26    0.142857
Freq: D, dtype: float64
new total cases: 417.0, old total cases: 417.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    0.0
2017-11-28    0.0
2017-11-29    0.0
2017-11-30    0.0
2017-12-01    0.0
2017-12-02    0.0
2017-12-03    0.0
2017-12-04    0.0
2017-12-05    0.0
2017-12-06    0.0
2017-12-07    0.0
2017-12-08    0.0
2017-12-09    0.0
2017-12-10    0.0
2017-12-11    0.0
2017-12-12    0.0
2017-12-13    0.0
2017-12-14    0.0
2017-12-15    0.0
2017-12-16    0.0
2017-12-17    0.0
Freq: D, dtype: float64
new total cases: 419.0, old total cases: 417.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    0.142857
2017-12-19    0.142857
2017-12-20    0.142857
2017-12-21    0.142857
2017-12-22    0.142857
2017-12-23    0.142857
2017-12-24    0.142857
2017-12-25    0.142857
2017-12-26    0.142857
2017-12-27    0.142857
2017-12-28    0.142857
2017-12-29    0.142857
2017-12-30    0.142857
2017-12-31    0.142857
Freq: D, dtype: float64
new total cases: 420.0, old total cases: 419.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    0.142857
2018-01-02    0.142857
2018-01-03    0.142857
2018-01-04    0.142857
2018-01-05    0.142857
2018-01-06    0.142857
2018-01-07    0.142857
Freq: D, dtype: float64
new total cases: 420.0, old total cases: 420.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    0.0
2018-01-09    0.0
2018-01-10    0.0
2018-01-11    0.0
2018-01-12    0.0
2018-01-13    0.0
2018-01-14    0.0
Freq: D, dtype: float64
new total cases: 421.0, old total cases: 420.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    0.142857
2018-01-16    0.142857
2018-01-17    0.142857
2018-01-18    0.142857
2018-01-19    0.142857
2018-01-20    0.142857
2018-01-21    0.142857
Freq: D, dtype: float64
new total cases: 421.0, old total cases: 421.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    0.0
2018-01-23    0.0
2018-01-24    0.0
2018-01-25    0.0
2018-01-26    0.0
2018-01-27    0.0
2018-01-28    0.0
Freq: D, dtype: float64
new total cases: 422.0, old total cases: 421.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    0.142857
2018-01-30    0.142857
2018-01-31    0.142857
2018-02-01    0.142857
2018-02-02    0.142857
2018-02-03    0.142857
2018-02-04    0.142857
Freq: D, dtype: float64
new total cases: 422.0, old total cases: 422.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    0.0
2018-02-06    0.0
2018-02-07    0.0
2018-02-08    0.0
2018-02-09    0.0
2018-02-10    0.0
2018-02-11    0.0
Freq: D, dtype: float64
new total cases: 422.0, old total cases: 422.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    0.0
2018-02-13    0.0
2018-02-14    0.0
2018-02-15    0.0
2018-02-16    0.0
2018-02-17    0.0
2018-02-18    0.0
Freq: D, dtype: float64
new total cases: 40.0, old total cases: 32.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    1.6
2017-05-24    1.6
2017-05-25    1.6
2017-05-26    1.6
2017-05-27    1.6
Freq: D, dtype: float64
new total cases: 41.0, old total cases: 40.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    0.333333
2017-05-29    0.333333
2017-05-30    0.333333
Freq: D, dtype: float64
new total cases: 59.0, old total cases: 41.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    3.6
2017-06-01    3.6
2017-06-02    3.6
2017-06-03    3.6
2017-06-04    3.6
Freq: D, dtype: float64
new total cases: 74.0, old total cases: 59.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    5.0
2017-06-06    5.0
2017-06-07    5.0
Freq: D, dtype: float64
new total cases: 87.0, old total cases: 74.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    4.333333
2017-06-09    4.333333
2017-06-10    4.333333
Freq: D, dtype: float64
new total cases: 87.0, old total cases: 87.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    0.0
2017-06-12    0.0
Freq: D, dtype: float64
new total cases: 94.0, old total cases: 87.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    7.0
Freq: D, dtype: float64
new total cases: 95.0, old total cases: 94.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    1.0
Freq: D, dtype: float64
new total cases: 106.0, old total cases: 95.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    3.666667
2017-06-16    3.666667
2017-06-17    3.666667
Freq: D, dtype: float64
new total cases: 110.0, old total cases: 106.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    4.0
Freq: D, dtype: float64
new total cases: 112.0, old total cases: 110.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    2.0
Freq: D, dtype: float64
new total cases: 117.0, old total cases: 112.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    5.0

Freq: D, dtype: float64
new total cases: 276.0, old total cases: 275.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    0.5
2017-09-30    0.5
Freq: D, dtype: float64
new total cases: 276.0, old total cases: 276.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    0.0
Freq: D, dtype: float64
new total cases: 276.0, old total cases: 276.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 276.0, old total cases: 276.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    0.0
Freq: D, dtype: float64
new total cases: 276.0, old total cases: 276.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    0.0
Freq: D, dtype: float64
new total cases: 276.0, old total cases: 276.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    0.0
Freq: D, dtype: float64
new total cases: 277.0, old total cases: 276.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    0.333333
2017-10-07    0.333333
2017-10-08    0.333333
Freq: D, dtype: float64
new total cases: 277.0, old total cases: 277.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    0.0
Freq: D, dtype: float64
new total cases: 277.0, old total cases: 277.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    0.0
Freq: D, dtype: float64
new total cases: 278.0, old total cases: 277.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    1.0
Freq: D, dtype: float64
new total cases: 278.0, old total cases: 278.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    0.0
2017-10-13    0.0
2017-10-14    0.0
Freq: D, dtype: float64
new total cases: 278.0, old total cases: 278.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    0.0
2017-10-16    0.0
Freq: D, dtype: float64
new total cases: 278.0, old total cases: 278.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    0.0
Freq: D, dtype: float64
new total cases: 279.0, old total cases: 278.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    0.25
2017-10-19    0.25
2017-10-20    0.25
2017-10-21    0.25
Freq: D, dtype: float64
new total cases: 279.0, old total cases: 279.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    0.0
Freq: D, dtype: float64
new total cases: 280.0, old total cases: 279.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    0.333333
2017-10-24    0.333333
2017-10-25    0.333333
Freq: D, dtype: float64
new total cases: 281.0, old total cases: 280.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    0.333333
2017-10-27    0.333333
2017-10-28    0.333333
Freq: D, dtype: float64
new total cases: 281.0, old total cases: 281.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    0.0
Freq: D, dtype: float64
new total cases: 281.0, old total cases: 281.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    0.0
Freq: D, dtype: float64
new total cases: 281.0, old total cases: 281.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    0.0
2017-11-01    0.0
2017-11-02    0.0
2017-11-03    0.0
Freq: D, dtype: float64
new total cases: 282.0, old total cases: 281.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    1.0
Freq: D, dtype: float64
new total cases: 282.0, old total cases: 282.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    0.0
Freq: D, dtype: float64
new total cases: 282.0, old total cases: 282.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    0.0
Freq: D, dtype: float64
new total cases: 282.0, old total cases: 282.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    0.0
Freq: D, dtype: float64
new total cases: 282.0, old total cases: 282.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    0.0
Freq: D, dtype: float64
new total cases: 283.0, old total cases: 282.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    0.090909
2017-11-10    0.090909
2017-11-11    0.090909
2017-11-12    0.090909
2017-11-13    0.090909
2017-11-14    0.090909
2017-11-15    0.090909
2017-11-16    0.090909
2017-11-17    0.090909
2017-11-18    0.090909
2017-11-19    0.090909
Freq: D, dtype: float64
new total cases: 284.0, old total cases: 283.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    0.142857
2017-11-21    0.142857
2017-11-22    0.142857
2017-11-23    0.142857
2017-11-24    0.142857
2017-11-25    0.142857
2017-11-26    0.142857
Freq: D, dtype: float64
new total cases: 285.0, old total cases: 284.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    0.047619
2017-11-28    0.047619
2017-11-29    0.047619
2017-11-30    0.047619
2017-12-01    0.047619
2017-12-02    0.047619
2017-12-03    0.047619
2017-12-04    0.047619
2017-12-05    0.047619
2017-12-06    0.047619
2017-12-07    0.047619
2017-12-08    0.047619
2017-12-09    0.047619
2017-12-10    0.047619
2017-12-11    0.047619
2017-12-12    0.047619
2017-12-13    0.047619
2017-12-14    0.047619
2017-12-15    0.047619
2017-12-16    0.047619
2017-12-17    0.047619
Freq: D, dtype: float64
new total cases: 286.0, old total cases: 285.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    0.071429
2017-12-19    0.071429
2017-12-20    0.071429
2017-12-21    0.071429
2017-12-22    0.071429
2017-12-23    0.071429
2017-12-24    0.071429
2017-12-25    0.071429
2017-12-26    0.071429
2017-12-27    0.071429
2017-12-28    0.071429
2017-12-29    0.071429
2017-12-30    0.071429
2017-12-31    0.071429
Freq: D, dtype: float64
new total cases: 286.0, old total cases: 286.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    0.0
2018-01-02    0.0
2018-01-03    0.0
2018-01-04    0.0
2018-01-05    0.0
2018-01-06    0.0
2018-01-07    0.0
Freq: D, dtype: float64
new total cases: 286.0, old total cases: 286.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    0.0
2018-01-09    0.0
2018-01-10    0.0
2018-01-11    0.0
2018-01-12    0.0
2018-01-13    0.0
2018-01-14    0.0
Freq: D, dtype: float64
new total cases: 287.0, old total cases: 286.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    0.142857
2018-01-16    0.142857
2018-01-17    0.142857
2018-01-18    0.142857
2018-01-19    0.142857
2018-01-20    0.142857
2018-01-21    0.142857
Freq: D, dtype: float64
new total cases: 287.0, old total cases: 287.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    0.0
2018-01-23    0.0
2018-01-24    0.0
2018-01-25    0.0
2018-01-26    0.0
2018-01-27    0.0
2018-01-28    0.0
Freq: D, dtype: float64
new total cases: 287.0, old total cases: 287.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    0.0
2018-01-30    0.0
2018-01-31    0.0
2018-02-01    0.0
2018-02-02    0.0
2018-02-03    0.0
2018-02-04    0.0
Freq: D, dtype: float64
new total cases: 288.0, old total cases: 287.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    0.142857
2018-02-06    0.142857
2018-02-07    0.142857
2018-02-08    0.142857
2018-02-09    0.142857
2018-02-10    0.142857
2018-02-11    0.142857
Freq: D, dtype: float64
new total cases: 288.0, old total cases: 288.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    0.0
2018-02-13    0.0
2018-02-14    0.0
2018-02-15    0.0
2018-02-16    0.0
2018-02-17    0.0
2018-02-18    0.0
Freq: D, dtype: float64
new total cases: 3.0, old total cases: 3.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    0.0
2017-05-24    0.0
2017-05-25    0.0
2017-05-26    0.0
2017-05-27    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 3.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    0.333333
2017-05-29    0.333333
2017-05-30    0.333333
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 4.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    0.2
2017-06-01    0.2
2017-06-02    0.2
2017-06-03    0.2
2017-06-04    0.2
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    0.0
2017-06-06    0.0
2017-06-07    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 5.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    0.666667
2017-06-09    0.666667
2017-06-10    0.666667
Freq: D, dtype: float64
new total cases: 8.0, old total cases: 7.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    0.5
2017-06-12    0.5
Freq: D, dtype: float64
new total cases: 8.0, old total cases: 8.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    0.0
Freq: D, dtype: float64
new total cases: 8.0, old total cases: 8.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    0.0
Freq: D, dtype: float64
new total cases: 9.0, old total cases: 8.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    0.333333
2017-06-16    0.333333
2017-06-17    0.333333
Freq: D, dtype: float64
new total cases: 9.0, old total cases: 9.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    0.0
Freq: D, dtype: float64
new total cases: 9.0, old total cases: 9.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    0.0
Freq: D, dtype: float64
new total cases: 9.0, old total cases: 9.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    0.0
Freq: D, dtype: float64
new total cases: 9.0, old total cases: 9.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    0.0
Freq: D, dtype: float64
new total cases: 9.0, old total cases: 9.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    0.0
Freq: D, dtype: float64
new total cases: 9.0, old total cases: 9.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    0.0
Freq: D, dtype: float64
new total cases: 10.0, old total cases: 9.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    1.0
Freq: D, dtype: float64
new total cases: 10.0, old total cases: 10.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    0.0
Freq: D, dtype: float64
new total cases: 10.0, old total cases: 10.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    0.0
Freq: D, dtype: float64
new total cases: 10.0, old total cases: 10.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    0.0
Freq: D, dtype: float64
new total cases: 10.0, old total cases: 10.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    0.0
Freq: D, dtype: float64
new total cases: 10.0, old total cases: 10.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    0.0
Freq: D, dtype: float64
new total cases: 10.0, old total cases: 10.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    0.0
Freq: D, dtype: float64
new total cases: 10.0, old total cases: 10.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    0.0
Freq: D, dtype: float64
new total cases: 11.0, old total cases: 10.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    1.0
Freq: D, dtype: float64
new total cases: 11.0, old total cases: 11.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    0.0
Freq: D, dtype: float64
new total cases: 11.0, old total cases: 11.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 11.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    2.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    0.0
2017-07-09    0.0
2017-07-10    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    0.0
Freq: D, dtype: float64
new total cases: 13.0, old total cases: 13.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    0.0
Freq: D, dtype: float64
new total cases: 15.0, old total cases: 13.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    2.0
Freq: D, dtype: float64
new total cases: 16.0, old total cases: 15.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    1.0
Freq: D, dtype: float64
new total cases: 16.0, old total cases: 16.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    0.0
Freq: D, dtype: float64
new total cases: 16.0, old total cases: 16.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    0.0
Freq: D, dtype: float64
new total cases: 16.0, old total cases: 16.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    0.0
Freq: D, dtype: float64
new total cases: 16.0, old total cases: 16.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    0.0
Freq: D, dtype: float64
new total cases: 17.0, old total cases: 16.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    1.0
Freq: D, dtype: float64
new total cases: 17.0, old total cases: 17.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    0.0
2017-08-03    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 17.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    0.333333
2017-08-05    0.333333
2017-08-06    0.333333
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    0.0
2017-08-08    0.0
2017-08-09    0.0
2017-08-10    0.0
2017-08-11    0.0
2017-08-12    0.0
2017-08-13    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    0.0
2017-08-15    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    0.0
2017-08-26    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    0.0
Freq: D, dtype: float64
new total cases: 18.0, old total cases: 18.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    0.0
Freq: D, dtype: float64
new total cases: 19.0, old total cases: 18.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    1.0
Freq: D, dtype: float64
new total cases: 19.0, old total cases: 19.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    0.0
Freq: D, dtype: float64
new total cases: 19.0, old total cases: 19.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    0.0
Freq: D, dtype: float64
new total cases: 20.0, old total cases: 19.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    1.0
Freq: D, dtype: float64
new total cases: 20.0, old total cases: 20.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    0.0
Freq: D, dtype: float64
new total cases: 20.0, old total cases: 20.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    0.0
Freq: D, dtype: float64
new total cases: 20.0, old total cases: 20.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    0.0
Freq: D, dtype: float64
new total cases: 20.0, old total cases: 20.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    0.0
Freq: D, dtype: float64

new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    0.0
2017-07-09    0.0
2017-07-10    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    0.0
2017-08-03    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    0.0
2017-08-05    0.0
2017-08-06    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    0.0
2017-08-08    0.0
2017-08-09    0.0
2017-08-10    0.0
2017-08-11    0.0
2017-08-12    0.0
2017-08-13    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    0.0
2017-08-15    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    0.0
2017-08-26    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    0.0
Freq: D, dtype: float64
new total cases: 4.0, old total cases: 4.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 4.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    3.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    0.0
2017-09-30    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    0.0
2017-10-07    0.0
2017-10-08    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    0.0
2017-10-13    0.0
2017-10-14    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    0.0
2017-10-16    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    0.0
2017-10-19    0.0
2017-10-20    0.0
2017-10-21    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    0.0
2017-10-24    0.0
2017-10-25    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    0.0
2017-10-27    0.0
2017-10-28    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    0.0
2017-11-01    0.0
2017-11-02    0.0
2017-11-03    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    0.0
2017-11-10    0.0
2017-11-11    0.0
2017-11-12    0.0
2017-11-13    0.0
2017-11-14    0.0
2017-11-15    0.0
2017-11-16    0.0
2017-11-17    0.0
2017-11-18    0.0
2017-11-19    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    0.0
2017-11-21    0.0
2017-11-22    0.0
2017-11-23    0.0
2017-11-24    0.0
2017-11-25    0.0
2017-11-26    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    0.0
2017-11-28    0.0
2017-11-29    0.0
2017-11-30    0.0
2017-12-01    0.0
2017-12-02    0.0
2017-12-03    0.0
2017-12-04    0.0
2017-12-05    0.0
2017-12-06    0.0
2017-12-07    0.0
2017-12-08    0.0
2017-12-09    0.0
2017-12-10    0.0
2017-12-11    0.0
2017-12-12    0.0
2017-12-13    0.0
2017-12-14    0.0
2017-12-15    0.0
2017-12-16    0.0
2017-12-17    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    0.0
2017-12-19    0.0
2017-12-20    0.0
2017-12-21    0.0
2017-12-22    0.0
2017-12-23    0.0
2017-12-24    0.0
2017-12-25    0.0
2017-12-26    0.0
2017-12-27    0.0
2017-12-28    0.0
2017-12-29    0.0
2017-12-30    0.0
2017-12-31    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    0.0
2018-01-02    0.0
2018-01-03    0.0
2018-01-04    0.0
2018-01-05    0.0
2018-01-06    0.0
2018-01-07    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    0.0
2018-01-09    0.0
2018-01-10    0.0
2018-01-11    0.0
2018-01-12    0.0
2018-01-13    0.0
2018-01-14    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    0.0
2018-01-16    0.0
2018-01-17    0.0
2018-01-18    0.0
2018-01-19    0.0
2018-01-20    0.0
2018-01-21    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    0.0
2018-01-23    0.0
2018-01-24    0.0
2018-01-25    0.0
2018-01-26    0.0
2018-01-27    0.0
2018-01-28    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    0.0
2018-01-30    0.0
2018-01-31    0.0
2018-02-01    0.0
2018-02-02    0.0
2018-02-03    0.0
2018-02-04    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    0.0
2018-02-06    0.0
2018-02-07    0.0
2018-02-08    0.0
2018-02-09    0.0
2018-02-10    0.0
2018-02-11    0.0
Freq: D, dtype: float64
new total cases: 7.0, old total cases: 7.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    0.0
2018-02-13    0.0
2018-02-14    0.0
2018-02-15    0.0
2018-02-16    0.0
2018-02-17    0.0
2018-02-18    0.0
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23   NaN
2017-05-24   NaN
2017-05-25   NaN
2017-05-26   NaN
2017-05-27   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28   NaN
2017-05-29   NaN
2017-05-30   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31   NaN
2017-06-01   NaN
2017-06-02   NaN
2017-06-03   NaN
2017-06-04   NaN
Freq: D, dtype: float64
new total cases: nan, old total cases: nan
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05   NaN
2017-06-06   NaN
2017-06-07   NaN
Freq: D, dtype: float64
new total cases: 0.0, old total cases: nan
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08   NaN
2017-06-09   NaN
2017-06-10   NaN
Freq: D, dtype: float64
new total cases: 0.0, old total cases: 0.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    0.0
2017-06-12    0.0
Freq: D, dtype: float64
new total cases: 0.0, old total cases: 0.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    0.0
Freq: D, dtype: float64
new total cases: 0.0, old total cases: 0.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    0.0
Freq: D, dtype: float64
new total cases: 0.0, old total cases: 0.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    0.0
2017-06-16    0.0
2017-06-17    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 0.0

2017-09-17    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    0.0
2017-09-30    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    0.0
Freq: D, dtype: float64
new total cases: 140.0, old total cases: 140.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    0.0
Freq: D, dtype: float64
new total cases: 141.0, old total cases: 140.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    0.333333
2017-10-07    0.333333
2017-10-08    0.333333
Freq: D, dtype: float64
new total cases: 141.0, old total cases: 141.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    0.0
Freq: D, dtype: float64
new total cases: 141.0, old total cases: 141.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    0.0
Freq: D, dtype: float64
new total cases: 142.0, old total cases: 141.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    1.0
Freq: D, dtype: float64
new total cases: 142.0, old total cases: 142.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    0.0
2017-10-13    0.0
2017-10-14    0.0
Freq: D, dtype: float64
new total cases: 142.0, old total cases: 142.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    0.0
2017-10-16    0.0
Freq: D, dtype: float64
new total cases: 142.0, old total cases: 142.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    0.0
Freq: D, dtype: float64
new total cases: 142.0, old total cases: 142.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    0.0
2017-10-19    0.0
2017-10-20    0.0
2017-10-21    0.0
Freq: D, dtype: float64
new total cases: 142.0, old total cases: 142.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    0.0
Freq: D, dtype: float64
new total cases: 143.0, old total cases: 142.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    0.333333
2017-10-24    0.333333
2017-10-25    0.333333
Freq: D, dtype: float64
new total cases: 143.0, old total cases: 143.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    0.0
2017-10-27    0.0
2017-10-28    0.0
Freq: D, dtype: float64
new total cases: 143.0, old total cases: 143.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    0.0
Freq: D, dtype: float64
new total cases: 143.0, old total cases: 143.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 143.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    0.5
2017-11-01    0.5
2017-11-02    0.5
2017-11-03    0.5
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    0.0
Freq: D, dtype: float64
new total cases: 145.0, old total cases: 145.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    0.0
Freq: D, dtype: float64
new total cases: 148.0, old total cases: 145.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    0.272727
2017-11-10    0.272727
2017-11-11    0.272727
2017-11-12    0.272727
2017-11-13    0.272727
2017-11-14    0.272727
2017-11-15    0.272727
2017-11-16    0.272727
2017-11-17    0.272727
2017-11-18    0.272727
2017-11-19    0.272727
Freq: D, dtype: float64
new total cases: 148.0, old total cases: 148.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    0.0
2017-11-21    0.0
2017-11-22    0.0
2017-11-23    0.0
2017-11-24    0.0
2017-11-25    0.0
2017-11-26    0.0
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 148.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    0.047619
2017-11-28    0.047619
2017-11-29    0.047619
2017-11-30    0.047619
2017-12-01    0.047619
2017-12-02    0.047619
2017-12-03    0.047619
2017-12-04    0.047619
2017-12-05    0.047619
2017-12-06    0.047619
2017-12-07    0.047619
2017-12-08    0.047619
2017-12-09    0.047619
2017-12-10    0.047619
2017-12-11    0.047619
2017-12-12    0.047619
2017-12-13    0.047619
2017-12-14    0.047619
2017-12-15    0.047619
2017-12-16    0.047619
2017-12-17    0.047619
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 149.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    0.0
2017-12-19    0.0
2017-12-20    0.0
2017-12-21    0.0
2017-12-22    0.0
2017-12-23    0.0
2017-12-24    0.0
2017-12-25    0.0
2017-12-26    0.0
2017-12-27    0.0
2017-12-28    0.0
2017-12-29    0.0
2017-12-30    0.0
2017-12-31    0.0
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 149.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    0.0
2018-01-02    0.0
2018-01-03    0.0
2018-01-04    0.0
2018-01-05    0.0
2018-01-06    0.0
2018-01-07    0.0
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 149.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    0.0
2018-01-09    0.0
2018-01-10    0.0
2018-01-11    0.0
2018-01-12    0.0
2018-01-13    0.0
2018-01-14    0.0
Freq: D, dtype: float64
new total cases: 149.0, old total cases: 149.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    0.0
2018-01-16    0.0
2018-01-17    0.0
2018-01-18    0.0
2018-01-19    0.0
2018-01-20    0.0
2018-01-21    0.0
Freq: D, dtype: float64
new total cases: 151.0, old total cases: 149.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    0.285714
2018-01-23    0.285714
2018-01-24    0.285714
2018-01-25    0.285714
2018-01-26    0.285714
2018-01-27    0.285714
2018-01-28    0.285714
Freq: D, dtype: float64
new total cases: 151.0, old total cases: 151.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    0.0
2018-01-30    0.0
2018-01-31    0.0
2018-02-01    0.0
2018-02-02    0.0
2018-02-03    0.0
2018-02-04    0.0
Freq: D, dtype: float64
new total cases: 151.0, old total cases: 151.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    0.0
2018-02-06    0.0
2018-02-07    0.0
2018-02-08    0.0
2018-02-09    0.0
2018-02-10    0.0
2018-02-11    0.0
Freq: D, dtype: float64
new total cases: 151.0, old total cases: 151.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    0.0
2018-02-13    0.0
2018-02-14    0.0
2018-02-15    0.0
2018-02-16    0.0
2018-02-17    0.0
2018-02-18    0.0
Freq: D, dtype: float64
new total cases: 8.0, old total cases: 4.0
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23    0.8
2017-05-24    0.8
2017-05-25    0.8
2017-05-26    0.8
2017-05-27    0.8
Freq: D, dtype: float64
new total cases: 9.0, old total cases: 8.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    0.333333
2017-05-29    0.333333
2017-05-30    0.333333
Freq: D, dtype: float64
new total cases: 15.0, old total cases: 9.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    1.2
2017-06-01    1.2
2017-06-02    1.2
2017-06-03    1.2
2017-06-04    1.2
Freq: D, dtype: float64
new total cases: 25.0, old total cases: 15.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    3.333333
2017-06-06    3.333333
2017-06-07    3.333333
Freq: D, dtype: float64
new total cases: 37.0, old total cases: 25.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    4.0
2017-06-09    4.0
2017-06-10    4.0
Freq: D, dtype: float64
new total cases: 41.0, old total cases: 37.0
new date: 2017-06-12 00:00:00, old date: 2017-06-10 00:00:00
2017-06-11    2.0
2017-06-12    2.0
Freq: D, dtype: float64
new total cases: 41.0, old total cases: 41.0
new date: 2017-06-13 00:00:00, old date: 2017-06-12 00:00:00
2017-06-13    0.0
Freq: D, dtype: float64
new total cases: 42.0, old total cases: 41.0
new date: 2017-06-14 00:00:00, old date: 2017-06-13 00:00:00
2017-06-14    1.0
Freq: D, dtype: float64
new total cases: 45.0, old total cases: 42.0
new date: 2017-06-17 00:00:00, old date: 2017-06-14 00:00:00
2017-06-15    1.0
2017-06-16    1.0
2017-06-17    1.0
Freq: D, dtype: float64
new total cases: 55.0, old total cases: 45.0
new date: 2017-06-18 00:00:00, old date: 2017-06-17 00:00:00
2017-06-18    10.0
Freq: D, dtype: float64
new total cases: 55.0, old total cases: 55.0
new date: 2017-06-19 00:00:00, old date: 2017-06-18 00:00:00
2017-06-19    0.0
Freq: D, dtype: float64
new total cases: 58.0, old total cases: 55.0
new date: 2017-06-20 00:00:00, old date: 2017-06-19 00:00:00
2017-06-20    3.0
Freq: D, dtype: float64
new total cases: 59.0, old total cases: 58.0
new date: 2017-06-21 00:00:00, old date: 2017-06-20 00:00:00
2017-06-21    1.0
Freq: D, dtype: float64
new total cases: 61.0, old total cases: 59.0
new date: 2017-06-22 00:00:00, old date: 2017-06-21 00:00:00
2017-06-22    2.0
Freq: D, dtype: float64
new total cases: 63.0, old total cases: 61.0
new date: 2017-06-23 00:00:00, old date: 2017-06-22 00:00:00
2017-06-23    2.0
Freq: D, dtype: float64
new total cases: 63.0, old total cases: 63.0
new date: 2017-06-24 00:00:00, old date: 2017-06-23 00:00:00
2017-06-24    0.0
Freq: D, dtype: float64
new total cases: 63.0, old total cases: 63.0
new date: 2017-06-25 00:00:00, old date: 2017-06-24 00:00:00
2017-06-25    0.0
Freq: D, dtype: float64
new total cases: 64.0, old total cases: 63.0
new date: 2017-06-26 00:00:00, old date: 2017-06-25 00:00:00
2017-06-26    1.0
Freq: D, dtype: float64
new total cases: 64.0, old total cases: 64.0
new date: 2017-06-27 00:00:00, old date: 2017-06-26 00:00:00
2017-06-27    0.0
Freq: D, dtype: float64
new total cases: 66.0, old total cases: 64.0
new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    2.0
Freq: D, dtype: float64
new total cases: 67.0, old total cases: 66.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    1.0
Freq: D, dtype: float64
new total cases: 67.0, old total cases: 67.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    0.0
Freq: D, dtype: float64
new total cases: 71.0, old total cases: 67.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    4.0
Freq: D, dtype: float64
new total cases: 73.0, old total cases: 71.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    2.0
Freq: D, dtype: float64
new total cases: 74.0, old total cases: 73.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    1.0
Freq: D, dtype: float64
new total cases: 74.0, old total cases: 74.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    0.0
Freq: D, dtype: float64
new total cases: 75.0, old total cases: 74.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    1.0
Freq: D, dtype: float64
new total cases: 78.0, old total cases: 75.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    3.0
Freq: D, dtype: float64
new total cases: 78.0, old total cases: 78.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 78.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    0.666667
2017-07-09    0.666667
2017-07-10    0.666667
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    0.0
Freq: D, dtype: float64
new total cases: 80.0, old total cases: 80.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    0.0
Freq: D, dtype: float64
new total cases: 81.0, old total cases: 80.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    1.0
Freq: D, dtype: float64
new total cases: 85.0, old total cases: 81.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    4.0
Freq: D, dtype: float64
new total cases: 85.0, old total cases: 85.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    0.0
Freq: D, dtype: float64
new total cases: 86.0, old total cases: 85.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    1.0
Freq: D, dtype: float64
new total cases: 90.0, old total cases: 86.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    4.0
Freq: D, dtype: float64
new total cases: 90.0, old total cases: 90.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    0.0
Freq: D, dtype: float64
new total cases: 91.0, old total cases: 90.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    1.0
Freq: D, dtype: float64
new total cases: 91.0, old total cases: 91.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    0.0
Freq: D, dtype: float64
new total cases: 91.0, old total cases: 91.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    0.0
Freq: D, dtype: float64
new total cases: 91.0, old total cases: 91.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    0.0
Freq: D, dtype: float64
new total cases: 91.0, old total cases: 91.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    0.0
Freq: D, dtype: float64
new total cases: 91.0, old total cases: 91.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    0.0
Freq: D, dtype: float64
new total cases: 91.0, old total cases: 91.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    0.0
Freq: D, dtype: float64
new total cases: 92.0, old total cases: 91.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    1.0
Freq: D, dtype: float64
new total cases: 94.0, old total cases: 92.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    2.0
Freq: D, dtype: float64
new total cases: 94.0, old total cases: 94.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    0.0
Freq: D, dtype: float64
new total cases: 95.0, old total cases: 94.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    1.0
Freq: D, dtype: float64
new total cases: 95.0, old total cases: 95.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    0.0
Freq: D, dtype: float64
new total cases: 95.0, old total cases: 95.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    0.0
Freq: D, dtype: float64
new total cases: 95.0, old total cases: 95.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    0.0
2017-08-03    0.0
Freq: D, dtype: float64
new total cases: 99.0, old total cases: 95.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    1.333333
2017-08-05    1.333333
2017-08-06    1.333333
Freq: D, dtype: float64
new total cases: 101.0, old total cases: 99.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    0.285714
2017-08-08    0.285714
2017-08-09    0.285714
2017-08-10    0.285714
2017-08-11    0.285714
2017-08-12    0.285714
2017-08-13    0.285714
Freq: D, dtype: float64
new total cases: 103.0, old total cases: 101.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    1.0
2017-08-15    1.0
Freq: D, dtype: float64
new total cases: 104.0, old total cases: 103.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    1.0
Freq: D, dtype: float64
new total cases: 104.0, old total cases: 104.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    0.0
Freq: D, dtype: float64
new total cases: 105.0, old total cases: 104.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    1.0
Freq: D, dtype: float64
new total cases: 105.0, old total cases: 105.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    0.0
Freq: D, dtype: float64
new total cases: 105.0, old total cases: 105.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    0.0
Freq: D, dtype: float64
new total cases: 105.0, old total cases: 105.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    0.0
Freq: D, dtype: float64
new total cases: 105.0, old total cases: 105.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    0.0
Freq: D, dtype: float64
new total cases: 105.0, old total cases: 105.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    0.0
Freq: D, dtype: float64
new total cases: 106.0, old total cases: 105.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    1.0
Freq: D, dtype: float64
new total cases: 106.0, old total cases: 106.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    0.0
2017-08-26    0.0
Freq: D, dtype: float64
new total cases: 106.0, old total cases: 106.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    0.0
Freq: D, dtype: float64
new total cases: 106.0, old total cases: 106.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    0.0
Freq: D, dtype: float64

new date: 2017-06-28 00:00:00, old date: 2017-06-27 00:00:00
2017-06-28    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-06-29 00:00:00, old date: 2017-06-28 00:00:00
2017-06-29    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-06-30 00:00:00, old date: 2017-06-29 00:00:00
2017-06-30    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-01 00:00:00, old date: 2017-06-30 00:00:00
2017-07-01    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-02 00:00:00, old date: 2017-07-01 00:00:00
2017-07-02    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-03 00:00:00, old date: 2017-07-02 00:00:00
2017-07-03    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-04 00:00:00, old date: 2017-07-03 00:00:00
2017-07-04    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-05 00:00:00, old date: 2017-07-04 00:00:00
2017-07-05    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-06 00:00:00, old date: 2017-07-05 00:00:00
2017-07-06    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-07 00:00:00, old date: 2017-07-06 00:00:00
2017-07-07    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-10 00:00:00, old date: 2017-07-07 00:00:00
2017-07-08    0.0
2017-07-09    0.0
2017-07-10    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-11 00:00:00, old date: 2017-07-10 00:00:00
2017-07-11    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-12 00:00:00, old date: 2017-07-11 00:00:00
2017-07-12    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-13 00:00:00, old date: 2017-07-12 00:00:00
2017-07-13    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-14 00:00:00, old date: 2017-07-13 00:00:00
2017-07-14    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-15 00:00:00, old date: 2017-07-14 00:00:00
2017-07-15    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-16 00:00:00, old date: 2017-07-15 00:00:00
2017-07-16    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-17 00:00:00, old date: 2017-07-16 00:00:00
2017-07-17    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-18 00:00:00, old date: 2017-07-17 00:00:00
2017-07-18    0.0
Freq: D, dtype: float64
new total cases: 1.0, old total cases: 1.0
new date: 2017-07-19 00:00:00, old date: 2017-07-18 00:00:00
2017-07-19    0.0
Freq: D, dtype: float64
new total cases: 2.0, old total cases: 1.0
new date: 2017-07-20 00:00:00, old date: 2017-07-19 00:00:00
2017-07-20    1.0
Freq: D, dtype: float64
new total cases: 2.0, old total cases: 2.0
new date: 2017-07-21 00:00:00, old date: 2017-07-20 00:00:00
2017-07-21    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 2.0
new date: 2017-07-22 00:00:00, old date: 2017-07-21 00:00:00
2017-07-22    3.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-07-23 00:00:00, old date: 2017-07-22 00:00:00
2017-07-23    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-07-24 00:00:00, old date: 2017-07-23 00:00:00
2017-07-24    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-07-25 00:00:00, old date: 2017-07-24 00:00:00
2017-07-25    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-07-26 00:00:00, old date: 2017-07-25 00:00:00
2017-07-26    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-07-27 00:00:00, old date: 2017-07-26 00:00:00
2017-07-27    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-07-28 00:00:00, old date: 2017-07-27 00:00:00
2017-07-28    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-07-29 00:00:00, old date: 2017-07-28 00:00:00
2017-07-29    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-07-30 00:00:00, old date: 2017-07-29 00:00:00
2017-07-30    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-07-31 00:00:00, old date: 2017-07-30 00:00:00
2017-07-31    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-01 00:00:00, old date: 2017-07-31 00:00:00
2017-08-01    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-03 00:00:00, old date: 2017-08-01 00:00:00
2017-08-02    0.0
2017-08-03    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-06 00:00:00, old date: 2017-08-03 00:00:00
2017-08-04    0.0
2017-08-05    0.0
2017-08-06    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-13 00:00:00, old date: 2017-08-06 00:00:00
2017-08-07    0.0
2017-08-08    0.0
2017-08-09    0.0
2017-08-10    0.0
2017-08-11    0.0
2017-08-12    0.0
2017-08-13    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-15 00:00:00, old date: 2017-08-13 00:00:00
2017-08-14    0.0
2017-08-15    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-16 00:00:00, old date: 2017-08-15 00:00:00
2017-08-16    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-17 00:00:00, old date: 2017-08-16 00:00:00
2017-08-17    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-18 00:00:00, old date: 2017-08-17 00:00:00
2017-08-18    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-19 00:00:00, old date: 2017-08-18 00:00:00
2017-08-19    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-20 00:00:00, old date: 2017-08-19 00:00:00
2017-08-20    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-21 00:00:00, old date: 2017-08-20 00:00:00
2017-08-21    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-22 00:00:00, old date: 2017-08-21 00:00:00
2017-08-22    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-23 00:00:00, old date: 2017-08-22 00:00:00
2017-08-23    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-24 00:00:00, old date: 2017-08-23 00:00:00
2017-08-24    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-26 00:00:00, old date: 2017-08-24 00:00:00
2017-08-25    0.0
2017-08-26    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-27 00:00:00, old date: 2017-08-26 00:00:00
2017-08-27    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-28 00:00:00, old date: 2017-08-27 00:00:00
2017-08-28    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-29 00:00:00, old date: 2017-08-28 00:00:00
2017-08-29    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-30 00:00:00, old date: 2017-08-29 00:00:00
2017-08-30    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-08-31 00:00:00, old date: 2017-08-30 00:00:00
2017-08-31    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-01 00:00:00, old date: 2017-08-31 00:00:00
2017-09-01    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-02 00:00:00, old date: 2017-09-01 00:00:00
2017-09-02    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-03 00:00:00, old date: 2017-09-02 00:00:00
2017-09-03    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-04 00:00:00, old date: 2017-09-03 00:00:00
2017-09-04    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-05 00:00:00, old date: 2017-09-04 00:00:00
2017-09-05    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-06 00:00:00, old date: 2017-09-05 00:00:00
2017-09-06    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-07 00:00:00, old date: 2017-09-06 00:00:00
2017-09-07    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-08 00:00:00, old date: 2017-09-07 00:00:00
2017-09-08    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-09 00:00:00, old date: 2017-09-08 00:00:00
2017-09-09    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-10 00:00:00, old date: 2017-09-09 00:00:00
2017-09-10    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-11 00:00:00, old date: 2017-09-10 00:00:00
2017-09-11    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-12 00:00:00, old date: 2017-09-11 00:00:00
2017-09-12    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-13 00:00:00, old date: 2017-09-12 00:00:00
2017-09-13    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-14 00:00:00, old date: 2017-09-13 00:00:00
2017-09-14    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-15 00:00:00, old date: 2017-09-14 00:00:00
2017-09-15    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-16 00:00:00, old date: 2017-09-15 00:00:00
2017-09-16    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-17 00:00:00, old date: 2017-09-16 00:00:00
2017-09-17    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-18 00:00:00, old date: 2017-09-17 00:00:00
2017-09-18    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-19 00:00:00, old date: 2017-09-18 00:00:00
2017-09-19    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-20 00:00:00, old date: 2017-09-19 00:00:00
2017-09-20    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-21 00:00:00, old date: 2017-09-20 00:00:00
2017-09-21    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-22 00:00:00, old date: 2017-09-21 00:00:00
2017-09-22    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-23 00:00:00, old date: 2017-09-22 00:00:00
2017-09-23    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-24 00:00:00, old date: 2017-09-23 00:00:00
2017-09-24    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-25 00:00:00, old date: 2017-09-24 00:00:00
2017-09-25    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-26 00:00:00, old date: 2017-09-25 00:00:00
2017-09-26    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-27 00:00:00, old date: 2017-09-26 00:00:00
2017-09-27    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-28 00:00:00, old date: 2017-09-27 00:00:00
2017-09-28    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-09-30 00:00:00, old date: 2017-09-28 00:00:00
2017-09-29    0.0
2017-09-30    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-01 00:00:00, old date: 2017-09-30 00:00:00
2017-10-01    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-02 00:00:00, old date: 2017-10-01 00:00:00
2017-10-02    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-03 00:00:00, old date: 2017-10-02 00:00:00
2017-10-03    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-04 00:00:00, old date: 2017-10-03 00:00:00
2017-10-04    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-05 00:00:00, old date: 2017-10-04 00:00:00
2017-10-05    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-08 00:00:00, old date: 2017-10-05 00:00:00
2017-10-06    0.0
2017-10-07    0.0
2017-10-08    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-09 00:00:00, old date: 2017-10-08 00:00:00
2017-10-09    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-10 00:00:00, old date: 2017-10-09 00:00:00
2017-10-10    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-11 00:00:00, old date: 2017-10-10 00:00:00
2017-10-11    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-14 00:00:00, old date: 2017-10-11 00:00:00
2017-10-12    0.0
2017-10-13    0.0
2017-10-14    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-16 00:00:00, old date: 2017-10-14 00:00:00
2017-10-15    0.0
2017-10-16    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-17 00:00:00, old date: 2017-10-16 00:00:00
2017-10-17    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-21 00:00:00, old date: 2017-10-17 00:00:00
2017-10-18    0.0
2017-10-19    0.0
2017-10-20    0.0
2017-10-21    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-22 00:00:00, old date: 2017-10-21 00:00:00
2017-10-22    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-25 00:00:00, old date: 2017-10-22 00:00:00
2017-10-23    0.0
2017-10-24    0.0
2017-10-25    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-28 00:00:00, old date: 2017-10-25 00:00:00
2017-10-26    0.0
2017-10-27    0.0
2017-10-28    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-29 00:00:00, old date: 2017-10-28 00:00:00
2017-10-29    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-10-30 00:00:00, old date: 2017-10-29 00:00:00
2017-10-30    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-11-03 00:00:00, old date: 2017-10-30 00:00:00
2017-10-31    0.0
2017-11-01    0.0
2017-11-02    0.0
2017-11-03    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-11-04 00:00:00, old date: 2017-11-03 00:00:00
2017-11-04    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-11-05 00:00:00, old date: 2017-11-04 00:00:00
2017-11-05    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-11-06 00:00:00, old date: 2017-11-05 00:00:00
2017-11-06    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-11-07 00:00:00, old date: 2017-11-06 00:00:00
2017-11-07    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-11-08 00:00:00, old date: 2017-11-07 00:00:00
2017-11-08    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-11-19 00:00:00, old date: 2017-11-08 00:00:00
2017-11-09    0.0
2017-11-10    0.0
2017-11-11    0.0
2017-11-12    0.0
2017-11-13    0.0
2017-11-14    0.0
2017-11-15    0.0
2017-11-16    0.0
2017-11-17    0.0
2017-11-18    0.0
2017-11-19    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-11-26 00:00:00, old date: 2017-11-19 00:00:00
2017-11-20    0.0
2017-11-21    0.0
2017-11-22    0.0
2017-11-23    0.0
2017-11-24    0.0
2017-11-25    0.0
2017-11-26    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-12-17 00:00:00, old date: 2017-11-26 00:00:00
2017-11-27    0.0
2017-11-28    0.0
2017-11-29    0.0
2017-11-30    0.0
2017-12-01    0.0
2017-12-02    0.0
2017-12-03    0.0
2017-12-04    0.0
2017-12-05    0.0
2017-12-06    0.0
2017-12-07    0.0
2017-12-08    0.0
2017-12-09    0.0
2017-12-10    0.0
2017-12-11    0.0
2017-12-12    0.0
2017-12-13    0.0
2017-12-14    0.0
2017-12-15    0.0
2017-12-16    0.0
2017-12-17    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2017-12-31 00:00:00, old date: 2017-12-17 00:00:00
2017-12-18    0.0
2017-12-19    0.0
2017-12-20    0.0
2017-12-21    0.0
2017-12-22    0.0
2017-12-23    0.0
2017-12-24    0.0
2017-12-25    0.0
2017-12-26    0.0
2017-12-27    0.0
2017-12-28    0.0
2017-12-29    0.0
2017-12-30    0.0
2017-12-31    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2018-01-07 00:00:00, old date: 2017-12-31 00:00:00
2018-01-01    0.0
2018-01-02    0.0
2018-01-03    0.0
2018-01-04    0.0
2018-01-05    0.0
2018-01-06    0.0
2018-01-07    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2018-01-14 00:00:00, old date: 2018-01-07 00:00:00
2018-01-08    0.0
2018-01-09    0.0
2018-01-10    0.0
2018-01-11    0.0
2018-01-12    0.0
2018-01-13    0.0
2018-01-14    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2018-01-21 00:00:00, old date: 2018-01-14 00:00:00
2018-01-15    0.0
2018-01-16    0.0
2018-01-17    0.0
2018-01-18    0.0
2018-01-19    0.0
2018-01-20    0.0
2018-01-21    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2018-01-28 00:00:00, old date: 2018-01-21 00:00:00
2018-01-22    0.0
2018-01-23    0.0
2018-01-24    0.0
2018-01-25    0.0
2018-01-26    0.0
2018-01-27    0.0
2018-01-28    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2018-02-04 00:00:00, old date: 2018-01-28 00:00:00
2018-01-29    0.0
2018-01-30    0.0
2018-01-31    0.0
2018-02-01    0.0
2018-02-02    0.0
2018-02-03    0.0
2018-02-04    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2018-02-11 00:00:00, old date: 2018-02-04 00:00:00
2018-02-05    0.0
2018-02-06    0.0
2018-02-07    0.0
2018-02-08    0.0
2018-02-09    0.0
2018-02-10    0.0
2018-02-11    0.0
Freq: D, dtype: float64
new total cases: 5.0, old total cases: 5.0
new date: 2018-02-18 00:00:00, old date: 2018-02-11 00:00:00
2018-02-12    0.0
2018-02-13    0.0
2018-02-14    0.0
2018-02-15    0.0
2018-02-16    0.0
2018-02-17    0.0
2018-02-18    0.0
Freq: D, dtype: float64
new total cases: 0.0, old total cases: nan
new date: 2017-05-27 00:00:00, old date: 2017-05-22 00:00:00
2017-05-23   NaN
2017-05-24   NaN
2017-05-25   NaN
2017-05-26   NaN
2017-05-27   NaN
Freq: D, dtype: float64
new total cases: 0.0, old total cases: 0.0
new date: 2017-05-30 00:00:00, old date: 2017-05-27 00:00:00
2017-05-28    0.0
2017-05-29    0.0
2017-05-30    0.0
Freq: D, dtype: float64
new total cases: 0.0, old total cases: 0.0
new date: 2017-06-04 00:00:00, old date: 2017-05-30 00:00:00
2017-05-31    0.0
2017-06-01    0.0
2017-06-02    0.0
2017-06-03    0.0
2017-06-04    0.0
Freq: D, dtype: float64
new total cases: 0.0, old total cases: 0.0
new date: 2017-06-07 00:00:00, old date: 2017-06-04 00:00:00
2017-06-05    0.0
2017-06-06    0.0
2017-06-07    0.0
Freq: D, dtype: float64
new total cases: 0.0, old total cases: 0.0
new date: 2017-06-10 00:00:00, old date: 2017-06-07 00:00:00
2017-06-08    0.0
2017-06-09    0.0

In [14]:
yemen_cholera_death_data_diff

,YE-AB,YE-AD,YE-AM,YE-BA,YE-DA,YE-DH,YE-HD,YE-HJ,YE-HU,YE-IB,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
2017-05-23,1.000000,0.000000,2.400000,0.400000,0.200000,1.600000,NaN,4.000000,1.600000,4.000000,...,0.200000,0.200000,NaN,2.200000,0.800000,0.600000,NaN,NaN,1.400000,1.400000
2017-05-24,1.000000,0.000000,2.400000,0.400000,0.200000,1.600000,NaN,4.000000,1.600000,4.000000,...,0.200000,0.200000,NaN,2.200000,0.800000,0.600000,NaN,NaN,1.400000,1.400000
2017-05-25,1.000000,0.000000,2.400000,0.400000,0.200000,1.600000,NaN,4.000000,1.600000,4.000000,...,0.200000,0.200000,NaN,2.200000,0.800000,0.600000,NaN,NaN,1.400000,1.400000
2017-05-26,1.000000,0.000000,2.400000,0.400000,0.200000,1.600000,NaN,4.000000,1.600000,4.000000,...,0.200000,0.200000,NaN,2.200000,0.800000,0.600000,NaN,NaN,1.400000,1.400000
2017-05-27,1.000000,0.000000,2.400000,0.400000,0.200000,1.600000,NaN,4.000000,1.600000,4.000000,...,0.200000,0.200000,NaN,2.200000,0.800000,0.600000,NaN,NaN,1.400000,1.400000
2017-05-28,0.333333,1.333333,6.333333,1.000000,0.666667,1.000000,NaN,2.666667,0.333333,0.000000,...,0.333333,0.000000,NaN,1.666667,0.333333,0.000000,0.0,0.0,1.333333,2.666667
2017-05-29,0.333333,1.333333,6.333333,1.000000,0.666667,1.000000,NaN,2.666667,0.333333,0.000000,...,0.333333,0.000000,NaN,1.666667,0.333333,0.000000,0.0,0.0,1.333333,2.666667
2017-05-30,0.333333,1.333333,6.333333,1.000000,0.666667,1.000000,NaN,2.666667,0.333333,0.000000,...,0.333333,0.000000,NaN,1.666667,0.333333,0.000000,0.0,0.0,1.333333,2.666667
2017-05-31,0.000000,1.400000,2.800000,0.400000,0.600000,1.600000,NaN,6.400000,3.600000,5.600000,...,0.000000,0.000000,NaN,2.600000,1.200000,0.200000,0.0,0.0,1.200000,2.000000
2017-06-01,0.000000,1.400000,2.800000,0.400000,0.600000,1.600000,NaN,6.400000,3.600000,5.600000,...,0.000000,0.000000,NaN,2.600000,1.200000,0.200000,0.0,0.0,1.200000,2.000000
2017-06-02,0.000000,1.400000,2.800000,0.400000,0.600000,1.600000,NaN,6.400000,3.600000,5.600000,...,0.000000,0.000000,NaN,2.600000,1.200000,0.200000,0.0,0.0,1.200000,2.000000
2017-06-03,0.000000,1.400000,2.800000,0.400000,0.600000,1.600000,NaN,6.400000,3.600000,5.600000,...,0.000000,0.000000,NaN,2.600000,1.200000,0.200000,0.0,0.0,1.200000,2.000000
2017-06-04,0.000000,1.400000,2.800000,0.400000,0.600000,1.600000,NaN,6.400000,3.600000,5.600000,...,0.000000,0.000000,NaN,2.600000,1.200000,0.200000,0.0,0.0,1.200000,2.000000
2017-06-05,0.333333,0.000000,1.333333,0.333333,1.666667,1.000000,NaN,9.333333,5.000000,8.666667,...,1.000000,0.000000,NaN,1.666667,3.333333,0.666667,0.0,0.0,1.000000,2.333333
2017-06-06,0.333333,0.000000,1.333333,0.333333,1.666667,1.000000,NaN,9.333333,5.000000,8.666667,...,1.000000,0.000000,NaN,1.666667,3.333333,0.666667,0.0,0.0,1.000000,2.333333
2017-06-07,0.333333,0.000000,1.333333,0.333333,1.666667,1.000000,NaN,9.333333,5.000000,8.666667,...,1.000000,0.000000,NaN,1.666667,3.333333,0.666667,0.0,0.0,1.000000,2.333333
2017-06-08,1.333333,2.666667,3.666667,1.333333,2.000000,1.666667,NaN,5.333333,4.333333,6.000000,...,1.000000,0.000000,NaN,0.666667,4.000000,0.666667,0.0,0.0,3.333333,4.333333
2017-06-09,1.333333,2.666667,3.666667,1.333333,2.000000,1.666667,NaN,5.333333,4.333333,6.000000,...,1.000000,0.000000,NaN,0.666667,4.000000,0.666667,0.0,0.0,3.333333,4.333333
2017-06-10,1.333333,2.666667,3.666667,1.333333,2.000000,1.666667,NaN,5.333333,4.333333,6.000000,...,1.000000,0.000000,NaN,0.666667,4.000000,0.666667,0.0,0.0,3.333333,4.333333
2017-06-11,0.000000,0.000000,0.500000,0.000000,0.500000,0.500000,NaN,0.000000,0.000000,2.500000,...,0.000000,0.000000,0.0,0.000000,2.000000,0.500000,0.0,0.0,0.000000,2.500000
2017-06-12,0.000000,0.000000,0.500000,0.000000,0.500000,0.500000,NaN,0.000000,0.000000,2.500000,...,0.000000,0.000000,0.0,0.000000,2.000000,0.500000,0.0,0.0,0.000000,2.500000
2017-06-13,0.000000,0.000000,3.000000,0.000000,3.000000,6.000000,NaN,0.000000,7.000000,2.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,5.000000,0.0,0.0,2.000000,4.000000
2017-06-14,0.000000,0.000000,3.000000,0.000000,0.000000,2.000000,NaN,0.000000,1.000000,2.000000,...,0.000000,0.000000,0.0,2.000000,1.000000,0.000000,0.0,0.0,2.000000,2.000000
2017-06-15,0.000000,2.000000,1.000000,0.000000,0.666667,3.666667,NaN,11.666667,3.666667,4.333333,...,0.000000,0.666667,0.0,1.666667,1.000000,0.666667,0.0,0.0,1.666667,4.000000
2017-06-16,0.000000,2.000000,1.000000,0.000000,0.666667,3.666667,NaN,11.666667,3.666667,4.333333,...,0.000000,0.666667,0.0,1.666667,1.000000,0.666667,0.0,0.0,1.666667,4.000000
2017-06-17,0.000000,2.000000,1.000000,0.000000,0.666667,3.666667,NaN,11.666667,3.666667,4.333333,...,0.000000,0.666667,0.0,1.666667,1.000000,0.666667,0.0,0.0,1.666667,4.000000
2017-06-18,0.000000,0.000000,5.000000,0.000000,5.000000,1.000000,NaN,0.000000,4.000000,12.000000,...,0.000000,0.000000,1.0,0.000000,10.000000,2.000000,0.0,0.0,5.000000,1.000000
2017-06-19,0.000000,1.000000,3.000000,0.000000,0.000000,3.000000,NaN,0.000000,2.000000,8.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,7.000000
2017-06-20,0.000000,1.000000,4.000000,0.000000,2.000000,1.000000,NaN,5.000000,5.000000,3.000000,...,4.000000,0.000000,0.0,0.000000,3.000000,1.000000,0.0,0.0,3.000000,3.000000
2017-06-21,0.000000,1.000000,2.000000,0.000000,1.000000,1.000000,NaN,1.000000,8.000000,4.000000,...,0.000000,0.000000,0.0,0.000000,1.000000,1.000000,1.0,0.0,1.000000,6.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-01-20,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.0,0.142857,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-01-21,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.0,0.142857,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-01-22,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-23,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-24,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-25,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-26,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-27,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-28,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-29,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-01-30,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-01-31,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-02-01,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-02-02,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-02-03,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-02-04,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-02-05,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-06,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-07,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-08,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-09,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-10,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-11,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000

In [15]:
yemen_cholera_case_data_diff = yemen_cholera_case_data_diff.fillna(0)
yemen_cholera_death_data_diff = yemen_cholera_death_data_diff.fillna(0)

In [74]:
diff_case_fig, diff_case_ax = plt.subplots(1,1, figsize=(12,10))
yemen_cholera_case_data_diff.plot(ax = diff_case_ax, title = 'new cases over time')
diff_case_ax.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
diff_case_fig.savefig('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_plots/new_case_data_plot.png', bbox_inches = 'tight')
plt.close('all')

In [75]:
diff_death_fig, diff_death_ax = plt.subplots(1,1, figsize=(12,10))
yemen_cholera_death_data_diff.plot(ax = diff_death_ax, title = 'new deaths over time')
diff_death_ax.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
diff_death_fig.savefig('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_plots/new_death_data_plot.png', bbox_inches = 'tight')
plt.close('all')

In [78]:
yemen_cholera_case_data_diff.to_csv('/Users/Rohil/Documents/iGEM/yemen/yemen_cholera_case_data_differenced.csv')

In [25]:
yemen_cholera_case_data_diff

,YE-AB,YE-AD,YE-AM,YE-BA,YE-DA,YE-DH,YE-HD,YE-HJ,YE-HU,YE-IB,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
2017-05-23,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,0.000000,263.200000,213.200000,159.800000,...,32.000000,11.400000,0.000000,221.600000,42.400000,665.600000,0.000000,0.0,313.600000,320.600000
2017-05-24,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,0.000000,263.200000,213.200000,159.800000,...,32.000000,11.400000,0.000000,221.600000,42.400000,665.600000,0.000000,0.0,313.600000,320.600000
2017-05-25,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,0.000000,263.200000,213.200000,159.800000,...,32.000000,11.400000,0.000000,221.600000,42.400000,665.600000,0.000000,0.0,313.600000,320.600000
2017-05-26,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,0.000000,263.200000,213.200000,159.800000,...,32.000000,11.400000,0.000000,221.600000,42.400000,665.600000,0.000000,0.0,313.600000,320.600000
2017-05-27,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,0.000000,263.200000,213.200000,159.800000,...,32.000000,11.400000,0.000000,221.600000,42.400000,665.600000,0.000000,0.0,313.600000,320.600000
2017-05-28,74.000000,126.000000,335.000000,200.000000,150.666667,175.333333,0.000000,387.666667,1467.333333,130.000000,...,47.666667,18.333333,0.000000,217.333333,47.000000,385.333333,6.666667,1.0,280.333333,335.000000
2017-05-29,74.000000,126.000000,335.000000,200.000000,150.666667,175.333333,0.000000,387.666667,1467.333333,130.000000,...,47.666667,18.333333,0.000000,217.333333,47.000000,385.333333,6.666667,1.0,280.333333,335.000000
2017-05-30,74.000000,126.000000,335.000000,200.000000,150.666667,175.333333,0.000000,387.666667,1467.333333,130.000000,...,47.666667,18.333333,0.000000,217.333333,47.000000,385.333333,6.666667,1.0,280.333333,335.000000
2017-05-31,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,0.000000,544.200000,493.000000,341.400000,...,9.800000,7.400000,0.000000,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
2017-06-01,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,0.000000,544.200000,493.000000,341.400000,...,9.800000,7.400000,0.000000,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
2017-06-02,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,0.000000,544.200000,493.000000,341.400000,...,9.800000,7.400000,0.000000,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
2017-06-03,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,0.000000,544.200000,493.000000,341.400000,...,9.800000,7.400000,0.000000,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
2017-06-04,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,0.000000,544.200000,493.000000,341.400000,...,9.800000,7.400000,0.000000,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
2017-06-05,83.666667,0.333333,541.333333,137.666667,208.666667,261.666667,0.000000,453.333333,599.333333,589.000000,...,68.000000,31.333333,0.000000,227.333333,128.000000,833.666667,2.333333,0.0,400.666667,539.666667
2017-06-06,83.666667,0.333333,541.333333,137.666667,208.666667,261.666667,0.000000,453.333333,599.333333,589.000000,...,68.000000,31.333333,0.000000,227.333333,128.000000,833.666667,2.333333,0.0,400.666667,539.666667
2017-06-07,83.666667,0.333333,541.333333,137.666667,208.666667,261.666667,0.000000,453.333333,599.333333,589.000000,...,68.000000,31.333333,0.000000,227.333333,128.000000,833.666667,2.333333,0.0,400.666667,539.666667
2017-06-08,103.000000,229.000000,674.666667,227.666667,424.000000,395.333333,0.000000,685.000000,993.000000,860.666667,...,106.000000,16.666667,0.000000,310.000000,191.333333,883.666667,3.666667,2.0,589.666667,648.333333
2017-06-09,103.000000,229.000000,674.666667,227.666667,424.000000,395.333333,0.000000,685.000000,993.000000,860.666667,...,106.000000,16.666667,0.000000,310.000000,191.333333,883.666667,3.666667,2.0,589.666667,648.333333
2017-06-10,103.000000,229.000000,674.666667,227.666667,424.000000,395.333333,0.000000,685.000000,993.000000,860.666667,...,106.000000,16.666667,0.000000,310.000000,191.333333,883.666667,3.666667,2.0,589.666667,648.333333
2017-06-11,65.500000,0.000000,340.000000,57.500000,78.500000,141.500000,0.000000,173.500000,311.000000,433.500000,...,98.500000,12.000000,0.000000,139.500000,79.000000,287.500000,1.000000,0.0,89.500000,269.500000
2017-06-12,65.500000,0.000000,340.000000,57.500000,78.500000,141.500000,0.000000,173.500000,311.000000,433.500000,...,98.500000,12.000000,0.000000,139.500000,79.000000,287.500000,1.000000,0.0,89.500000,269.500000
2017-06-13,64.000000,0.000000,522.000000,199.000000,173.000000,241.000000,0.000000,827.000000,913.000000,506.000000,...,2.000000,16.000000,24.000000,229.000000,24.000000,548.000000,0.000000,0.0,694.000000,999.000000
2017-06-14,96.000000,1.000000,587.000000,230.000000,77.000000,292.000000,0.000000,13.000000,825.000000,327.000000,...,235.000000,22.000000,8.000000,181.000000,265.000000,775.000000,1.000000,0.0,389.000000,554.000000
2017-06-15,107.666667,278.333333,631.666667,162.000000,297.333333,411.666667,0.000000,729.666667,904.666667,529.333333,...,36.666667,16.666667,7.333333,240.000000,47.333333,896.666667,6.333333,0.0,488.333333,463.666667
2017-06-16,107.666667,278.333333,631.666667,162.000000,297.333333,411.666667,0.000000,729.666667,904.666667,529.333333,...,36.666667,16.666667,7.333333,240.000000,47.333333,896.666667,6.333333,0.0,488.333333,463.666667
2017-06-17,107.666667,278.333333,631.666667,162.000000,297.333333,411.666667,0.000000,729.666667,904.666667,529.333333,...,36.666667,16.666667,7.333333,240.000000,47.333333,896.666667,6.333333,0.0,488.333333,463.666667
2017-06-18,100.000000,215.000000,729.000000,0.000000,803.000000,407.000000,0.000000,776.000000,1001.000000,921.000000,...,314.000000,49.000000,10.000000,287.000000,331.000000,1008.000000,5.000000,17.0,459.000000,539.000000
2017-06-19,110.000000,354.000000,750.000000,122.000000,239.000000,413.000000,0.000000,8.000000,843.000000,551.000000,...,25.000000,29.000000,13.000000,294.000000,5.000000,691.000000,1.000000,12.0,497.000000,338.000000
2017-06-20,1.000000,219.000000,836.000000,2.000000,160.000000,438.000000,0.000000,1276.000000,913.000000,482.000000,...,213.000000,0.000000,16.000000,98.000000,175.000000,1404.000000,1.000000,4.0,394.000000,581.000000
2017-06-21,4.000000,198.000000,818.000000,416.000000,381.000000,475.000000,0.000000,236.000000,956.000000,223.000000,...,9.000000,32.000000,12.000000,252.000000,107.000000,949.000000,45.000000,0.0,211.000000,400.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-01-20,0.000000,2.714286,98.000000,77.000000,0.000000,153.714286,0.000000,398.000000,232.428571,114.714286,...,0.000000,0.000000,0.000000,66.714286,64.285714,163.428571,0.285714,0.0,96.857143,97.000000
2018-01-21,0.000000,2.714286,98.000000,77.000000,0.000000,153.714286,0.000000,398.000000,232.428571,114.714286,...,0.000000,0.000000,0.000000,66.714286,64.285714,163.428571,0.285714,0.0,96.857143,97.000000
2018-01-22,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-23,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-24,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-25,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-26,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-27,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-28,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,73.285714,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
2018-01-29,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-01-30,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-01-31,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-02-01,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-02-02,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-02-03,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-02-04,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,42.142857,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
2018-02-05,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-06,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-07,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-08,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-09,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-10,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-11,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,66.000000,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
2018-02-12,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-13,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-14,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-15,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-16,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-17,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
2018-02-18,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,74.285714,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143

In [24]:
yemen_cholera_death_data_diff

,YE-AB,YE-AD,YE-AM,YE-BA,YE-DA,YE-DH,YE-HD,YE-HJ,YE-HU,YE-IB,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
2017-05-23,1.000000,0.000000,2.400000,0.400000,0.200000,1.600000,0.0,4.000000,1.600000,4.000000,...,0.200000,0.200000,0.0,2.200000,0.800000,0.600000,0.0,0.0,1.400000,1.400000
2017-05-24,1.000000,0.000000,2.400000,0.400000,0.200000,1.600000,0.0,4.000000,1.600000,4.000000,...,0.200000,0.200000,0.0,2.200000,0.800000,0.600000,0.0,0.0,1.400000,1.400000
2017-05-25,1.000000,0.000000,2.400000,0.400000,0.200000,1.600000,0.0,4.000000,1.600000,4.000000,...,0.200000,0.200000,0.0,2.200000,0.800000,0.600000,0.0,0.0,1.400000,1.400000
2017-05-26,1.000000,0.000000,2.400000,0.400000,0.200000,1.600000,0.0,4.000000,1.600000,4.000000,...,0.200000,0.200000,0.0,2.200000,0.800000,0.600000,0.0,0.0,1.400000,1.400000
2017-05-27,1.000000,0.000000,2.400000,0.400000,0.200000,1.600000,0.0,4.000000,1.600000,4.000000,...,0.200000,0.200000,0.0,2.200000,0.800000,0.600000,0.0,0.0,1.400000,1.400000
2017-05-28,0.333333,1.333333,6.333333,1.000000,0.666667,1.000000,0.0,2.666667,0.333333,0.000000,...,0.333333,0.000000,0.0,1.666667,0.333333,0.000000,0.0,0.0,1.333333,2.666667
2017-05-29,0.333333,1.333333,6.333333,1.000000,0.666667,1.000000,0.0,2.666667,0.333333,0.000000,...,0.333333,0.000000,0.0,1.666667,0.333333,0.000000,0.0,0.0,1.333333,2.666667
2017-05-30,0.333333,1.333333,6.333333,1.000000,0.666667,1.000000,0.0,2.666667,0.333333,0.000000,...,0.333333,0.000000,0.0,1.666667,0.333333,0.000000,0.0,0.0,1.333333,2.666667
2017-05-31,0.000000,1.400000,2.800000,0.400000,0.600000,1.600000,0.0,6.400000,3.600000,5.600000,...,0.000000,0.000000,0.0,2.600000,1.200000,0.200000,0.0,0.0,1.200000,2.000000
2017-06-01,0.000000,1.400000,2.800000,0.400000,0.600000,1.600000,0.0,6.400000,3.600000,5.600000,...,0.000000,0.000000,0.0,2.600000,1.200000,0.200000,0.0,0.0,1.200000,2.000000
2017-06-02,0.000000,1.400000,2.800000,0.400000,0.600000,1.600000,0.0,6.400000,3.600000,5.600000,...,0.000000,0.000000,0.0,2.600000,1.200000,0.200000,0.0,0.0,1.200000,2.000000
2017-06-03,0.000000,1.400000,2.800000,0.400000,0.600000,1.600000,0.0,6.400000,3.600000,5.600000,...,0.000000,0.000000,0.0,2.600000,1.200000,0.200000,0.0,0.0,1.200000,2.000000
2017-06-04,0.000000,1.400000,2.800000,0.400000,0.600000,1.600000,0.0,6.400000,3.600000,5.600000,...,0.000000,0.000000,0.0,2.600000,1.200000,0.200000,0.0,0.0,1.200000,2.000000
2017-06-05,0.333333,0.000000,1.333333,0.333333,1.666667,1.000000,0.0,9.333333,5.000000,8.666667,...,1.000000,0.000000,0.0,1.666667,3.333333,0.666667,0.0,0.0,1.000000,2.333333
2017-06-06,0.333333,0.000000,1.333333,0.333333,1.666667,1.000000,0.0,9.333333,5.000000,8.666667,...,1.000000,0.000000,0.0,1.666667,3.333333,0.666667,0.0,0.0,1.000000,2.333333
2017-06-07,0.333333,0.000000,1.333333,0.333333,1.666667,1.000000,0.0,9.333333,5.000000,8.666667,...,1.000000,0.000000,0.0,1.666667,3.333333,0.666667,0.0,0.0,1.000000,2.333333
2017-06-08,1.333333,2.666667,3.666667,1.333333,2.000000,1.666667,0.0,5.333333,4.333333,6.000000,...,1.000000,0.000000,0.0,0.666667,4.000000,0.666667,0.0,0.0,3.333333,4.333333
2017-06-09,1.333333,2.666667,3.666667,1.333333,2.000000,1.666667,0.0,5.333333,4.333333,6.000000,...,1.000000,0.000000,0.0,0.666667,4.000000,0.666667,0.0,0.0,3.333333,4.333333
2017-06-10,1.333333,2.666667,3.666667,1.333333,2.000000,1.666667,0.0,5.333333,4.333333,6.000000,...,1.000000,0.000000,0.0,0.666667,4.000000,0.666667,0.0,0.0,3.333333,4.333333
2017-06-11,0.000000,0.000000,0.500000,0.000000,0.500000,0.500000,0.0,0.000000,0.000000,2.500000,...,0.000000,0.000000,0.0,0.000000,2.000000,0.500000,0.0,0.0,0.000000,2.500000
2017-06-12,0.000000,0.000000,0.500000,0.000000,0.500000,0.500000,0.0,0.000000,0.000000,2.500000,...,0.000000,0.000000,0.0,0.000000,2.000000,0.500000,0.0,0.0,0.000000,2.500000
2017-06-13,0.000000,0.000000,3.000000,0.000000,3.000000,6.000000,0.0,0.000000,7.000000,2.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,5.000000,0.0,0.0,2.000000,4.000000
2017-06-14,0.000000,0.000000,3.000000,0.000000,0.000000,2.000000,0.0,0.000000,1.000000,2.000000,...,0.000000,0.000000,0.0,2.000000,1.000000,0.000000,0.0,0.0,2.000000,2.000000
2017-06-15,0.000000,2.000000,1.000000,0.000000,0.666667,3.666667,0.0,11.666667,3.666667,4.333333,...,0.000000,0.666667,0.0,1.666667,1.000000,0.666667,0.0,0.0,1.666667,4.000000
2017-06-16,0.000000,2.000000,1.000000,0.000000,0.666667,3.666667,0.0,11.666667,3.666667,4.333333,...,0.000000,0.666667,0.0,1.666667,1.000000,0.666667,0.0,0.0,1.666667,4.000000
2017-06-17,0.000000,2.000000,1.000000,0.000000,0.666667,3.666667,0.0,11.666667,3.666667,4.333333,...,0.000000,0.666667,0.0,1.666667,1.000000,0.666667,0.0,0.0,1.666667,4.000000
2017-06-18,0.000000,0.000000,5.000000,0.000000,5.000000,1.000000,0.0,0.000000,4.000000,12.000000,...,0.000000,0.000000,1.0,0.000000,10.000000,2.000000,0.0,0.0,5.000000,1.000000
2017-06-19,0.000000,1.000000,3.000000,0.000000,0.000000,3.000000,0.0,0.000000,2.000000,8.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,7.000000
2017-06-20,0.000000,1.000000,4.000000,0.000000,2.000000,1.000000,0.0,5.000000,5.000000,3.000000,...,4.000000,0.000000,0.0,0.000000,3.000000,1.000000,0.0,0.0,3.000000,3.000000
2017-06-21,0.000000,1.000000,2.000000,0.000000,1.000000,1.000000,0.0,1.000000,8.000000,4.000000,...,0.000000,0.000000,0.0,0.000000,1.000000,1.000000,1.0,0.0,1.000000,6.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-01-20,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.0,0.142857,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-01-21,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.0,0.142857,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-01-22,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-23,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-24,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-25,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-26,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-27,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-28,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.285714,0.000000,0.142857,0.0,0.0,0.000000,0.000000
2018-01-29,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-01-30,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-01-31,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-02-01,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-02-02,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-02-03,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-02-04,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.142857
2018-02-05,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-06,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-07,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-08,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-09,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-10,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-11,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.0,0.000000,0.142857,0.142857,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2018-02-18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000

In [26]:
yemen_cholera_death_data_diff.to_csv('/Users/Rohil/Documents/iGEM/yemen/yemen_cholera_death_data_differenced.csv')

In [150]:
def scale(train, test):
    # fit scaler
    scaler = MinMaxScaler(feature_range=(-1, 1))
    scaler = scaler.fit(train)
    # transform train
    train = train.reshape(train.shape[0], train.shape[1])
    train_scaled = scaler.transform(train)
    # transform test
    test = test.reshape(test.shape[0], test.shape[1])
    test_scaled = scaler.transform(test)
    return (scaler, train_scaled, test_scaled)

In [10]:
yemen_cholera_case_data_formatted.to_csv('/Users/Rohil/Documents/iGEM/yemen_cholera_data_crosstab.csv')

In [2]:
import pandas as pd

In [3]:
yemen_cholera_case_data_diff = pd.read_csv('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_data/yemen_cholera_case_data_differenced.csv')

In [4]:
yemen_cholera_case_data_diff

,date,YE-AB,YE-AD,YE-AM,YE-BA,YE-DA,YE-DH,YE-HD-AL,YE-HJ,YE-HU,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
0,23-05-17,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,0.000000,263.200000,213.200000,...,32.000000,11.400000,0.000000,221.600000,42.400000,665.600000,0.000000,0.0,313.600000,320.600000
1,24-05-17,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,0.000000,263.200000,213.200000,...,32.000000,11.400000,0.000000,221.600000,42.400000,665.600000,0.000000,0.0,313.600000,320.600000
2,25-05-17,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,0.000000,263.200000,213.200000,...,32.000000,11.400000,0.000000,221.600000,42.400000,665.600000,0.000000,0.0,313.600000,320.600000
3,26-05-17,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,0.000000,263.200000,213.200000,...,32.000000,11.400000,0.000000,221.600000,42.400000,665.600000,0.000000,0.0,313.600000,320.600000
4,27-05-17,59.400000,60.800000,445.800000,207.600000,103.600000,178.000000,0.000000,263.200000,213.200000,...,32.000000,11.400000,0.000000,221.600000,42.400000,665.600000,0.000000,0.0,313.600000,320.600000
5,28-05-17,74.000000,126.000000,335.000000,200.000000,150.666667,175.333333,0.000000,387.666667,1467.333333,...,47.666667,18.333333,0.000000,217.333333,47.000000,385.333333,6.666667,1.0,280.333333,335.000000
6,29-05-17,74.000000,126.000000,335.000000,200.000000,150.666667,175.333333,0.000000,387.666667,1467.333333,...,47.666667,18.333333,0.000000,217.333333,47.000000,385.333333,6.666667,1.0,280.333333,335.000000
7,30-05-17,74.000000,126.000000,335.000000,200.000000,150.666667,175.333333,0.000000,387.666667,1467.333333,...,47.666667,18.333333,0.000000,217.333333,47.000000,385.333333,6.666667,1.0,280.333333,335.000000
8,31-05-17,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,0.000000,544.200000,493.000000,...,9.800000,7.400000,0.000000,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
9,01-06-17,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,0.000000,544.200000,493.000000,...,9.800000,7.400000,0.000000,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
10,02-06-17,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,0.000000,544.200000,493.000000,...,9.800000,7.400000,0.000000,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
11,03-06-17,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,0.000000,544.200000,493.000000,...,9.800000,7.400000,0.000000,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
12,04-06-17,66.600000,357.800000,504.600000,140.200000,86.200000,205.400000,0.000000,544.200000,493.000000,...,9.800000,7.400000,0.000000,253.600000,47.800000,537.200000,2.400000,0.2,353.600000,241.800000
13,05-06-17,83.666667,0.333333,541.333333,137.666667,208.666667,261.666667,0.000000,453.333333,599.333333,...,68.000000,31.333333,0.000000,227.333333,128.000000,833.666667,2.333333,0.0,400.666667,539.666667
14,06-06-17,83.666667,0.333333,541.333333,137.666667,208.666667,261.666667,0.000000,453.333333,599.333333,...,68.000000,31.333333,0.000000,227.333333,128.000000,833.666667,2.333333,0.0,400.666667,539.666667
15,07-06-17,83.666667,0.333333,541.333333,137.666667,208.666667,261.666667,0.000000,453.333333,599.333333,...,68.000000,31.333333,0.000000,227.333333,128.000000,833.666667,2.333333,0.0,400.666667,539.666667
16,08-06-17,103.000000,229.000000,674.666667,227.666667,424.000000,395.333333,0.000000,685.000000,993.000000,...,106.000000,16.666667,0.000000,310.000000,191.333333,883.666667,3.666667,2.0,589.666667,648.333333
17,09-06-17,103.000000,229.000000,674.666667,227.666667,424.000000,395.333333,0.000000,685.000000,993.000000,...,106.000000,16.666667,0.000000,310.000000,191.333333,883.666667,3.666667,2.0,589.666667,648.333333
18,10-06-17,103.000000,229.000000,674.666667,227.666667,424.000000,395.333333,0.000000,685.000000,993.000000,...,106.000000,16.666667,0.000000,310.000000,191.333333,883.666667,3.666667,2.0,589.666667,648.333333
19,11-06-17,65.500000,0.000000,340.000000,57.500000,78.500000,141.500000,0.000000,173.500000,311.000000,...,98.500000,12.000000,0.000000,139.500000,79.000000,287.500000,1.000000,0.0,89.500000,269.500000
20,12-06-17,65.500000,0.000000,340.000000,57.500000,78.500000,141.500000,0.000000,173.500000,311.000000,...,98.500000,12.000000,0.000000,139.500000,79.000000,287.500000,1.000000,0.0,89.500000,269.500000
21,13-06-17,64.000000,0.000000,522.000000,199.000000,173.000000,241.000000,0.000000,827.000000,913.000000,...,2.000000,16.000000,24.000000,229.000000,24.000000,548.000000,0.000000,0.0,694.000000,999.000000
22,14-06-17,96.000000,1.000000,587.000000,230.000000,77.000000,292.000000,0.000000,13.000000,825.000000,...,235.000000,22.000000,8.000000,181.000000,265.000000,775.000000,1.000000,0.0,389.000000,554.000000
23,15-06-17,107.666667,278.333333,631.666667,162.000000,297.333333,411.666667,0.000000,729.666667,904.666667,...,36.666667,16.666667,7.333333,240.000000,47.333333,896.666667,6.333333,0.0,488.333333,463.666667
24,16-06-17,107.666667,278.333333,631.666667,162.000000,297.333333,411.666667,0.000000,729.666667,904.666667,...,36.666667,16.666667,7.333333,240.000000,47.333333,896.666667,6.333333,0.0,488.333333,463.666667
25,17-06-17,107.666667,278.333333,631.666667,162.000000,297.333333,411.666667,0.000000,729.666667,904.666667,...,36.666667,16.666667,7.333333,240.000000,47.333333,896.666667,6.333333,0.0,488.333333,463.666667
26,18-06-17,100.000000,215.000000,729.000000,0.000000,803.000000,407.000000,0.000000,776.000000,1001.000000,...,314.000000,49.000000,10.000000,287.000000,331.000000,1008.000000,5.000000,17.0,459.000000,539.000000
27,19-06-17,110.000000,354.000000,750.000000,122.000000,239.000000,413.000000,0.000000,8.000000,843.000000,...,25.000000,29.000000,13.000000,294.000000,5.000000,691.000000,1.000000,12.0,497.000000,338.000000
28,20-06-17,1.000000,219.000000,836.000000,2.000000,160.000000,438.000000,0.000000,1276.000000,913.000000,...,213.000000,0.000000,16.000000,98.000000,175.000000,1404.000000,1.000000,4.0,394.000000,581.000000
29,21-06-17,4.000000,198.000000,818.000000,416.000000,381.000000,475.000000,0.000000,236.000000,956.000000,...,9.000000,32.000000,12.000000,252.000000,107.000000,949.000000,45.000000,0.0,211.000000,400.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,20-01-18,0.000000,2.714286,98.000000,77.000000,0.000000,153.714286,0.000000,398.000000,232.428571,...,0.000000,0.000000,0.000000,66.714286,64.285714,163.428571,0.285714,0.0,96.857143,97.000000
243,21-01-18,0.000000,2.714286,98.000000,77.000000,0.000000,153.714286,0.000000,398.000000,232.428571,...,0.000000,0.000000,0.000000,66.714286,64.285714,163.428571,0.285714,0.0,96.857143,97.000000
244,22-01-18,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
245,23-01-18,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
246,24-01-18,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
247,25-01-18,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
248,26-01-18,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
249,27-01-18,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
250,28-01-18,0.000000,3.000000,52.571429,64.142857,0.000000,99.000000,0.000000,3.571429,122.000000,...,0.000000,0.142857,0.000000,51.857143,52.000000,109.714286,0.142857,0.0,56.571429,33.142857
251,29-01-18,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
252,30-01-18,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
253,31-01-18,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
254,01-02-18,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
255,02-02-18,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
256,03-02-18,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
257,04-02-18,0.000000,3.428571,38.714286,37.428571,0.428571,92.857143,0.000000,0.714286,116.571429,...,0.142857,0.000000,0.000000,49.714286,32.571429,78.000000,0.000000,0.0,50.571429,25.000000
258,05-02-18,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
259,06-02-18,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
260,07-02-18,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
261,08-02-18,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
262,09-02-18,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
263,10-02-18,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
264,11-02-18,0.285714,3.142857,36.857143,40.714286,0.000000,84.142857,0.000000,0.428571,140.428571,...,0.000000,0.000000,0.000000,47.285714,28.000000,83.285714,0.000000,0.0,46.428571,19.285714
265,12-02-18,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
266,13-02-18,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
267,14-02-18,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
268,15-02-18,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
269,16-02-18,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
270,17-02-18,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143
271,18-02-18,0.000000,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.000000,94.714286,...,0.000000,0.285714,0.000000,40.142857,28.571429,98.714286,0.000000,0.0,56.285714,14.857143

In [5]:
yemen_cholera_case_data_diff.date = pd.to_datetime(yemen_cholera_case_data_diff.date, format = '%d-%m-%y')

In [6]:
yemen_cholera_case_data_unstacked = yemen_cholera_case_data_diff.set_index('date').unstack().reset_index()

In [7]:
yemen_cholera_case_data_unstacked.columns = ['gov_iso', 'date', 'new_cases']

In [8]:
yemen_cholera_case_data_unstacked.head()

  gov_iso       date  new_cases
0   YE-AB 2017-05-23       59.4
1   YE-AB 2017-05-24       59.4
2   YE-AB 2017-05-25       59.4
3   YE-AB 2017-05-26       59.4
4   YE-AB 2017-05-27       59.4

In [9]:
#yemen_cholera_case_data_unstacked.groupby(['gov_iso', pd.Grouper(key='date_minus_14', freq='3W-WED')])['new_cases'].sum().reset_index().sort_values('date_minus_14')

In [10]:
def get_cholera_cases_x_days_ahead(row, days, data):
    
    new_cases = data[(data.gov_iso == row.gov_iso) & (data.date > row.date) & (data.date <= (row.date + pd.to_timedelta(days, unit='d')))].new_cases.sum()
    
    return (new_cases)

In [12]:
def get_cholera_cases_x_days_ahead_week_only(row, days_forward, days_back, data):
    
    new_cases = data[(data.gov_iso == row.gov_iso) & (data.date > (row.date + pd.to_timedelta(days_forward - days_back, unit='d'))) & (data.date <= (row.date + pd.to_timedelta(days_forward, unit='d')))].new_cases.sum()
    
    return (new_cases)

In [13]:
# yemen_cholera_case_data_unstacked['next_week_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead, args = (7,yemen_cholera_case_data_unstacked), axis = 1)
# yemen_cholera_case_data_unstacked['next_two_week_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead, args = (14,yemen_cholera_case_data_unstacked), axis = 1)
# yemen_cholera_case_data_unstacked['next_four_week_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead, args = (28,yemen_cholera_case_data_unstacked), axis = 1)
# yemen_cholera_case_data_unstacked['next_six_week_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead, args = (42,yemen_cholera_case_data_unstacked), axis = 1)

In [14]:
# yemen_cholera_case_data_unstacked['next_week_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead_week_only, args = (7,yemen_cholera_case_data_unstacked), axis = 1)
# yemen_cholera_case_data_unstacked['next_two_week_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead_week_only, args = (14, 7, yemen_cholera_case_data_unstacked), axis = 1)
# yemen_cholera_case_data_unstacked['next_three_week_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead_week_only, args = (21,yemen_cholera_case_data_unstacked), axis = 1)
# yemen_cholera_case_data_unstacked['next_four_week_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead_week_only, args = (28,yemen_cholera_case_data_unstacked), axis = 1)
# yemen_cholera_case_data_unstacked['next_five_week_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead_week_only, args = (35,yemen_cholera_case_data_unstacked), axis = 1)
# yemen_cholera_case_data_unstacked['next_six_week_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead_week_only, args = (42,yemen_cholera_case_data_unstacked), axis = 1)

In [15]:
yemen_cholera_case_data_unstacked['week_1_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead_week_only, args = (7, 7, yemen_cholera_case_data_unstacked), axis = 1)
yemen_cholera_case_data_unstacked['week_2_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead_week_only, args = (14, 7, yemen_cholera_case_data_unstacked), axis = 1)
yemen_cholera_case_data_unstacked['week_2_to_4_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead_week_only, args = (28, 14,yemen_cholera_case_data_unstacked), axis = 1)
yemen_cholera_case_data_unstacked['week_4_to_6_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead_week_only, args = (42, 14,yemen_cholera_case_data_unstacked), axis = 1)
yemen_cholera_case_data_unstacked['week_6_to_8_cases'] = yemen_cholera_case_data_unstacked.apply(get_cholera_cases_x_days_ahead_week_only, args = (56, 14, yemen_cholera_case_data_unstacked), axis = 1)

In [18]:
week_max_date = yemen_cholera_case_data_unstacked.sort_values('date').iloc[-1].date - pd.to_timedelta(7, unit='d')
two_week_max_date = yemen_cholera_case_data_unstacked.sort_values('date').iloc[-1].date - pd.to_timedelta(14, unit='d')
three_week_max_date = yemen_cholera_case_data_unstacked.sort_values('date').iloc[-1].date - pd.to_timedelta(21, unit='d')
four_week_max_date = yemen_cholera_case_data_unstacked.sort_values('date').iloc[-1].date - pd.to_timedelta(28, unit='d')
five_week_max_date = yemen_cholera_case_data_unstacked.sort_values('date').iloc[-1].date - pd.to_timedelta(35, unit='d')
six_week_max_date = yemen_cholera_case_data_unstacked.sort_values('date').iloc[-1].date - pd.to_timedelta(42, unit='d')
eight_week_max_date = yemen_cholera_case_data_unstacked.sort_values('date').iloc[-1].date - pd.to_timedelta(56, unit='d')

In [15]:
# next_week_crosstab = yemen_cholera_case_data_unstacked.pivot_table(index = 'date', columns = 'gov_iso', values = 'next_week_cases', aggfunc = 'sum')
# next_two_weeks_crosstab = yemen_cholera_case_data_unstacked.pivot_table(index = 'date', columns = 'gov_iso', values = 'next_two_week_cases', aggfunc = 'sum')
# next_three_weeks_crosstab = yemen_cholera_case_data_unstacked.pivot_table(index = 'date', columns = 'gov_iso', values = 'next_three_week_cases', aggfunc = 'sum')
# next_four_weeks_crosstab = yemen_cholera_case_data_unstacked.pivot_table(index = 'date', columns = 'gov_iso', values = 'next_four_week_cases', aggfunc = 'sum')
# next_five_weeks_crosstab = yemen_cholera_case_data_unstacked.pivot_table(index = 'date', columns = 'gov_iso', values = 'next_five_week_cases', aggfunc = 'sum')
# next_six_weeks_crosstab = yemen_cholera_case_data_unstacked.pivot_table(index = 'date', columns = 'gov_iso', values = 'next_six_week_cases', aggfunc = 'sum')

In [19]:
week_1_crosstab = yemen_cholera_case_data_unstacked.pivot_table(index = 'date', columns = 'gov_iso', values = 'week_1_cases', aggfunc = 'sum')
week_2_crosstab = yemen_cholera_case_data_unstacked.pivot_table(index = 'date', columns = 'gov_iso', values = 'week_2_cases', aggfunc = 'sum')
week_2_to_4_crosstab = yemen_cholera_case_data_unstacked.pivot_table(index = 'date', columns = 'gov_iso', values = 'week_2_to_4_cases', aggfunc = 'sum')
week_4_to_6_crosstab = yemen_cholera_case_data_unstacked.pivot_table(index = 'date', columns = 'gov_iso', values = 'week_4_to_6_cases', aggfunc = 'sum')
week_6_to_8_crosstab = yemen_cholera_case_data_unstacked.pivot_table(index = 'date', columns = 'gov_iso', values = 'week_6_to_8_cases', aggfunc = 'sum')

In [16]:
# next_week_crosstab = next_week_crosstab.loc[(next_week_crosstab.index.get_level_values('date') <= week_max_date)]
# next_two_weeks_crosstab = next_two_weeks_crosstab.loc[(next_two_weeks_crosstab.index.get_level_values('date') <= two_week_max_date)]
# next_three_weeks_crosstab = next_three_weeks_crosstab.loc[(next_three_weeks_crosstab.index.get_level_values('date') <= three_week_max_date)]
# next_four_weeks_crosstab = next_four_weeks_crosstab.loc[(next_four_weeks_crosstab.index.get_level_values('date') <= four_week_max_date)]
# next_five_weeks_crosstab = next_five_weeks_crosstab.loc[(next_five_weeks_crosstab.index.get_level_values('date') <= five_week_max_date)]
# next_six_weeks_crosstab = next_six_weeks_crosstab.loc[(next_six_weeks_crosstab.index.get_level_values('date') <= six_week_max_date)]

In [20]:
week_1_crosstab = week_1_crosstab.loc[(week_1_crosstab.index.get_level_values('date') <= week_max_date)]
week_2_crosstab = week_2_crosstab.loc[(week_2_crosstab.index.get_level_values('date') <= two_week_max_date)]
week_2_to_4_crosstab = week_2_to_4_crosstab.loc[(week_2_to_4_crosstab.index.get_level_values('date') <= four_week_max_date)]
week_4_to_6_crosstab = week_4_to_6_crosstab.loc[(week_4_to_6_crosstab.index.get_level_values('date') <= six_week_max_date)]
week_6_to_8_crosstab = week_6_to_8_crosstab.loc[(week_6_to_8_crosstab.index.get_level_values('date') <= eight_week_max_date)]

In [24]:
crosstab_list = [next_week_crosstab, next_two_weeks_crosstab, next_three_weeks_crosstab, next_four_weeks_crosstab, next_five_weeks_crosstab, next_six_weeks_crosstab]

In [ ]:
for i in range(0, len(crosstab_list)):
    
    crosstab_list[i]

In [147]:
next_week_crosstab.to_csv('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_data/yemen_next_week_case_data.csv')

In [148]:
next_two_weeks_crosstab.to_csv('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_data/yemen_next_two_week_case_data.csv')

In [149]:
next_three_weeks_crosstab.to_csv('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_data/yemen_next_three_week_case_data.csv')

In [16]:
next_four_weeks_crosstab.to_csv('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_data/yemen_next_four_week_case_data.csv')

In [17]:
next_six_weeks_crosstab.to_csv('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_data/yemen_next_six_week_case_data.csv')

In [22]:
gov_pop_area_data = pd.read_excel('/Users/Rohil/Documents/iGEM/yemen/gov_area_pop_data.xlsx')
gov_pop_area_data = gov_pop_area_data[gov_pop_area_data.iso != 'YE-HD']

In [23]:
# norm_next_week_crosstab = next_week_crosstab
# for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
#     norm_next_week_crosstab[row.iso] = (norm_next_week_crosstab[row.iso] * 10000) / row.population
    
# norm_next_two_weeks_crosstab = next_two_weeks_crosstab
# for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
#     norm_next_two_weeks_crosstab[row.iso] = (norm_next_two_weeks_crosstab[row.iso] * 10000) / row.population
    
# norm_next_three_weeks_crosstab = next_three_weeks_crosstab
# for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
#     norm_next_three_weeks_crosstab[row.iso] = (norm_next_three_weeks_crosstab[row.iso] * 10000) / row.population    
    
# norm_next_four_weeks_crosstab = next_four_weeks_crosstab
# for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
#     norm_next_four_weeks_crosstab[row.iso] = (norm_next_four_weeks_crosstab[row.iso] * 10000) / row.population

# norm_next_five_weeks_crosstab = next_five_weeks_crosstab
# for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
#     norm_next_five_weeks_crosstab[row.iso] = (norm_next_five_weeks_crosstab[row.iso] * 10000) / row.population   
    
# norm_next_six_weeks_crosstab = next_six_weeks_crosstab
# for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
#     norm_next_six_weeks_crosstab[row.iso] = (norm_next_six_weeks_crosstab[row.iso] * 10000) / row.population

In [24]:
norm_week_1_crosstab = week_1_crosstab
for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
    norm_week_1_crosstab[row.iso] = (norm_week_1_crosstab[row.iso] * 10000) / row.population
    
norm_week_2_crosstab = week_2_crosstab
for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
    norm_week_2_crosstab[row.iso] = (norm_week_2_crosstab[row.iso] * 10000) / row.population
    
norm_week_2_to_4_crosstab = week_2_to_4_crosstab
for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
    norm_week_2_to_4_crosstab[row.iso] = (norm_week_2_to_4_crosstab[row.iso] * 10000) / row.population    
    
norm_week_4_to_6_crosstab = week_4_to_6_crosstab
for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
    norm_week_4_to_6_crosstab[row.iso] = (norm_week_4_to_6_crosstab[row.iso] * 10000) / row.population

norm_week_6_to_8_crosstab = week_6_to_8_crosstab
for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
    norm_week_6_to_8_crosstab[row.iso] = (norm_week_6_to_8_crosstab[row.iso] * 10000) / row.population

In [25]:
norm_week_1_df = norm_week_1_crosstab.unstack().reset_index()
norm_week_1_df.columns = ['gov_iso', 'date', 'week_1_cases']

norm_week_2_df = norm_week_2_crosstab.unstack().reset_index()
norm_week_2_df.columns = ['gov_iso', 'date', 'week_2_cases']

norm_week_2_to_4_df = norm_week_2_to_4_crosstab.unstack().reset_index()
norm_week_2_to_4_df.columns = ['gov_iso', 'date', 'week_2_to_4_cases']

norm_week_4_to_6_df = norm_week_4_to_6_crosstab.unstack().reset_index()
norm_week_4_to_6_df.columns = ['gov_iso', 'date', 'week_4_to_6_cases']

norm_week_6_to_8_df = norm_week_6_to_8_crosstab.unstack().reset_index()
norm_week_6_to_8_df.columns = ['gov_iso', 'date', 'week_6_to_8_cases']

In [19]:
# norm_next_week_df = norm_next_week_crosstab.unstack().reset_index()
# norm_next_week_df.columns = ['gov_iso', 'date', 'next_week_cases']

# norm_next_two_weeks_df = norm_next_two_weeks_crosstab.unstack().reset_index()
# norm_next_two_weeks_df.columns = ['gov_iso', 'date', 'next_two_week_cases']

# norm_next_three_weeks_df = norm_next_three_weeks_crosstab.unstack().reset_index()
# norm_next_three_weeks_df.columns = ['gov_iso', 'date', 'next_three_week_cases']

# norm_next_four_weeks_df = norm_next_four_weeks_crosstab.unstack().reset_index()
# norm_next_four_weeks_df.columns = ['gov_iso', 'date', 'next_four_week_cases']

# norm_next_five_weeks_df = norm_next_five_weeks_crosstab.unstack().reset_index()
# norm_next_five_weeks_df.columns = ['gov_iso', 'date', 'next_five_week_cases']

# norm_next_six_weeks_df = norm_next_six_weeks_crosstab.unstack().reset_index()
# norm_next_six_weeks_df.columns = ['gov_iso', 'date', 'next_six_week_cases']

In [28]:
#y_df = norm_next_week_df.merge(norm_next_two_weeks_df, on = ['gov_iso', 'date'], how = 'left').merge(norm_next_three_weeks_df, on = ['gov_iso', 'date'], how = 'left').merge(norm_next_four_weeks_df, on = ['gov_iso', 'date'], how = 'left').merge(norm_next_five_weeks_df, on = ['gov_iso', 'date'], how = 'left').merge(norm_next_six_weeks_df, on = ['gov_iso', 'date'], how = 'left')

In [26]:
y_df = norm_week_1_df.merge(norm_week_2_df, on = ['gov_iso', 'date'], how = 'left').merge(norm_week_2_to_4_df, on = ['gov_iso', 'date'], how = 'left').merge(norm_week_4_to_6_df, on = ['gov_iso', 'date'], how = 'left').merge(norm_week_6_to_8_df, on = ['gov_iso', 'date'], how = 'left')

In [27]:
y_df

,gov_iso,date,week_1_cases,week_2_cases,week_2_to_4_cases,week_4_to_6_cases,week_6_to_8_cases
0,YE-AB,2017-05-23,6.976066,7.594340,18.482427,51.257999,65.009775
1,YE-AB,2017-05-24,7.085352,7.853387,17.273202,55.583889,60.623171
2,YE-AB,2017-05-25,7.194638,8.405887,20.658021,55.523175,60.532100
3,YE-AB,2017-05-26,7.303923,8.958386,21.022306,57.982101,60.577635
4,YE-AB,2017-05-27,7.413209,9.510886,22.358020,58.563946,60.876147
5,YE-AB,2017-05-28,7.300888,9.494190,21.394181,62.014539,57.410376
6,YE-AB,2017-05-29,7.447614,9.218446,22.388377,63.507097,63.446383
7,YE-AB,2017-05-30,7.594340,8.919934,21.508020,68.455308,62.899955
8,YE-AB,2017-05-31,7.853387,9.107136,26.441053,65.905310,63.021384
9,YE-AB,2017-06-01,8.405887,9.177970,28.905039,66.117810,68.500844
10,YE-AB,2017-06-02,8.958386,9.248803,30.807418,70.762449,64.068704
11,YE-AB,2017-06-03,9.510886,9.319636,34.060690,70.671378,59.348172
12,YE-AB,2017-06-04,9.494190,9.843297,42.226756,61.093706,63.658883
13,YE-AB,2017-06-05,9.218446,10.518742,45.687467,61.412456,62.444598
14,YE-AB,2017-06-06,8.919934,9.562493,51.257999,65.009775,57.253531
15,YE-AB,2017-06-07,9.107136,8.166066,55.583889,60.623171,60.919153
16,YE-AB,2017-06-08,9.177970,11.480051,55.523175,60.532100,59.788350
17,YE-AB,2017-06-09,9.248803,11.773503,57.982101,60.577635,60.289243
18,YE-AB,2017-06-10,9.319636,13.038384,58.563946,60.876147,61.442813
19,YE-AB,2017-06-11,9.843297,11.550885,62.014539,57.410376,66.360667
20,YE-AB,2017-06-12,10.518742,11.869634,63.507097,63.446383,59.836054
21,YE-AB,2017-06-13,9.562493,11.945527,68.455308,62.899955,58.335545
22,YE-AB,2017-06-14,8.166066,18.274987,65.905310,63.021384,57.366286
23,YE-AB,2017-06-15,11.480051,17.424988,66.117810,68.500844,50.568459
24,YE-AB,2017-06-16,11.773503,19.033915,70.762449,64.068704,49.811699
25,YE-AB,2017-06-17,13.038384,21.022306,70.671378,59.348172,52.728151
26,YE-AB,2017-06-18,11.550885,30.675871,61.093706,63.658883,51.303535
27,YE-AB,2017-06-19,11.869634,33.817833,61.412456,62.444598,50.711571
28,YE-AB,2017-06-20,11.945527,39.312472,65.009775,57.253531,50.362464
29,YE-AB,2017-06-21,18.274987,37.308902,60.623171,60.919153,49.762911
...,...,...,...,...,...,...,...
5535,YE-TA,2018-01-13,1.382951,0.649601,0.711080,NaN,NaN
5536,YE-TA,2018-01-14,1.490852,0.509393,0.680654,NaN,NaN
5537,YE-TA,2018-01-15,1.350643,0.491514,0.658384,NaN,NaN
5538,YE-TA,2018-01-16,1.210435,0.473635,0.636114,NaN,NaN
5539,YE-TA,2018-01-17,1.070227,0.455756,0.613843,NaN,NaN
5540,YE-TA,2018-01-18,0.930018,0.437877,0.591573,NaN,NaN
5541,YE-TA,2018-01-19,0.789810,0.419998,0.569303,NaN,NaN
5542,YE-TA,2018-01-20,0.649601,0.402119,0.547033,NaN,NaN
5543,YE-TA,2018-01-21,0.509393,0.384240,0.524762,NaN,NaN
5544,YE-TA,2018-01-22,0.491514,0.371694,NaN,NaN,NaN
5545,YE-TA,2018-01-23,0.473635,0.359147,NaN,NaN,NaN
5546,YE-TA,2018-01-24,0.455756,0.346600,NaN,NaN,NaN
5547,YE-TA,2018-01-25,0.437877,0.334054,NaN,NaN,NaN
5548,YE-TA,2018-01-26,0.419998,0.321507,NaN,NaN,NaN
5549,YE-TA,2018-01-27,0.402119,0.308960,NaN,NaN,NaN
5550,YE-TA,2018-01-28,0.384240,0.296414,NaN,NaN,NaN
5551,YE-TA,2018-01-29,0.371694,0.286690,NaN,NaN,NaN
5552,YE-TA,2018-01-30,0.359147,0.276967,NaN,NaN,NaN
5553,YE-TA,2018-01-31,0.346600,0.267243,NaN,NaN,NaN
5554,YE-TA,2018-02-01,0.334054,0.257519,NaN,NaN,NaN
5555,YE-TA,2018-02-02,0.321507,0.247796,NaN,NaN,NaN
5556,YE-TA,2018-02-03,0.308960,0.238072,NaN,NaN,NaN
5557,YE-TA,2018-02-04,0.296414,0.228348,NaN,NaN,NaN
5558,YE-TA,2018-02-05,0.286690,NaN,NaN,NaN,NaN
5559,YE-TA,2018-02-06,0.276967,NaN,NaN,NaN,NaN
5560,YE-TA,2018-02-07,0.267243,NaN,NaN,NaN,NaN
5561,YE-TA,2018-02-08,0.257519,NaN,NaN,NaN,NaN
5562,YE-TA,2018-02-09,0.247796,NaN,NaN,NaN,NaN
5563,YE-TA,2018-02-10,0.238072,NaN,NaN,NaN,NaN
5564,YE-TA,2018-02-11,0.228348,NaN,NaN,NaN,NaN

In [28]:
y_df.to_csv('/Users/Rohil/Documents/iGEM/yemen/cholera_epi_data/y_normalized_groupby_week_df.csv', index = False)