In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from scipy.stats import kurtosis
from sklearn.decomposition import PCA
import seaborn as sns
from scipy.stats import pearsonr
%matplotlib

Using matplotlib backend: Qt5Agg

In [2]:
gov_pop_area_data = pd.read_excel('/Users/Rohil/Documents/iGEM/yemen/gov_area_pop_data.xlsx')

In [3]:
gov_pop_area_data = gov_pop_area_data[gov_pop_area_data.iso != 'YE-HD']

In [4]:
gov_pop_area_data.head()

   governorate governorate_arabic capital_city     area  population    iso
0        Abyan               أبين     Zinjibar  21939.0      658824  YE-AB
1         Aden                عدن         Aden   1114.0     1087653  YE-AD
2     Al Bayda            البيضاء     Al Bayda  11193.0      835683  YE-BA
3  Al Hudaydah            الحديدة  Al Hudaydah  17509.0     3774914  YE-HU
4      Al Jawf              الجوف      Al Hazm  30620.0      663147  YE-JA

In [5]:
cholera_case_crosstab = pd.read_csv(r'C:\Users\Rohil\Documents\iGEM\yemen\cholera_epi_data\yemen_cholera_case_data_differenced.csv', dayfirst = True)

In [6]:
cholera_case_crosstab.tail()

,date,YE-AB,YE-AD,YE-AM,YE-BA,YE-DA,YE-DH,YE-HD-AL,YE-HJ,YE-HU,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
267,14-02-18,0.0,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.0,94.714286,...,0.0,0.285714,0.0,40.142857,28.571429,98.714286,0.0,0.0,56.285714,14.857143
268,15-02-18,0.0,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.0,94.714286,...,0.0,0.285714,0.0,40.142857,28.571429,98.714286,0.0,0.0,56.285714,14.857143
269,16-02-18,0.0,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.0,94.714286,...,0.0,0.285714,0.0,40.142857,28.571429,98.714286,0.0,0.0,56.285714,14.857143
270,17-02-18,0.0,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.0,94.714286,...,0.0,0.285714,0.0,40.142857,28.571429,98.714286,0.0,0.0,56.285714,14.857143
271,18-02-18,0.0,1.714286,21.571429,43.285714,0.142857,62.857143,0.142857,0.0,94.714286,...,0.0,0.285714,0.0,40.142857,28.571429,98.714286,0.0,0.0,56.285714,14.857143

In [7]:
norm_cholera_case_crosstab = cholera_case_crosstab

In [8]:
for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
    norm_cholera_case_crosstab[row.iso] = (norm_cholera_case_crosstab[row.iso] * 10000) / row.population

In [9]:
norm_cholera_case_crosstab.tail()

,date,YE-AB,YE-AD,YE-AM,YE-BA,YE-DA,YE-DH,YE-HD-AL,YE-HJ,YE-HU,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
267,14-02-18,0.0,0.015761,0.191976,0.517968,0.002371,0.370387,0.005534,0.0,0.250904,...,0.0,0.005661,0.0,0.54813,0.56858,0.840288,0.0,0.0,0.246903,0.032621
268,15-02-18,0.0,0.015761,0.191976,0.517968,0.002371,0.370387,0.005534,0.0,0.250904,...,0.0,0.005661,0.0,0.54813,0.56858,0.840288,0.0,0.0,0.246903,0.032621
269,16-02-18,0.0,0.015761,0.191976,0.517968,0.002371,0.370387,0.005534,0.0,0.250904,...,0.0,0.005661,0.0,0.54813,0.56858,0.840288,0.0,0.0,0.246903,0.032621
270,17-02-18,0.0,0.015761,0.191976,0.517968,0.002371,0.370387,0.005534,0.0,0.250904,...,0.0,0.005661,0.0,0.54813,0.56858,0.840288,0.0,0.0,0.246903,0.032621
271,18-02-18,0.0,0.015761,0.191976,0.517968,0.002371,0.370387,0.005534,0.0,0.250904,...,0.0,0.005661,0.0,0.54813,0.56858,0.840288,0.0,0.0,0.246903,0.032621

In [10]:
cholera_death_crosstab = pd.read_csv(r'C:\Users\Rohil\Documents\iGEM\yemen\cholera_epi_data\yemen_cholera_death_data_differenced.csv', dayfirst = True)

In [11]:
cholera_death_crosstab.head()

,date,YE-AB,YE-AD,YE-AM,YE-BA,YE-DA,YE-DH,YE-HD-AL,YE-HJ,YE-HU,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
0,23-05-17,1.0,0.0,2.4,0.4,0.2,1.6,0,4.0,1.6,...,0.2,0.2,0,2.2,0.8,0.6,0,0.0,1.4,1.4
1,24-05-17,1.0,0.0,2.4,0.4,0.2,1.6,0,4.0,1.6,...,0.2,0.2,0,2.2,0.8,0.6,0,0.0,1.4,1.4
2,25-05-17,1.0,0.0,2.4,0.4,0.2,1.6,0,4.0,1.6,...,0.2,0.2,0,2.2,0.8,0.6,0,0.0,1.4,1.4
3,26-05-17,1.0,0.0,2.4,0.4,0.2,1.6,0,4.0,1.6,...,0.2,0.2,0,2.2,0.8,0.6,0,0.0,1.4,1.4
4,27-05-17,1.0,0.0,2.4,0.4,0.2,1.6,0,4.0,1.6,...,0.2,0.2,0,2.2,0.8,0.6,0,0.0,1.4,1.4

In [12]:
norm_cholera_death_crosstab = cholera_death_crosstab

In [13]:
for index, row in gov_pop_area_data[['iso', 'population']].iterrows():
    norm_cholera_death_crosstab[row.iso] = (norm_cholera_death_crosstab[row.iso] * 10000) / row.population

In [14]:
norm_cholera_death_crosstab.head()

,date,YE-AB,YE-AD,YE-AM,YE-BA,YE-DA,YE-DH,YE-HD-AL,YE-HJ,YE-HU,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
0,23-05-17,0.015179,0.0,0.021359,0.004787,0.003319,0.009428,0.0,0.021195,0.004239,...,0.002159,0.003963,0.0,0.03004,0.01592,0.005107,0.0,0.0,0.006141,0.003074
1,24-05-17,0.015179,0.0,0.021359,0.004787,0.003319,0.009428,0.0,0.021195,0.004239,...,0.002159,0.003963,0.0,0.03004,0.01592,0.005107,0.0,0.0,0.006141,0.003074
2,25-05-17,0.015179,0.0,0.021359,0.004787,0.003319,0.009428,0.0,0.021195,0.004239,...,0.002159,0.003963,0.0,0.03004,0.01592,0.005107,0.0,0.0,0.006141,0.003074
3,26-05-17,0.015179,0.0,0.021359,0.004787,0.003319,0.009428,0.0,0.021195,0.004239,...,0.002159,0.003963,0.0,0.03004,0.01592,0.005107,0.0,0.0,0.006141,0.003074
4,27-05-17,0.015179,0.0,0.021359,0.004787,0.003319,0.009428,0.0,0.021195,0.004239,...,0.002159,0.003963,0.0,0.03004,0.01592,0.005107,0.0,0.0,0.006141,0.003074

In [15]:
mean_rainfall_crosstab = pd.read_csv(r'C:\Users\Rohil\Documents\iGEM\yemen\rainfall\yemen_daily_mean_rainfall_crosstab.csv', dayfirst = True)

In [16]:
max_rainfall_crosstab = pd.read_csv(r'C:\Users\Rohil\Documents\iGEM\yemen\rainfall\yemen_daily_max_rainfall_crosstab.csv', dayfirst = True)

In [17]:
mean_rainfall_crosstab.head()

,date,YE-AB,YE-AD,YE-AM,YE-BA,YE-DA,YE-DH,YE-HD,YE-HD-AL,YE-HJ,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
0,01-01-17,0.0,0.0,0.0,0.0,0.0,0.0,0.016940,0.0,0.000000,...,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.116578
1,02-01-17,0.0,0.0,0.0,0.0,0.0,0.0,0.025991,0.0,0.195193,...,0.0,0.0,0.039,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
2,03-01-17,0.0,0.0,0.0,0.0,0.0,0.0,0.020690,0.0,0.000000,...,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.191324
3,04-01-17,0.0,0.0,0.0,0.0,0.0,0.0,0.006466,0.0,0.000000,...,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
4,05-01-17,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [18]:
max_rainfall_crosstab.head()

,date,YE-AB,YE-AD,YE-AM,YE-BA,YE-DA,YE-DH,YE-HD,YE-HD-AL,YE-HJ,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
0,01-01-17,0.0,0.0,0.0,0.0,0.0,0.0,2.10,0.0,0.000000,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1.632085
1,02-01-17,0.0,0.0,0.0,0.0,0.0,0.0,3.90,0.0,1.155481,...,0.0,0.0,3.51,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
2,03-01-17,0.0,0.0,0.0,0.0,0.0,0.0,4.32,0.0,0.000000,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1.552748
3,04-01-17,0.0,0.0,0.0,0.0,0.0,0.0,1.50,0.0,0.000000,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
4,05-01-17,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [19]:
cases_unstacked = norm_cholera_case_crosstab.set_index('date').unstack().reset_index()
cases_unstacked.columns = ['gov_iso', 'date', 'new_cases']

In [20]:
deaths_unstacked = norm_cholera_death_crosstab.set_index('date').unstack().reset_index()
deaths_unstacked.columns = ['gov_iso', 'date', 'new_deaths']

In [21]:
max_rainfall_unstacked = max_rainfall_crosstab.set_index('date').unstack().reset_index()
max_rainfall_unstacked.columns = ['gov_iso', 'date', 'max_rainfall']

In [22]:
mean_rainfall_unstacked = mean_rainfall_crosstab.set_index('date').unstack().reset_index()
mean_rainfall_unstacked.columns = ['gov_iso', 'date', 'mean_rainfall']

In [23]:
cases_unstacked.shape

(5712, 3)

In [24]:
cases_unstacked.head()

  gov_iso      date  new_cases
0   YE-AB  23-05-17   0.901606
1   YE-AB  24-05-17   0.901606
2   YE-AB  25-05-17   0.901606
3   YE-AB  26-05-17   0.901606
4   YE-AB  27-05-17   0.901606

In [27]:
deaths_unstacked.shape

(5712, 3)

In [28]:
deaths_unstacked.head()

  gov_iso      date  new_deaths
0   YE-AB  23-05-17    0.015179
1   YE-AB  24-05-17    0.015179
2   YE-AB  25-05-17    0.015179
3   YE-AB  26-05-17    0.015179
4   YE-AB  27-05-17    0.015179

In [29]:
mean_rainfall_unstacked.shape

(9944, 3)

In [30]:
## date formatting has been fixed
mean_rainfall_unstacked.head()

  gov_iso      date  mean_rainfall
0   YE-AB  01-01-17            0.0
1   YE-AB  02-01-17            0.0
2   YE-AB  03-01-17            0.0
3   YE-AB  04-01-17            0.0
4   YE-AB  05-01-17            0.0

In [31]:
mean_rainfall_unstacked.date.tail()

9939    26-03-18
9940    27-03-18
9941    28-03-18
9942    29-03-18
9943    30-03-18
Name: date, dtype: object

In [33]:
cases_unstacked.date.tail()

5707    14-02-18
5708    15-02-18
5709    16-02-18
5710    17-02-18
5711    18-02-18
Name: date, dtype: object

In [34]:
deaths_unstacked.date.tail()

5707    14-02-18
5708    15-02-18
5709    16-02-18
5710    17-02-18
5711    18-02-18
Name: date, dtype: object

In [35]:
case_death_rainfall_data = cases_unstacked.merge(deaths_unstacked, on =['date', 'gov_iso']).merge(mean_rainfall_unstacked, on =['date', 'gov_iso'], how = 'left')

In [36]:
case_death_rainfall_data.date = pd.to_datetime(case_death_rainfall_data.date, dayfirst = True)

In [37]:
case_death_rainfall_data.sort_values(by = 'date')

       gov_iso       date  new_cases  new_deaths  mean_rainfall
0        YE-AB 2017-05-23   0.901606    0.015179       0.000000
2176     YE-HU 2017-05-23   0.564781    0.004239      14.555986
3536     YE-MR 2017-05-23   0.000000    0.000000       0.000000
3808     YE-MW 2017-05-23   3.025834    0.030040      17.384593
4896     YE-SH 2017-05-23   0.000000    0.000000       0.000000
1088     YE-DA 2017-05-23   1.719180    0.003319       3.266315
4624     YE-SD 2017-05-23   0.000000    0.000000       0.267274
1904     YE-HJ 2017-05-23   1.394649    0.021195      12.675418
3264     YE-MA 2017-05-23   0.225879    0.003963       0.000000
4352     YE-SA 2017-05-23   5.665804    0.005107       0.000000
2992     YE-LA 2017-05-23   0.345464    0.002159       0.068845
2720     YE-JA 2017-05-23   0.247306    0.000000       0.000000
2448     YE-IB 2017-05-23   0.408584    0.010227       2.847355
816      YE-BA 2017-05-23   2.484196    0.004787       0.124548
5440     YE-TA 2017-05-23   0.703928    0.003074       4.762600
272      YE-AD 2017-05-23   0.559002    0.000000       0.000000
1360     YE-DH 2017-05-23   1.048868    0.009428       0.454375
4080     YE-RA 2017-05-23   0.843773    0.015920      12.988092
5168     YE-SN 2017-05-23   1.375641    0.006141       3.610576
544      YE-AM 2017-05-23   3.967424    0.021359       1.432684
1632  YE-HD-AL 2017-05-23   0.000000    0.000000       0.000000
3809     YE-MW 2017-05-24   3.025834    0.030040       0.000000
1361     YE-DH 2017-05-24   1.048868    0.009428       0.467938
5169     YE-SN 2017-05-24   1.375641    0.006141       0.000000
2721     YE-JA 2017-05-24   0.247306    0.000000       0.000000
4081     YE-RA 2017-05-24   0.843773    0.015920       0.000000
1905     YE-HJ 2017-05-24   1.394649    0.021195       0.347712
2993     YE-LA 2017-05-24   0.345464    0.002159       0.686612
4897     YE-SH 2017-05-24   0.000000    0.000000       0.000000
545      YE-AM 2017-05-24   3.967424    0.021359       0.000000
...        ...        ...        ...         ...            ...
1902  YE-HD-AL 2018-02-17   0.005534    0.000000       0.000000
814      YE-AM 2018-02-17   0.191976    0.000000       0.000000
4894     YE-SD 2018-02-17   0.000000    0.000000       0.000000
542      YE-AD 2018-02-17   0.015761    0.000000       0.000000
5166     YE-SH 2018-02-17   0.000000    0.000000       0.000000
2990     YE-JA 2018-02-17   0.114174    0.000000       0.000000
5710     YE-TA 2018-02-17   0.032621    0.000000       0.000000
5438     YE-SN 2018-02-17   0.246903    0.000000       0.000000
2446     YE-HU 2018-02-17   0.250904    0.000000       0.000000
3263     YE-LA 2018-02-18   0.000000    0.000000       0.000000
2175     YE-HJ 2018-02-18   0.000000    0.000000       0.000000
2447     YE-HU 2018-02-18   0.250904    0.000000       1.076938
2991     YE-JA 2018-02-18   0.114174    0.000000       0.000000
3535     YE-MA 2018-02-18   0.005661    0.000000       0.000000
1903  YE-HD-AL 2018-02-18   0.005534    0.000000       0.000000
5439     YE-SN 2018-02-18   0.246903    0.000000       0.000000
4079     YE-MW 2018-02-18   0.548130    0.000000       0.000000
1631     YE-DH 2018-02-18   0.370387    0.000000       0.000000
1359     YE-DA 2018-02-18   0.002371    0.000000       0.000000
2719     YE-IB 2018-02-18   0.189937    0.000000       0.000000
4351     YE-RA 2018-02-18   0.568580    0.000000       0.000000
1087     YE-BA 2018-02-18   0.517968    0.000000       0.000000
4623     YE-SA 2018-02-18   0.840288    0.000000       0.000000
815      YE-AM 2018-02-18   0.191976    0.000000       0.000000
4895     YE-SD 2018-02-18   0.000000    0.000000       0.000000
543      YE-AD 2018-02-18   0.015761    0.000000       0.000000
5167     YE-SH 2018-02-18   0.000000    0.000000       0.000000
271      YE-AB 2018-02-18   0.000000    0.000000       0.000000
3807     YE-MR 2018-02-18   0.000000    0.000000       0.000000
5711     YE-TA 2018-02-18   0.032621    0.000000       0.000000

[5712 rows x 5 columns]

In [53]:
# YE-HD-AL refers to Al Mukulla
neighboring_gov_dict = {"YE-SA" : ["YE-SN"], 
                        "YE-AB" : ["YE-LA", "YE-SH", "YE-BA"], 
                        "YE-AD" : ["YE-LA"], 
                        "YE-DA" : ["YE-LA", "YE-TA", "YE-IB", "YE-BA"], 
                        "YE-BA" : ["YE-DH", "YE-IB", "YE-DA", "YE-AB", "YE-SH", "YE-MA", "YE-SN"], 
                        "YE-HU" : ["YE-HJ", "YE-MW", "YE-SN", "YE-RA", "YE-DH", "YE-TA"], 
                        "YE-JA" : ["YE-MA", "YE-SN", "YE-AM", "YE-SD"], 
                        "YE-MR" : ["YE-HD-AL"], 
                        "YE-MW" : ["YE-HU", "YE-HJ", "YE-AM", "YE-SN"], 
                        "YE-AM" : ["YE-HJ", "YE-SD", "YE-JA", "YE-SN", "YE-MW"], 
                        "YE-DH" : ["YE-IB", "YE-RA", "YE-SN", "YE-BA"], 
                        "YE-HD-AL" : ["YE-SH", "YE-MR"], 
                        "YE-HJ" : ["YE-MW", "YE-HU", "YE-MR"], 
                        "YE-IB" : ["YE-TA", "YE-HU", "YE-DH", "YE-BA", "YE-DA"], 
                        "YE-LA" : ["YE-AD", "YE-TA", "YE-DA", "YE-BA", "YE-AB"], 
                        "YE-MA" : ["YE-BA", "YE-SN", "YE-JA", "YE-SH"], 
                        "YE-RA" : ["YE-DH", "YE-HU", "YE-SN"], 
                        "YE-SD" : ["YE-HJ", "YE-AM", "YE-JA"], 
                        "YE-SN" : ["YE-BA", "YE-DH", "YE-RA", "YE-MW", "YE-AM", "YE-JA", "YE-MA"], 
                        "YE-SH" : ["YE-AB", "YE-BA", "YE-MA", "YE-HD-AL"], 
                        "YE-TA" : ["YE-LA", "YE-DA", "YE-IB", "YE-HU"]}

In [38]:
def get_past_days_features(row, var, daysback):
    if 'rainfall' in var:
        rainfall_df = mean_rainfall_unstacked
        rainfall_df.date = pd.to_datetime(rainfall_df.date, dayfirst = True)
        gov_data = rainfall_df[rainfall_df.gov_iso == row.gov_iso].set_index('date')
        x_days_date = row.date - pd.to_timedelta(daysback, unit='d')
        relevant_gov_data = gov_data.loc[(gov_data.index >= x_days_date) & (gov_data.index < row.date)].sort_index()
        return (pd.Series([np.mean(relevant_gov_data[var]), np.max(relevant_gov_data[var]), kurtosis(relevant_gov_data[var])]))        
    else:  
        gov_data = case_death_rainfall_data[case_death_rainfall_data.gov_iso == row.gov_iso].set_index('date')
        x_days_date = row.date - pd.to_timedelta(daysback, unit='d')
        relevant_gov_data = gov_data.loc[(gov_data.index >= x_days_date) & (gov_data.index < row.date)].sort_index()
        return (pd.Series([np.mean(relevant_gov_data[var]), np.max(relevant_gov_data[var]), kurtosis(relevant_gov_data[var])]))

In [39]:
def get_neighbor_past_days_features(row, var, daysback):
    if 'rainfall' in var:
        rainfall_df = mean_rainfall_unstacked
        rainfall_df.date = pd.to_datetime(rainfall_df.date, dayfirst = True)
        other_gov_data = rainfall_df[rainfall_df.gov_iso.isin(neighboring_gov_dict[row.gov_iso])].set_index('date')
        x_days_date = row.date - pd.to_timedelta(daysback, unit='d')
        relevant_other_gov_data = other_gov_data.loc[(other_gov_data.index >= x_days_date) & (other_gov_data.index < row.date)].sort_index()
        return (pd.Series([np.mean(relevant_other_gov_data[var]), np.max(relevant_other_gov_data[var]), kurtosis(relevant_other_gov_data[var])]))       
    else:    
        other_gov_data = case_death_rainfall_data[case_death_rainfall_data.gov_iso.isin(neighboring_gov_dict[row.gov_iso])].set_index('date')
        x_days_date = row.date - pd.to_timedelta(daysback, unit='d')
        relevant_other_gov_data = other_gov_data.loc[(other_gov_data.index >= x_days_date) & (other_gov_data.index < row.date)].sort_index()
        return (pd.Series([np.mean(relevant_other_gov_data[var]), np.max(relevant_other_gov_data[var]), kurtosis(relevant_other_gov_data[var])]))

In [56]:
past_week_cases = case_death_rainfall_data.apply(get_past_days_features, args = ('new_cases', 7), axis = 1)
past_week_cases.columns = ['mean_past_week_cases', 'max_past_week_cases', 'kurtosis_past_week_cases']
neighbor_past_week_cases = case_death_rainfall_data.apply(get_neighbor_past_days_features, args = ('new_cases', 7), axis = 1)
neighbor_past_week_cases.columns = ['neighbor_mean_past_week_cases', 'neighbor_max_past_week_cases', 'neighbor_kurtosis_past_week_cases']

past_2_week_cases = case_death_rainfall_data.apply(get_past_days_features, args = ('new_cases', 14), axis = 1)
past_2_week_cases.columns = ['mean_past_2_week_cases', 'max_past_2_week_cases', 'kurtosis_past_2_week_cases']
neighbor_past_2_week_cases = case_death_rainfall_data.apply(get_neighbor_past_days_features, args = ('new_cases', 14), axis = 1)
neighbor_past_2_week_cases.columns = ['neighbor_mean_past_2_week_cases', 'neighbor_max_past_2_week_cases', 'neighbor_kurtosis_past_2_week_cases']

past_3_week_cases = case_death_rainfall_data.apply(get_past_days_features, args = ('new_cases', 21), axis = 1)
past_3_week_cases.columns = ['mean_past_3_week_cases', 'max_past_3_week_cases', 'kurtosis_past_3_week_cases']
neighbor_past_3_week_cases = case_death_rainfall_data.apply(get_neighbor_past_days_features, args = ('new_cases', 21), axis = 1)
neighbor_past_3_week_cases.columns = ['neighbor_mean_past_3_week_cases', 'neighbor_max_past_3_week_cases', 'neighbor_kurtosis_past_3_week_cases']

past_month_cases = case_death_rainfall_data.apply(get_past_days_features, args = ('new_cases', 30), axis = 1)
past_month_cases.columns = ['mean_past_month_cases', 'max_past_month_cases', 'kurtosis_past_month_cases']
neighbor_past_month_cases = case_death_rainfall_data.apply(get_neighbor_past_days_features, args = ('new_cases', 30), axis = 1)
neighbor_past_month_cases.columns = ['neighbor_mean_past_month_cases', 'neighbor_max_past_month_cases', 'neighbor_kurtosis_past_month_cases']

past_6_week_cases = case_death_rainfall_data.apply(get_past_days_features, args = ('new_cases', 42), axis = 1)
past_6_week_cases.columns = ['mean_past_6_week_cases', 'max_past_6_week_cases', 'kurtosis_past_6_week_cases']
neighbor_past_6_week_cases = case_death_rainfall_data.apply(get_neighbor_past_days_features, args = ('new_cases', 42), axis = 1)
neighbor_past_6_week_cases.columns = ['neighbor_mean_past_6_week_cases', 'neighbor_max_past_6_week_cases', 'neighbor_kurtosis_past_6_week_cases']

In [57]:
past_week_deaths = case_death_rainfall_data.apply(get_past_days_features, args = ('new_deaths', 7), axis = 1)
past_week_deaths.columns = ['mean_past_week_deaths', 'max_past_week_deaths', 'kurtosis_past_week_deaths']
neighbor_past_week_deaths = case_death_rainfall_data.apply(get_neighbor_past_days_features, args = ('new_deaths', 7), axis = 1)
neighbor_past_week_deaths.columns = ['neighbor_mean_past_week_deaths', 'neighbor_max_past_week_deaths', 'neighbor_kurtosis_past_week_deaths']

past_2_week_deaths = case_death_rainfall_data.apply(get_past_days_features, args = ('new_deaths', 14), axis = 1)
past_2_week_deaths.columns = ['mean_past_2_week_deaths', 'max_past_2_week_deaths', 'kurtosis_past_2_week_deaths']
neighbor_past_2_week_deaths = case_death_rainfall_data.apply(get_neighbor_past_days_features, args = ('new_deaths', 14), axis = 1)
neighbor_past_2_week_deaths.columns = ['neighbor_mean_past_2_week_deaths', 'neighbor_max_past_2_week_deaths', 'neighbor_kurtosis_past_2_week_deaths']

past_month_deaths = case_death_rainfall_data.apply(get_past_days_features, args = ('new_deaths', 30), axis = 1)
past_month_deaths.columns = ['mean_past_month_deaths', 'max_past_month_deaths', 'kurtosis_past_month_deaths']
neighbor_past_month_deaths = case_death_rainfall_data.apply(get_neighbor_past_days_features, args = ('new_deaths', 30), axis = 1)
neighbor_past_month_deaths.columns = ['neighbor_mean_past_month_deaths', 'neighbor_max_past_month_deaths', 'neighbor_kurtosis_past_month_deaths']

In [58]:
past_week_rainfall = case_death_rainfall_data.apply(get_past_days_features, args = ('mean_rainfall', 7), axis = 1)
past_week_rainfall.columns = ['mean_past_week_rainfall', 'max_past_week_rainfall', 'kurtosis_past_week_rainfall']
neighbor_past_week_rainfall = case_death_rainfall_data.apply(get_neighbor_past_days_features, args = ('mean_rainfall', 7), axis = 1)
neighbor_past_week_rainfall.columns = ['neighbor_mean_past_week_rainfall', 'neighbor_max_past_week_rainfall', 'neighbor_kurtosis_past_week_rainfall']

past_2_week_rainfall = case_death_rainfall_data.apply(get_past_days_features, args = ('mean_rainfall', 14), axis = 1)
past_2_week_rainfall.columns = ['mean_past_2_week_rainfall', 'max_past_2_week_rainfall', 'kurtosis_past_2_week_rainfall']
neighbor_past_2_week_rainfall = case_death_rainfall_data.apply(get_neighbor_past_days_features, args = ('mean_rainfall', 14), axis = 1)
neighbor_past_2_week_rainfall.columns = ['neighbor_mean_past_2_week_rainfall', 'neighbor_max_past_2_week_rainfall', 'neighbor_kurtosis_past_2_week_rainfall']

past_month_rainfall = case_death_rainfall_data.apply(get_past_days_features, args = ('mean_rainfall', 30), axis = 1)
past_month_rainfall.columns = ['mean_past_month_rainfall', 'max_past_month_rainfall', 'kurtosis_past_month_rainfall']
neighbor_past_month_rainfall = case_death_rainfall_data.apply(get_neighbor_past_days_features, args = ('mean_rainfall', 30), axis = 1)
neighbor_past_month_rainfall.columns = ['neighbor_mean_past_month_rainfall', 'neighbor_max_past_month_rainfall', 'neighbor_kurtosis_past_month_rainfall']

In [59]:
training_data = pd.concat([case_death_rainfall_data[['gov_iso', 'date', 'weekly_cases']], 
           past_week_cases, past_2_week_cases, past_month_cases, neighbor_past_week_cases, neighbor_past_2_week_cases, neighbor_past_month_cases,
           past_week_deaths, past_2_week_deaths, past_month_deaths, neighbor_past_week_deaths, neighbor_past_2_week_deaths, neighbor_past_month_deaths,
           past_week_rainfall, past_2_week_rainfall, past_month_rainfall, neighbor_past_week_rainfall, neighbor_past_2_week_rainfall, neighbor_past_month_rainfall], axis = 1)

In [60]:
training_data.to_csv('/Users/Rohil/Documents/iGEM/yemen/full_feature_data.csv', index = False)

In [61]:
col_list = []
for col in training_data.columns:
    if ('max' not in col) and ('kurtosis' not in col) & ('deaths' not in col):
        col_list.append(col)

In [62]:
# want to have at least 7 days of data for most of these examples
trunc_training_data = training_data[col_list]
trunc_training_data = trunc_training_data[(trunc_training_data['date'] > '2017-05-30')].sort_values('date')

In [63]:
features = trunc_training_data.iloc[:,3:].columns.tolist()
target = trunc_training_data.iloc[:,2].name

In [64]:
correlations = {}
for f in features:
    data_temp = trunc_training_data[[f,target]]
    x1 = data_temp[f].values
    x2 = data_temp[target].values
    key = f + ' vs ' + target
    correlations[key] = pearsonr(x1,x2)[0]

In [65]:
data_correlations = pd.DataFrame(correlations, index=['Value']).T
data_correlations.loc[data_correlations['Value'].abs().sort_values(ascending=False).index]

                                                       Value
mean_past_week_cases vs weekly_cases                0.918165
mean_past_2_week_cases vs weekly_cases              0.915829
mean_past_month_cases vs weekly_cases               0.887642
neighbor_mean_past_month_rainfall vs weekly_cases   0.426926
neighbor_mean_past_2_week_cases vs weekly_cases     0.426219
neighbor_mean_past_month_cases vs weekly_cases      0.424176
neighbor_mean_past_week_cases vs weekly_cases       0.422416
neighbor_mean_past_2_week_rainfall vs weekly_cases  0.409648
neighbor_mean_past_week_rainfall vs weekly_cases    0.377756
mean_past_month_rainfall vs weekly_cases            0.298683
mean_past_2_week_rainfall vs weekly_cases           0.277123
mean_past_week_rainfall vs weekly_cases             0.253148

In [66]:
trunc_training_data = pd.concat([trunc_training_data, pd.get_dummies(trunc_training_data.gov_iso).sort_index()], axis=1)

In [67]:
trunc_training_data.to_csv('/Users/Rohil/Documents/iGEM/yemen/prelim_training_data.csv', index = False)

In [68]:
trunc_training_data[trunc_training_data.isnull().any(axis=1)]

Empty DataFrame
Columns: [gov_iso, date, weekly_cases, mean_past_week_cases, mean_past_2_week_cases, mean_past_month_cases, neighbor_mean_past_week_cases, neighbor_mean_past_2_week_cases, neighbor_mean_past_month_cases, mean_past_week_rainfall, mean_past_2_week_rainfall, mean_past_month_rainfall, neighbor_mean_past_week_rainfall, neighbor_mean_past_2_week_rainfall, neighbor_mean_past_month_rainfall, YE-AB, YE-AD, YE-AM, YE-BA, YE-DA, YE-DH, YE-HD-AL, YE-HJ, YE-HU, YE-IB, YE-JA, YE-LA, YE-MA, YE-MR, YE-MW, YE-RA, YE-SA, YE-SD, YE-SH, YE-SN, YE-TA]
Index: []

[0 rows x 36 columns]

In [69]:
trunc_training_data.shape

(5397, 36)

In [70]:
trunc_training_data.head()

,gov_iso,date,weekly_cases,mean_past_week_cases,mean_past_2_week_cases,mean_past_month_cases,neighbor_mean_past_week_cases,neighbor_mean_past_2_week_cases,neighbor_mean_past_month_cases,mean_past_week_rainfall,...,YE-LA,YE-MA,YE-MR,YE-MW,YE-RA,YE-SA,YE-SD,YE-SH,YE-SN,YE-TA
8,YE-AB,2017-05-31,7.853387,0.996581,0.984709,0.984709,0.956582,0.954912,0.954912,2.881060,...,0,0,0,0,0,0,0,0,0,0
9,YE-AB,2017-06-01,8.405887,1.012193,0.987618,0.987618,0.906910,0.914979,0.914979,2.881060,...,0,0,0,0,0,0,0,0,0,0
10,YE-AB,2017-06-02,8.958386,1.027805,0.989946,0.989946,0.857238,0.883032,0.883032,2.881060,...,0,0,0,0,0,0,0,0,0,0
11,YE-AB,2017-06-03,9.510886,1.043418,0.991850,0.991850,0.807565,0.856894,0.856894,2.881060,...,0,0,0,0,0,0,0,0,0,0
12,YE-AB,2017-06-04,9.494190,1.059030,0.993437,0.993437,0.757893,0.835112,0.835112,2.668663,...,0,0,0,0,0,0,0,0,0,0

In [71]:
whole_standard_scaler = StandardScaler()

In [72]:
trunc_training_features = trunc_training_data.iloc[:,3:]

In [73]:
trunc_training_features.shape

(5397, 33)

In [74]:
norm_features = whole_standard_scaler.fit_transform(trunc_training_features)

In [79]:
pca = PCA(n_components = 33)

In [80]:
pca.fit(norm_features)

PCA(copy=True, iterated_power='auto', n_components=33, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [81]:
pca.explained_variance_ratio_

array([2.22911228e-01, 8.64879219e-02, 6.18524843e-02, 3.70021221e-02,
       3.18308115e-02, 3.18258591e-02, 3.18214339e-02, 3.18196110e-02,
       3.18189211e-02, 3.18186736e-02, 3.18181954e-02, 3.18181843e-02,
       3.18181818e-02, 3.18181818e-02, 3.18181818e-02, 3.18181818e-02,
       3.18181818e-02, 3.18181818e-02, 3.18181818e-02, 3.18181818e-02,
       2.41188171e-02, 1.63707878e-02, 1.17147778e-02, 1.02743986e-02,
       9.25151255e-03, 2.97153633e-03, 2.58276730e-03, 2.21336647e-03,
       1.42453647e-03, 9.64105304e-04, 4.35307866e-04, 3.07186095e-04,
       4.39614882e-32])

In [111]:
pd.DataFrame(pca.components_, columns = trunc_training_features.columns)

,mean_past_week_cases,mean_past_2_week_cases,mean_past_month_cases,neighbor_mean_past_week_cases,neighbor_mean_past_2_week_cases,neighbor_mean_past_month_cases,mean_past_week_rainfall,mean_past_2_week_rainfall,mean_past_month_rainfall,neighbor_mean_past_week_rainfall,neighbor_mean_past_2_week_rainfall,neighbor_mean_past_month_rainfall
0,0.216672,0.220878,0.219090,0.242954,0.249539,0.249948,0.307285,0.329550,0.325247,0.337397,0.357458,0.349382
1,0.516359,0.523741,0.513780,-0.207022,-0.214150,-0.212123,-0.131309,-0.135808,-0.130384,-0.058788,-0.056403,-0.045405
2,0.114915,0.112379,0.102083,0.479669,0.486344,0.458766,-0.265926,-0.268173,-0.241870,-0.178225,-0.173631,-0.153688
3,0.075176,0.071473,0.063633,0.051369,0.046776,0.025840,0.443879,0.400374,0.293948,-0.443716,-0.431081,-0.391471
4,0.003697,-0.019057,-0.001241,-0.002796,-0.025770,-0.005789,-0.491599,0.001949,0.560845,-0.484289,-0.042189,0.454290
5,0.097356,0.010481,-0.118400,0.630907,0.091042,-0.743257,0.018395,-0.073172,0.061869,0.071886,-0.052261,0.014517
6,-0.032473,-0.004567,0.051363,0.059857,0.008463,-0.064131,-0.528247,0.560534,-0.011851,0.029215,0.390460,-0.491755
7,0.117149,-0.017950,-0.126602,0.055142,-0.007124,-0.058310,0.190615,0.267682,-0.566487,-0.559162,0.329944,0.336174
8,0.649436,0.068915,-0.718801,-0.105713,-0.023252,0.122701,-0.072278,0.007124,0.083839,0.100955,-0.029604,-0.081639
9,-0.029885,0.027788,-0.003441,-0.000564,0.004870,-0.002763,-0.240680,0.499408,-0.292925,0.298839,-0.620543,0.361624
10,-0.081718,0.149208,-0.071195,-0.491160,0.788160,-0.320410,-0.005936,0.000971,0.004854,-0.020604,0.016638,0.011493
11,-0.462559,0.794085,-0.345135,0.091135,-0.149384,0.060768,0.003855,-0.008167,0.005131,-0.030304,0.031684,-0.002498

In [84]:
pca.components_

array([[ 1.55813439e-01,  1.50085258e-01,  8.45372440e-02, ...,
         2.15063135e-01,  1.90250206e-01, -9.68351895e-02],
       [ 2.46495276e-01,  2.51472350e-01, -8.02377833e-03, ...,
        -1.45518408e-02, -2.51903440e-02, -5.45364805e-03],
       [ 7.35322539e-02,  8.50581794e-02,  9.40761724e-03, ...,
        -1.69244606e-01, -1.12156640e-01,  9.82238857e-03],
       ...,
       [-1.28932103e-01,  3.45764802e-02, -8.16526131e-04, ...,
         7.52414660e-03,  1.27779872e-04,  3.14377574e-03],
       [-2.35068890e-01,  9.48844745e-02, -2.01177708e-03, ...,
         2.50962803e-02, -1.68637329e-02,  3.53136318e-03],
       [ 2.95584312e-01, -1.10236270e-01,  5.07402338e-03, ...,
        -1.28955878e-02, -8.28428622e-03, -1.51369758e-03]])

In [110]:
sns.heatmap(np.log(pca.inverse_transform(np.eye(12))))

C:\Users\Rohil\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.

In [85]:
# plots of normalized cases x days back vs today
for column in trunc_training_features.columns:
    fig, ax = plt.subplots(1,1)
    ax.scatter(trunc_training_features[column], trunc_training_data['weekly_cases'])
    ax.set_ylabel('weekly cholera cases')
    ax.set_xlabel(column)
    fig.savefig('/Users/Rohil/Documents/iGEM/yemen/feature_engineering/old/' + column + '_vs_cases.png')
    plt.close()

In [79]:
norm_features = pd.DataFrame(data=norm_features, columns = trunc_training_features.columns)

In [80]:
norm_features

,mean_past_week_cases,max_past_week_cases,kurtosis_past_week_cases,mean_past_2_week_cases,max_past_2_week_cases,kurtosis_past_2_week_cases,mean_past_month_cases,max_past_month_cases,kurtosis_past_month_cases,neighbor_mean_past_week_cases,...,kurtosis_past_month_rainfall,neighbor_mean_past_week_rainfall,neighbor_max_past_week_rainfall,neighbor_kurtosis_past_week_rainfall,neighbor_mean_past_2_week_rainfall,neighbor_max_past_2_week_rainfall,neighbor_kurtosis_past_2_week_rainfall,neighbor_mean_past_month_rainfall,neighbor_max_past_month_rainfall,neighbor_kurtosis_past_month_rainfall
0,-0.283260,-0.389526,-0.749486,-0.306391,-0.457361,-0.796954,-0.338044,-0.548806,-0.834332,-0.355118,...,0.128619,0.406055,0.048174,-0.418341,-0.104365,-0.194035,-0.451726,0.105478,-0.447052,-0.871006
1,-0.099895,-0.313110,-0.749486,-0.106443,-0.391352,-0.796954,-0.131359,-0.493445,-0.834332,0.169770,...,-0.203484,-0.245759,0.056575,0.641940,0.082883,1.439344,1.238922,2.246055,2.304245,-0.598468
2,-0.856788,-0.724903,-0.749486,-0.888588,-0.747066,-0.796954,-0.939859,-0.791777,-0.834332,-0.374284,...,-0.684875,0.582515,1.416685,0.725674,-0.054990,0.912731,0.894877,0.025697,0.427977,0.090509
3,0.555964,0.022476,-0.749486,0.565092,-0.101466,-0.796954,0.562805,-0.250323,-0.834332,-0.423514,...,-0.892478,0.846003,1.416685,0.282570,0.417864,0.912731,0.066051,1.460468,0.707845,-0.775136
4,-0.642816,-0.605861,-0.749486,-0.666013,-0.644236,-0.796954,-0.709784,-0.705535,-0.834332,0.177286,...,-0.715766,2.500680,1.942275,-0.132701,2.073585,1.337795,-0.568614,2.449371,0.767652,-0.847592
5,1.829386,0.985625,-0.749486,1.945463,0.730520,-0.796954,1.989689,0.447452,-0.834332,-0.081176,...,0.126086,-0.586744,-0.587191,-0.567311,-0.303889,-0.316383,-0.498171,1.793484,0.707845,-0.807396
6,0.329272,0.027328,-0.749486,0.304595,-0.097275,-0.796954,0.293530,-0.246808,-0.834332,-0.330098,...,-0.619493,3.002069,1.942275,-0.196482,2.307325,1.337795,-0.551078,2.805322,0.767652,-0.868342
7,-0.843841,-0.709115,-0.749486,-0.876957,-0.733429,-0.796954,-0.927837,-0.780340,-0.834332,0.318346,...,-0.555888,-0.597896,-0.506189,0.491164,-0.149687,0.839081,0.968728,1.968290,1.182383,-0.767143
8,0.877861,0.186443,-0.749486,0.894502,0.040171,-0.796954,0.903314,-0.131533,-0.834332,0.547252,...,-0.383808,0.019925,0.304658,0.224401,0.624492,1.078791,-0.099327,2.460773,1.182383,-0.823906
9,-0.444950,-0.506882,-0.749486,-0.466324,-0.558736,-0.796954,-0.503366,-0.633828,-0.834332,-0.161087,...,-0.889069,1.885539,0.756753,-0.532684,1.579700,1.078791,-0.422217,1.978658,0.683287,-0.805206
10,-0.256871,-0.412032,-0.749486,-0.271739,-0.476802,-0.796954,-0.302224,-0.565111,-0.834332,-0.126347,...,-0.656621,0.558005,0.699550,0.263336,0.754324,0.878937,-0.142373,3.297708,2.304245,-0.703138
11,0.111095,-0.107701,-0.749486,0.084492,-0.213916,-0.796954,0.066010,-0.344632,-0.834332,0.187804,...,-0.869915,0.197048,0.304658,-0.119684,1.047810,1.439344,-0.256338,1.588885,1.576249,-0.540389
12,-0.860599,-0.729549,-1.496377,-0.892011,-0.751080,-1.322903,-0.943397,-0.795144,-1.186875,-1.090138,...,-0.076322,-0.697469,-0.672179,-1.098737,-0.774670,-0.776611,-1.137683,-0.865678,-0.921999,-1.103447
13,-0.700108,-0.633685,-0.749486,-0.729465,-0.668271,-0.796954,-0.775374,-0.725693,-0.834332,-0.096697,...,-0.053009,-0.668458,-0.587191,1.567013,-0.608635,-0.316383,1.033979,1.392347,1.182383,-0.632951
14,-0.618473,-0.573768,-0.749486,-0.648839,-0.616514,-0.796954,-0.692032,-0.682285,-0.834332,-0.009932,...,-0.827667,3.424218,1.942275,-0.543939,2.147959,1.337795,-0.654021,1.917718,0.767652,-0.802713
15,0.291445,0.447158,-0.749486,0.184800,0.265382,-0.796954,0.169698,0.057347,-0.834332,0.015548,...,0.345129,1.213744,1.942275,0.578124,1.744977,1.439344,-0.514181,4.192576,2.304245,-0.824213
16,-0.860599,-0.729549,-1.496377,-0.892011,-0.751080,-1.322903,-0.943397,-0.795144,-1.186875,-1.087611,...,-1.215087,-0.634466,-0.575771,0.143430,-0.740224,-0.698642,0.303512,-0.598783,-0.697715,-0.711795
17,-0.349057,-0.446407,-0.749486,-0.369792,-0.506497,-0.796954,-0.403582,-0.590015,-0.834332,0.022440,...,-0.665520,0.413187,0.304658,-0.298554,0.701071,1.078791,0.097574,1.943864,0.707845,-0.813749
18,-0.695636,-0.619583,-0.749486,-0.727041,-0.656089,-0.796954,-0.772868,-0.715476,-0.834332,-0.313702,...,0.423545,-0.395050,-0.271537,0.189702,-0.498603,-0.316383,0.082674,0.184102,0.707845,0.013272
19,1.192986,0.471484,-0.749486,1.247560,0.286396,-0.796954,1.268269,0.074971,-0.834332,-0.122403,...,-0.284270,-0.570977,-0.506189,-0.033214,0.111595,1.439344,0.738904,1.941965,1.576249,-0.706559
20,-0.387926,-0.378856,-0.749486,-0.425876,-0.448145,-0.796954,-0.461555,-0.541077,-0.834332,-0.768993,...,1.139623,1.514153,0.048174,-0.737553,0.602757,-0.194035,-0.795978,0.700376,-0.447052,-0.990067
21,-0.702195,-0.619583,-0.474285,-0.735682,-0.656089,-0.597633,-0.781801,-0.715476,-0.700727,-0.329528,...,0.423545,-0.395050,-0.271537,0.189702,-0.503589,-0.316383,0.084113,0.149473,0.707845,0.019070
22,1.738931,0.985625,-0.692949,1.932357,0.730520,-0.752314,1.976141,0.447452,-0.804410,-0.061916,...,0.126086,-0.586744,-0.587191,-0.567311,-0.303889,-0.316383,-0.498171,1.709752,0.707845,-0.807100
23,-0.161937,0.266307,1.480827,-0.260290,0.109159,1.058617,-0.290390,-0.073674,0.409456,-0.795301,...,1.139623,1.373161,0.048174,-0.764176,0.456831,-0.194035,-0.777612,0.700376,-0.447052,-0.990067
24,-0.243509,-0.363155,1.970975,-0.260681,-0.434582,1.535081,-0.290794,-0.529702,0.728828,-0.127974,...,-0.660568,0.532177,0.699550,0.258271,0.599819,0.878937,-0.048476,3.238503,2.304245,-0.704575
25,0.489216,0.022476,1.911023,0.514051,-0.101466,1.477403,0.510044,-0.250323,0.690167,-0.414958,...,-0.887256,0.809029,1.416685,0.278415,0.321219,0.912731,0.151694,1.438947,0.707845,-0.775397
26,-0.856534,-0.724903,-0.728200,-0.888765,-0.747066,-0.705372,-0.940042,-0.791777,-0.772945,-0.395593,...,-0.684058,0.582515,1.416685,0.725674,-0.072818,0.912731,0.895715,0.013540,0.427977,0.091712
27,0.914023,0.318716,1.897053,0.924818,0.154431,1.456560,0.934652,-0.035705,0.676196,0.627629,...,-0.324122,-0.038536,0.304658,0.249043,0.563840,1.078791,-0.093697,2.400154,1.182383,-0.824832
28,0.234322,0.143390,0.219602,0.166539,0.002982,-0.063039,0.150822,-0.162723,-0.342389,0.230912,...,-0.870673,0.142900,0.304658,-0.103148,0.964496,1.439344,-0.252502,1.419214,1.576249,-0.506405
29,-0.860599,-0.729549,-1.496377,-0.892011,-0.751080,-1.322903,-0.943397,-0.795144,-1.186875,-1.087442,...,-1.215087,-0.634466,-0.575771,0.143430,-0.740295,-0.698642,0.303523,-0.613689,-0.697715,-0.702243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5367,-0.655550,-0.616934,-0.186446,-0.693715,-0.653801,-0.761394,-0.706269,-0.660107,-0.521594,-0.833203,...,0.999210,-0.115010,0.477451,0.695994,-0.411501,0.153137,0.754736,-0.669940,-0.179024,1.047494
5368,-0.739605,-0.662394,-0.186446,-0.761705,-0.686187,-0.167491,-0.751175,-0.680110,-0.676785,-0.806632,...,1.508296,-0.342182,0.274675,1.739033,-0.579902,-0.010855,1.992745,-0.759858,-0.310073,2.409512
5369,-0.860599,-0.729549,-1.496377,-0.891888,-0.750702,0.822415,-0.942656,-0.794509,-0.712148,-0.997760,...,1.387793,-0.644094,-0.549275,0.860683,-0.734569,-0.677214,0.711394,-0.841377,-0.842570,0.967919
5370,-0.860344,-0.729082,-0.186446,-0.891552,-0.750677,-0.907680,-0.942291,-0.792776,0.294837,-1.004591,...,1.527040,-0.260262,0.411561,1.981700,-0.486972,0.099849,1.856071,-0.712349,-0.221608,2.263880
5371,-0.584864,-0.582063,-0.186446,-0.590141,-0.550367,0.715306,-0.548014,-0.593066,-0.809423,-0.994003,...,-0.158743,-0.083067,0.477451,0.752382,-0.439450,0.153137,0.944095,-0.691305,-0.179024,1.273754
5372,-0.667840,-0.625249,-0.186446,-0.680141,-0.628735,0.721695,-0.622508,-0.603867,-0.590167,-0.953069,...,0.678176,-0.214199,0.477451,1.107745,-0.503064,0.153137,1.329691,-0.708403,-0.179024,1.648500
5373,-0.859422,-0.727396,-0.186446,-0.889896,-0.749220,-0.907680,-0.941211,-0.792024,-0.426626,-0.960732,...,1.596553,-0.475642,-0.488607,-0.489410,-0.592195,-0.540690,-0.284129,-0.756891,-0.733471,-0.243303
5374,-0.845980,-0.715854,-0.186446,-0.862636,-0.713337,0.471325,-0.900401,-0.763489,-0.716378,-0.986101,...,1.523771,-0.013642,0.477451,0.412027,-0.399891,0.153137,0.576064,-0.652242,-0.179024,0.829315
5375,-0.860599,-0.729549,-1.496377,-0.892011,-0.751080,-1.322903,-0.943397,-0.795144,-1.186875,-1.090138,...,0.222271,-0.697469,-0.672179,-1.098737,-0.774670,-0.776611,-1.137683,-0.865678,-0.921999,-1.103447
5376,-0.650320,-0.616934,2.065716,-0.691641,-0.653801,-0.866073,-0.703656,-0.660107,-0.518759,-0.837003,...,0.999210,-0.664030,-0.570726,1.591903,-0.411501,0.153137,0.754736,-0.680803,-0.179024,1.077399
5377,-0.860472,-0.729082,2.065716,-0.891552,-0.750677,-0.907680,-0.942513,-0.792776,0.896162,-1.004122,...,1.596553,-0.657342,-0.570726,1.113076,-0.486972,0.099849,1.856071,-0.715945,-0.221608,2.274738
5378,-0.741109,-0.662394,2.065716,-0.763595,-0.686187,0.165591,-0.757750,-0.680110,-0.609168,-0.809466,...,1.557529,-0.697469,-0.672179,-1.098737,-0.579902,-0.010855,1.992745,-0.767421,-0.310073,2.459215
5379,-0.858446,-0.728236,2.065716,-0.890906,-0.749946,-0.873078,-0.942864,-0.794192,-0.282324,-0.966736,...,1.596553,-0.697469,-0.672179,-1.098737,-0.692077,-0.628150,0.030410,-0.816444,-0.803362,-0.027492
5380,-0.581610,-0.582063,2.065716,-0.602050,-0.550367,3.157760,-0.547769,-0.593066,-0.808910,-0.994180,...,0.161118,-0.697469,-0.672179,-1.098737,-0.439450,0.153137,0.944095,-0.700616,-0.179024,1.303478
5381,-0.860599,-0.729549,-1.496377,-0.892011,-0.751080,-1.322903,-0.943397,-0.795144,-1.186875,-1.090138,...,-1.215087,-0.686175,-0.655157,0.142620,-0.745043,-0.729208,0.076506,-0.843337,-0.884119,-0.079975
5382,-0.530269,-0.533329,2.065716,-0.513292,-0.480477,2.459116,-0.366254,-0.496492,-0.815979,-0.815471,...,1.596553,-0.697469,-0.672179,-1.098737,-0.347108,0.153137,0.617036,-0.646093,-0.179024,0.920124
5383,-0.483810,-0.524053,2.065716,-0.495515,-0.565917,-0.472843,-0.499387,-0.595359,-0.528451,-0.916849,...,-1.215087,-0.697469,-0.672179,-1.098737,-0.512249,0.153137,1.688213,-0.727981,-0.179024,2.124738
5384,-0.569115,-0.563910,2.065716,-0.578156,-0.598532,-0.627436,-0.543514,-0.596496,-0.664319,-0.817731,...,1.595952,-0.697469,-0.672179,-1.098737,-0.352949,0.153137,0.308706,-0.648581,-0.179024,0.578686
5385,-0.453611,-0.514932,2.065716,-0.474208,-0.506860,2.742075,-0.391816,-0.490042,-0.605500,-0.931652,...,1.596553,-0.697469,-0.672179,-1.098737,0.042531,0.153137,-0.469186,-0.442063,-0.179024,-0.292026
5386,-0.843642,-0.720006,2.065716,-0.874101,-0.742837,-0.764682,-0.926010,-0.788230,-0.639502,-1.089969,...,1.596553,-0.697469,-0.672179,-1.098737,-0.644181,-0.628150,-0.469186,-0.803346,-0.803362,-0.280606
5387,-0.860599,-0.729549,-1.496377,-0.892011,-0.751080,-1.322903,-0.943397,-0.795144,-1.186875,-0.996915,...,1.596553,-0.697469,-0.672179,-1.098737,-0.671558,-0.479224,1.079364,-0.809088,-0.684353,1.251456
5388,-0.767886,-0.678464,2.065716,-0.808999,-0.702080,-0.858664,-0.829081,-0.730817,-0.589333,-0.876089,...,1.596553,-0.657342,-0.570726,1.113076,-0.431818,0.099849,1.371634,-0.687041,-0.221608,1.730033
5389,-0.848298,-0.715854,2.065716,-0.868035,-0.713337,2.108093,-0.900313,-0.763489,-0.716016,-0.987053,...,1.550614,-0.697469,-0.672179,-1.098737,-0.399891,0.153137,0.576064,-0.666380,-0.179024,0.856341
5390,-0.859158,-0.728403,2.065716,-0.889503,-0.746131,3.394010,-0.599099,-0.332624,-0.515206,-0.830585,...,1.502423,-0.689940,-0.655157,0.859349,-0.700140,-0.628518,0.617219,-0.820783,-0.803656,0.822345
5391,-0.860599,-0.729549,-1.496377,-0.891891,-0.750340,3.691711,-0.942991,-0.794523,-0.466000,-0.953928,...,1.596553,-0.697469,-0.672179,-1.098737,-0.517592,0.153137,1.725102,-0.726489,-0.179024,2.134612
5392,-0.860599,-0.729549,-1.496377,-0.891950,-0.750702,3.691711,-0.942686,-0.794509,-0.717795,-0.999445,...,1.407228,-0.697469,-0.672179,-1.098737,-0.734569,-0.677214,0.711394,-0.844000,-0.842570,1.030999
5393,-0.669207,-0.625249,2.065716,-0.686082,-0.628735,3.190526,-0.627198,-0.603867,-0.580672,-0.954844,...,0.941629,-0.697469,-0.672179,-1.098737,-0.503064,0.153137,1.329691,-0.719389,-0.179024,1.690973
5394,-0.860011,-0.727396,2.065716,-0.889896,-0.749220,-0.907680,-0.941503,-0.792024,-0.275584,-0.958365,...,1.596553,-0.647310,-0.570726,0.634784,-0.592195,-0.540690,-0.284129,-0.763131,-0.733471,-0.218104
5395,-0.860599,-0.729549,-1.496377,-0.892011,-0.751080,-1.322903,-0.943397,-0.795144,-1.186875,-1.090138,...,-0.303444,-0.697469,-0.672179,-1.098737,-0.774670,-0.776611,-1.137683,-0.865678,-0.921999,-1.103447
5396,-0.835030,-0.712932,2.065716,-0.861805,-0.732051,0.137326,-0.882869,-0.748434,-0.536063,-0.989432,...,0.551932,-0.697469,-0.672179,-1.098737,-0.467707,0.099849,1.418668,-0.716172,-0.221608,1.848408